
# set_max_fanout 10 [current_design]
set_max_transition 0.5 [current_design]
# set_dont_touch [get_ports *]
set_load -pin_load 3 [get_ports rocc_cmd_v_o]
set_load -pin_load 3 [get_ports {rocc_cmd_data_o_15}]
set_load -pin_load 3 [get_ports {rocc_cmd_data_o_14}]
set_load -pin_load 3 [get_ports {rocc_cmd_data_o_13}]
set_load -pin_load 3 [get_ports {rocc_cmd_data_o_12}]
set_load -pin_load 3 [get_ports {rocc_cmd_data_o_11}]
set_load -pin_load 3 [get_ports {rocc_cmd_data_o_10}]
set_load -pin_load 3 [get_ports {rocc_cmd_data_o_9}]
set_load -pin_load 3 [get_ports {rocc_cmd_data_o_8}]
set_load -pin_load 3 [get_ports {rocc_cmd_data_o_7}]
set_load -pin_load 3 [get_ports {rocc_cmd_data_o_6}]
set_load -pin_load 3 [get_ports {rocc_cmd_data_o_5}]
set_load -pin_load 3 [get_ports {rocc_cmd_data_o_4}]
set_load -pin_load 3 [get_ports {rocc_cmd_data_o_3}]
set_load -pin_load 3 [get_ports {rocc_cmd_data_o_2}]
set_load -pin_load 3 [get_ports {rocc_cmd_data_o_1}]
set_load -pin_load 3 [get_ports {rocc_cmd_data_o_0}]
set_load -pin_load 3 [get_ports rocc_resp_ready_o]
set_load -pin_load 3 [get_ports rocc_mem_req_ready_o]
set_load -pin_load 3 [get_ports rocc_mem_resp_v_o]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_63}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_62}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_61}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_60}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_59}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_58}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_57}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_56}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_55}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_54}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_53}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_52}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_51}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_50}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_49}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_48}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_47}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_46}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_45}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_44}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_43}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_42}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_41}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_40}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_39}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_38}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_37}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_36}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_35}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_34}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_33}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_32}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_31}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_30}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_29}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_28}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_27}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_26}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_25}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_24}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_23}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_22}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_21}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_20}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_19}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_18}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_17}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_16}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_15}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_14}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_13}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_12}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_11}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_10}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_9}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_8}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_7}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_6}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_5}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_4}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_3}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_2}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_1}]
set_load -pin_load 3 [get_ports {rocc_mem_resp_data_o_0}]
set_load -pin_load 3 [get_ports rocc_ctrl_o_s_]
set_load -pin_load 3 [get_ports rocc_ctrl_o_exception_]
set_load -pin_load 3 [get_ports rocc_ctrl_o_host_id_]
set_load -pin_load 3 [get_ports fsb_node_ready_o]
set_load -pin_load 3 [get_ports fsb_node_v_o]
set_load -pin_load 3 [get_ports {fsb_node_data_o_7}]
set_load -pin_load 3 [get_ports {fsb_node_data_o_6}]
set_load -pin_load 3 [get_ports {fsb_node_data_o_5}]
set_load -pin_load 3 [get_ports {fsb_node_data_o_4}]
set_load -pin_load 3 [get_ports {fsb_node_data_o_3}]
set_load -pin_load 3 [get_ports {fsb_node_data_o_2}]
set_load -pin_load 3 [get_ports {fsb_node_data_o_1}]
set_load -pin_load 3 [get_ports {fsb_node_data_o_0}]
set_max_transition 0.069 [get_ports rocc_cmd_v_o]
set_max_transition 0.069 [get_ports {rocc_cmd_data_o_15}]
set_max_transition 0.069 [get_ports {rocc_cmd_data_o_14}]
set_max_transition 0.069 [get_ports {rocc_cmd_data_o_13}]
set_max_transition 0.069 [get_ports {rocc_cmd_data_o_12}]
set_max_transition 0.069 [get_ports {rocc_cmd_data_o_11}]
set_max_transition 0.069 [get_ports {rocc_cmd_data_o_10}]
set_max_transition 0.069 [get_ports {rocc_cmd_data_o_9}]
set_max_transition 0.069 [get_ports {rocc_cmd_data_o_8}]
set_max_transition 0.069 [get_ports {rocc_cmd_data_o_7}]
set_max_transition 0.069 [get_ports {rocc_cmd_data_o_6}]
set_max_transition 0.069 [get_ports {rocc_cmd_data_o_5}]
set_max_transition 0.069 [get_ports {rocc_cmd_data_o_4}]
set_max_transition 0.069 [get_ports {rocc_cmd_data_o_3}]
set_max_transition 0.069 [get_ports {rocc_cmd_data_o_2}]
set_max_transition 0.069 [get_ports {rocc_cmd_data_o_1}]
set_max_transition 0.069 [get_ports {rocc_cmd_data_o_0}]
set_max_transition 0.069 [get_ports rocc_resp_ready_o]
set_max_transition 0.069 [get_ports rocc_mem_req_ready_o]
set_max_transition 0.069 [get_ports rocc_mem_resp_v_o]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_63}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_62}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_61}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_60}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_59}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_58}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_57}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_56}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_55}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_54}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_53}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_52}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_51}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_50}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_49}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_48}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_47}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_46}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_45}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_44}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_43}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_42}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_41}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_40}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_39}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_38}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_37}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_36}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_35}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_34}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_33}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_32}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_31}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_30}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_29}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_28}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_27}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_26}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_25}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_24}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_23}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_22}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_21}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_20}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_19}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_18}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_17}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_16}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_15}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_14}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_13}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_12}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_11}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_10}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_9}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_8}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_7}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_6}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_5}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_4}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_3}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_2}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_1}]
set_max_transition 0.069 [get_ports {rocc_mem_resp_data_o_0}]
set_max_transition 0.069 [get_ports rocc_ctrl_o_s_]
set_max_transition 0.069 [get_ports rocc_ctrl_o_exception_]
set_max_transition 0.069 [get_ports rocc_ctrl_o_host_id_]
set_max_transition 0.069 [get_ports fsb_node_ready_o]
set_max_transition 0.069 [get_ports fsb_node_v_o]
set_max_transition 0.069 [get_ports {fsb_node_data_o_7}]
set_max_transition 0.069 [get_ports {fsb_node_data_o_6}]
set_max_transition 0.069 [get_ports {fsb_node_data_o_5}]
set_max_transition 0.069 [get_ports {fsb_node_data_o_4}]
set_max_transition 0.069 [get_ports {fsb_node_data_o_3}]
set_max_transition 0.069 [get_ports {fsb_node_data_o_2}]
set_max_transition 0.069 [get_ports {fsb_node_data_o_1}]
set_max_transition 0.069 [get_ports {fsb_node_data_o_0}]
create_clock [get_pins u_clk.u_in/IN]  -name core_clk  -period 50  -waveform {0 2.5}
set_clock_latency -source 0  [get_clocks core_clk]
set_clock_uncertainty 0.03  [get_clocks core_clk]
set_clock_transition -min -fall 0.069 [get_clocks core_clk]
set_clock_transition -min -rise 0.069 [get_clocks core_clk]
set_clock_transition -max -fall 0.069 [get_clocks core_clk]
set_clock_transition -max -rise 0.069 [get_clocks core_clk]
set_false_path   -to [list [get_ports rocc_ctrl_o_s_] [get_ports rocc_ctrl_o_exception_] [get_ports rocc_ctrl_o_host_id_]]
set_input_delay -clock core_clk  2.51  [get_ports rocc_cmd_ready_i]
set_input_delay -clock core_clk  2.51  [get_ports rocc_resp_v_i]
set_input_delay -clock core_clk  2.51  [get_ports {rocc_resp_data_i[7]}]
set_input_delay -clock core_clk  2.51  [get_ports {rocc_resp_data_i[6]}]
set_input_delay -clock core_clk  2.51  [get_ports {rocc_resp_data_i[5]}]
set_input_delay -clock core_clk  2.51  [get_ports {rocc_resp_data_i[4]}]
set_input_delay -clock core_clk  2.51  [get_ports {rocc_resp_data_i[3]}]
set_input_delay -clock core_clk  2.51  [get_ports {rocc_resp_data_i[2]}]
set_input_delay -clock core_clk  2.51  [get_ports {rocc_resp_data_i[1]}]
set_input_delay -clock core_clk  2.51  [get_ports {rocc_resp_data_i[0]}]
set_input_delay -clock core_clk  3.01  [get_ports rocc_mem_req_v_i]
set_input_delay -clock core_clk  2.76  [get_ports {rocc_mem_req_data_i[31]}]
set_input_delay -clock core_clk  2.76  [get_ports {rocc_mem_req_data_i[30]}]
set_input_delay -clock core_clk  2.76  [get_ports {rocc_mem_req_data_i[29]}]
set_input_delay -clock core_clk  2.76  [get_ports {rocc_mem_req_data_i[28]}]
set_input_delay -clock core_clk  2.76  [get_ports {rocc_mem_req_data_i[27]}]
set_input_delay -clock core_clk  2.76  [get_ports {rocc_mem_req_data_i[26]}]
set_input_delay -clock core_clk  2.76  [get_ports {rocc_mem_req_data_i[25]}]
set_input_delay -clock core_clk  2.76  [get_ports {rocc_mem_req_data_i[24]}]
set_input_delay -clock core_clk  2.76  [get_ports {rocc_mem_req_data_i[23]}]
set_input_delay -clock core_clk  2.76  [get_ports {rocc_mem_req_data_i[22]}]
set_input_delay -clock core_clk  2.76  [get_ports {rocc_mem_req_data_i[21]}]
set_input_delay -clock core_clk  2.76  [get_ports {rocc_mem_req_data_i[20]}]
set_input_delay -clock core_clk  2.76  [get_ports {rocc_mem_req_data_i[19]}]
set_input_delay -clock core_clk  2.76  [get_ports {rocc_mem_req_data_i[18]}]
set_input_delay -clock core_clk  2.76  [get_ports {rocc_mem_req_data_i[17]}]
set_input_delay -clock core_clk  2.76  [get_ports {rocc_mem_req_data_i[16]}]
set_input_delay -clock core_clk  2.76  [get_ports {rocc_mem_req_data_i[15]}]
set_input_delay -clock core_clk  2.76  [get_ports {rocc_mem_req_data_i[14]}]
set_input_delay -clock core_clk  2.76  [get_ports {rocc_mem_req_data_i[13]}]
set_input_delay -clock core_clk  2.76  [get_ports {rocc_mem_req_data_i[12]}]
set_input_delay -clock core_clk  2.76  [get_ports {rocc_mem_req_data_i[11]}]
set_input_delay -clock core_clk  2.76  [get_ports {rocc_mem_req_data_i[10]}]
set_input_delay -clock core_clk  2.76  [get_ports {rocc_mem_req_data_i[9]}]
set_input_delay -clock core_clk  2.76  [get_ports {rocc_mem_req_data_i[8]}]
set_input_delay -clock core_clk  2.76  [get_ports {rocc_mem_req_data_i[7]}]
set_input_delay -clock core_clk  2.76  [get_ports {rocc_mem_req_data_i[6]}]
set_input_delay -clock core_clk  2.76  [get_ports {rocc_mem_req_data_i[5]}]
set_input_delay -clock core_clk  2.76  [get_ports {rocc_mem_req_data_i[4]}]
set_input_delay -clock core_clk  2.76  [get_ports {rocc_mem_req_data_i[3]}]
set_input_delay -clock core_clk  2.76  [get_ports {rocc_mem_req_data_i[2]}]
set_input_delay -clock core_clk  2.76  [get_ports {rocc_mem_req_data_i[1]}]
set_input_delay -clock core_clk  2.76  [get_ports {rocc_mem_req_data_i[0]}]
set_input_delay -clock core_clk  2.76  [get_ports rocc_ctrl_i_busy_]
set_input_delay -clock core_clk  2.76  [get_ports rocc_ctrl_i_interrupt_]
set_input_delay -clock core_clk  2.51  [get_ports fsb_node_v_i]
set_input_delay -clock core_clk  2.51  [get_ports {fsb_node_data_i[7]}]
set_input_delay -clock core_clk  2.51  [get_ports {fsb_node_data_i[6]}]
set_input_delay -clock core_clk  2.51  [get_ports {fsb_node_data_i[5]}]
set_input_delay -clock core_clk  2.51  [get_ports {fsb_node_data_i[4]}]
set_input_delay -clock core_clk  2.51  [get_ports {fsb_node_data_i[3]}]
set_input_delay -clock core_clk  2.51  [get_ports {fsb_node_data_i[2]}]
set_input_delay -clock core_clk  2.51  [get_ports {fsb_node_data_i[1]}]
set_input_delay -clock core_clk  2.51  [get_ports {fsb_node_data_i[0]}]
set_input_delay -clock core_clk  3.01  [get_ports fsb_node_yumi_i]
set_input_delay -clock core_clk  2.51  [get_ports reset_i]
set_input_delay -clock core_clk  2.51  [get_ports en_i]
set_output_delay -clock core_clk  2.51  [get_ports rocc_cmd_v_o]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_cmd_data_o_15}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_cmd_data_o_14}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_cmd_data_o_13}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_cmd_data_o_12}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_cmd_data_o_11}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_cmd_data_o_10}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_cmd_data_o_9}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_cmd_data_o_8}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_cmd_data_o_7}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_cmd_data_o_6}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_cmd_data_o_5}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_cmd_data_o_4}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_cmd_data_o_3}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_cmd_data_o_2}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_cmd_data_o_1}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_cmd_data_o_0}]
set_output_delay -clock core_clk  2.76  [get_ports rocc_mem_req_ready_o]
set_output_delay -clock core_clk  2.51  [get_ports rocc_mem_resp_v_o]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_63}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_62}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_61}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_60}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_59}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_58}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_57}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_56}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_55}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_54}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_53}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_52}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_51}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_50}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_49}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_48}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_47}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_46}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_45}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_44}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_43}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_42}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_41}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_40}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_39}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_38}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_37}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_36}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_35}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_34}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_33}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_32}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_31}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_30}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_29}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_28}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_27}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_26}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_25}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_24}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_23}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_22}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_21}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_20}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_19}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_18}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_17}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_16}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_15}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_14}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_13}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_12}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_11}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_10}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_9}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_8}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_7}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_6}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_5}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_4}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_3}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_2}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_1}]
set_output_delay -clock core_clk  2.51  [get_ports {rocc_mem_resp_data_o_0}]
set_output_delay -clock core_clk  2.51  [get_ports rocc_ctrl_o_s_]
set_output_delay -clock core_clk  2.51  [get_ports rocc_ctrl_o_exception_]
set_output_delay -clock core_clk  2.51  [get_ports rocc_ctrl_o_host_id_]
set_output_delay -clock core_clk  2.51  [get_ports rocc_resp_ready_o]
set_output_delay -clock core_clk  2.51  [get_ports fsb_node_ready_o]
set_output_delay -clock core_clk  3.01  [get_ports fsb_node_v_o]
set_output_delay -clock core_clk  2.51  [get_ports {fsb_node_data_o_7}]
set_output_delay -clock core_clk  2.51  [get_ports {fsb_node_data_o_6}]
set_output_delay -clock core_clk  2.51  [get_ports {fsb_node_data_o_5}]
set_output_delay -clock core_clk  2.51  [get_ports {fsb_node_data_o_4}]
set_output_delay -clock core_clk  2.51  [get_ports {fsb_node_data_o_3}]
set_output_delay -clock core_clk  2.51  [get_ports {fsb_node_data_o_2}]
set_output_delay -clock core_clk  2.51  [get_ports {fsb_node_data_o_1}]
set_output_delay -clock core_clk  2.51  [get_ports {fsb_node_data_o_0}]
set_input_transition -max 0.069  [get_ports clk_i]
set_input_transition -min 0.069  [get_ports clk_i]
set_input_transition -max 0.069  [get_ports reset_i]
set_input_transition -min 0.069  [get_ports reset_i]
set_input_transition -max 0.069  [get_ports en_i]
set_input_transition -min 0.069  [get_ports en_i]
set_input_transition -max 0.069  [get_ports rocc_cmd_ready_i]
set_input_transition -min 0.069  [get_ports rocc_cmd_ready_i]
set_input_transition -max 0.069  [get_ports rocc_resp_v_i]
set_input_transition -min 0.069  [get_ports rocc_resp_v_i]
set_input_transition -max 0.069  [get_ports {rocc_resp_data_i[7]}]
set_input_transition -min 0.069  [get_ports {rocc_resp_data_i[7]}]
set_input_transition -max 0.069  [get_ports {rocc_resp_data_i[6]}]
set_input_transition -min 0.069  [get_ports {rocc_resp_data_i[6]}]
set_input_transition -max 0.069  [get_ports {rocc_resp_data_i[5]}]
set_input_transition -min 0.069  [get_ports {rocc_resp_data_i[5]}]
set_input_transition -max 0.069  [get_ports {rocc_resp_data_i[4]}]
set_input_transition -min 0.069  [get_ports {rocc_resp_data_i[4]}]
set_input_transition -max 0.069  [get_ports {rocc_resp_data_i[3]}]
set_input_transition -min 0.069  [get_ports {rocc_resp_data_i[3]}]
set_input_transition -max 0.069  [get_ports {rocc_resp_data_i[2]}]
set_input_transition -min 0.069  [get_ports {rocc_resp_data_i[2]}]
set_input_transition -max 0.069  [get_ports {rocc_resp_data_i[1]}]
set_input_transition -min 0.069  [get_ports {rocc_resp_data_i[1]}]
set_input_transition -max 0.069  [get_ports {rocc_resp_data_i[0]}]
set_input_transition -min 0.069  [get_ports {rocc_resp_data_i[0]}]
set_input_transition -max 0.069  [get_ports rocc_mem_req_v_i]
set_input_transition -min 0.069  [get_ports rocc_mem_req_v_i]
set_input_transition -max 0.069  [get_ports {rocc_mem_req_data_i[31]}]
set_input_transition -min 0.069  [get_ports {rocc_mem_req_data_i[31]}]
set_input_transition -max 0.069  [get_ports {rocc_mem_req_data_i[30]}]
set_input_transition -min 0.069  [get_ports {rocc_mem_req_data_i[30]}]
set_input_transition -max 0.069  [get_ports {rocc_mem_req_data_i[29]}]
set_input_transition -min 0.069  [get_ports {rocc_mem_req_data_i[29]}]
set_input_transition -max 0.069  [get_ports {rocc_mem_req_data_i[28]}]
set_input_transition -min 0.069  [get_ports {rocc_mem_req_data_i[28]}]
set_input_transition -max 0.069  [get_ports {rocc_mem_req_data_i[27]}]
set_input_transition -min 0.069  [get_ports {rocc_mem_req_data_i[27]}]
set_input_transition -max 0.069  [get_ports {rocc_mem_req_data_i[26]}]
set_input_transition -min 0.069  [get_ports {rocc_mem_req_data_i[26]}]
set_input_transition -max 0.069  [get_ports {rocc_mem_req_data_i[25]}]
set_input_transition -min 0.069  [get_ports {rocc_mem_req_data_i[25]}]
set_input_transition -max 0.069  [get_ports {rocc_mem_req_data_i[24]}]
set_input_transition -min 0.069  [get_ports {rocc_mem_req_data_i[24]}]
set_input_transition -max 0.069  [get_ports {rocc_mem_req_data_i[23]}]
set_input_transition -min 0.069  [get_ports {rocc_mem_req_data_i[23]}]
set_input_transition -max 0.069  [get_ports {rocc_mem_req_data_i[22]}]
set_input_transition -min 0.069  [get_ports {rocc_mem_req_data_i[22]}]
set_input_transition -max 0.069  [get_ports {rocc_mem_req_data_i[21]}]
set_input_transition -min 0.069  [get_ports {rocc_mem_req_data_i[21]}]
set_input_transition -max 0.069  [get_ports {rocc_mem_req_data_i[20]}]
set_input_transition -min 0.069  [get_ports {rocc_mem_req_data_i[20]}]
set_input_transition -max 0.069  [get_ports {rocc_mem_req_data_i[19]}]
set_input_transition -min 0.069  [get_ports {rocc_mem_req_data_i[19]}]
set_input_transition -max 0.069  [get_ports {rocc_mem_req_data_i[18]}]
set_input_transition -min 0.069  [get_ports {rocc_mem_req_data_i[18]}]
set_input_transition -max 0.069  [get_ports {rocc_mem_req_data_i[17]}]
set_input_transition -min 0.069  [get_ports {rocc_mem_req_data_i[17]}]
set_input_transition -max 0.069  [get_ports {rocc_mem_req_data_i[16]}]
set_input_transition -min 0.069  [get_ports {rocc_mem_req_data_i[16]}]
set_input_transition -max 0.069  [get_ports {rocc_mem_req_data_i[15]}]
set_input_transition -min 0.069  [get_ports {rocc_mem_req_data_i[15]}]
set_input_transition -max 0.069  [get_ports {rocc_mem_req_data_i[14]}]
set_input_transition -min 0.069  [get_ports {rocc_mem_req_data_i[14]}]
set_input_transition -max 0.069  [get_ports {rocc_mem_req_data_i[13]}]
set_input_transition -min 0.069  [get_ports {rocc_mem_req_data_i[13]}]
set_input_transition -max 0.069  [get_ports {rocc_mem_req_data_i[12]}]
set_input_transition -min 0.069  [get_ports {rocc_mem_req_data_i[12]}]
set_input_transition -max 0.069  [get_ports {rocc_mem_req_data_i[11]}]
set_input_transition -min 0.069  [get_ports {rocc_mem_req_data_i[11]}]
set_input_transition -max 0.069  [get_ports {rocc_mem_req_data_i[10]}]
set_input_transition -min 0.069  [get_ports {rocc_mem_req_data_i[10]}]
set_input_transition -max 0.069  [get_ports {rocc_mem_req_data_i[9]}]
set_input_transition -min 0.069  [get_ports {rocc_mem_req_data_i[9]}]
set_input_transition -max 0.069  [get_ports {rocc_mem_req_data_i[8]}]
set_input_transition -min 0.069  [get_ports {rocc_mem_req_data_i[8]}]
set_input_transition -max 0.069  [get_ports {rocc_mem_req_data_i[7]}]
set_input_transition -min 0.069  [get_ports {rocc_mem_req_data_i[7]}]
set_input_transition -max 0.069  [get_ports {rocc_mem_req_data_i[6]}]
set_input_transition -min 0.069  [get_ports {rocc_mem_req_data_i[6]}]
set_input_transition -max 0.069  [get_ports {rocc_mem_req_data_i[5]}]
set_input_transition -min 0.069  [get_ports {rocc_mem_req_data_i[5]}]
set_input_transition -max 0.069  [get_ports {rocc_mem_req_data_i[4]}]
set_input_transition -min 0.069  [get_ports {rocc_mem_req_data_i[4]}]
set_input_transition -max 0.069  [get_ports {rocc_mem_req_data_i[3]}]
set_input_transition -min 0.069  [get_ports {rocc_mem_req_data_i[3]}]
set_input_transition -max 0.069  [get_ports {rocc_mem_req_data_i[2]}]
set_input_transition -min 0.069  [get_ports {rocc_mem_req_data_i[2]}]
set_input_transition -max 0.069  [get_ports {rocc_mem_req_data_i[1]}]
set_input_transition -min 0.069  [get_ports {rocc_mem_req_data_i[1]}]
set_input_transition -max 0.069  [get_ports {rocc_mem_req_data_i[0]}]
set_input_transition -min 0.069  [get_ports {rocc_mem_req_data_i[0]}]
set_input_transition -max 0.069  [get_ports rocc_ctrl_i_busy_]
set_input_transition -min 0.069  [get_ports rocc_ctrl_i_busy_]
set_input_transition -max 0.069  [get_ports rocc_ctrl_i_interrupt_]
set_input_transition -min 0.069  [get_ports rocc_ctrl_i_interrupt_]
set_input_transition -max 0.069  [get_ports fsb_node_v_i]
set_input_transition -min 0.069  [get_ports fsb_node_v_i]
set_input_transition -max 0.069  [get_ports {fsb_node_data_i[7]}]
set_input_transition -min 0.069  [get_ports {fsb_node_data_i[7]}]
set_input_transition -max 0.069  [get_ports {fsb_node_data_i[6]}]
set_input_transition -min 0.069  [get_ports {fsb_node_data_i[6]}]
set_input_transition -max 0.069  [get_ports {fsb_node_data_i[5]}]
set_input_transition -min 0.069  [get_ports {fsb_node_data_i[5]}]
set_input_transition -max 0.069  [get_ports {fsb_node_data_i[4]}]
set_input_transition -min 0.069  [get_ports {fsb_node_data_i[4]}]
set_input_transition -max 0.069  [get_ports {fsb_node_data_i[3]}]
set_input_transition -min 0.069  [get_ports {fsb_node_data_i[3]}]
set_input_transition -max 0.069  [get_ports {fsb_node_data_i[2]}]
set_input_transition -min 0.069  [get_ports {fsb_node_data_i[2]}]
set_input_transition -max 0.069  [get_ports {fsb_node_data_i[1]}]
set_input_transition -min 0.069  [get_ports {fsb_node_data_i[1]}]
set_input_transition -max 0.069  [get_ports {fsb_node_data_i[0]}]
set_input_transition -min 0.069  [get_ports {fsb_node_data_i[0]}]
set_input_transition -max 0.069  [get_ports fsb_node_yumi_i]
set_input_transition -min 0.069  [get_ports fsb_node_yumi_i]
