// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2025-2025, The OpenROAD Authors

#include "cgv/MakeCGV.h"

#include <tcl.h>

#include "utl/decode.h"

// Generated by swig from the example.i
extern "C" {
extern int Cgv_Init(Tcl_Interp* interp);
}

namespace cgv {

// example.tcl encoded as strings.
extern const char* cgv_tcl_inits[];

void initCGV(Tcl_Interp* tcl_interp)
{
  // Define swig TCL commands.
  Cgv_Init(tcl_interp);
  // Eval encoded TCL sources.
  utl::evalTclInit(tcl_interp, cgv_tcl_inits);
}

}  // namespace exa
