# CMake generated Testfile for 
# Source directory: /home/memzfs_projects/MLBuf_extension/OR_latest/src/par/test
# Build directory: /home/memzfs_projects/MLBuf_extension/OR_latest/build/src/par/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(par.partition_gcd.tcl "/usr/bin/bash" "/home/memzfs_projects/MLBuf_extension/OR_latest/test/regression_test.sh")
set_tests_properties(par.partition_gcd.tcl PROPERTIES  ENVIRONMENT "OPENROAD_EXE=/home/memzfs_projects/MLBuf_extension/OR_latest/build/bin/openroad;TEST_NAME=partition_gcd;TEST_EXT=tcl;TEST_TYPE=tcl;TEST_CHECK_LOG=True;TEST_CHECK_PASSFAIL=False" LABELS "IntegrationTest tcl par log_compare" WORKING_DIRECTORY "/home/memzfs_projects/MLBuf_extension/OR_latest/src/par/test" _BACKTRACE_TRIPLES "/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;19;add_test;/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;86;or_integration_test_single;/home/memzfs_projects/MLBuf_extension/OR_latest/src/par/test/CMakeLists.txt;1;or_integration_tests;/home/memzfs_projects/MLBuf_extension/OR_latest/src/par/test/CMakeLists.txt;0;")
add_test(par.partition_gcd.py "/usr/bin/bash" "/home/memzfs_projects/MLBuf_extension/OR_latest/test/regression_test.sh")
set_tests_properties(par.partition_gcd.py PROPERTIES  ENVIRONMENT "OPENROAD_EXE=/home/memzfs_projects/MLBuf_extension/OR_latest/build/bin/openroad;TEST_NAME=partition_gcd;TEST_EXT=py;TEST_TYPE=python;TEST_CHECK_LOG=True;TEST_CHECK_PASSFAIL=False" LABELS "IntegrationTest python par log_compare" WORKING_DIRECTORY "/home/memzfs_projects/MLBuf_extension/OR_latest/src/par/test" _BACKTRACE_TRIPLES "/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;19;add_test;/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;88;or_integration_test_single;/home/memzfs_projects/MLBuf_extension/OR_latest/src/par/test/CMakeLists.txt;1;or_integration_tests;/home/memzfs_projects/MLBuf_extension/OR_latest/src/par/test/CMakeLists.txt;0;")
add_test(par.read_part.tcl "/usr/bin/bash" "/home/memzfs_projects/MLBuf_extension/OR_latest/test/regression_test.sh")
set_tests_properties(par.read_part.tcl PROPERTIES  ENVIRONMENT "OPENROAD_EXE=/home/memzfs_projects/MLBuf_extension/OR_latest/build/bin/openroad;TEST_NAME=read_part;TEST_EXT=tcl;TEST_TYPE=tcl;TEST_CHECK_LOG=True;TEST_CHECK_PASSFAIL=False" LABELS "IntegrationTest tcl par log_compare" WORKING_DIRECTORY "/home/memzfs_projects/MLBuf_extension/OR_latest/src/par/test" _BACKTRACE_TRIPLES "/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;19;add_test;/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;86;or_integration_test_single;/home/memzfs_projects/MLBuf_extension/OR_latest/src/par/test/CMakeLists.txt;1;or_integration_tests;/home/memzfs_projects/MLBuf_extension/OR_latest/src/par/test/CMakeLists.txt;0;")
add_test(par.write_artnet.tcl "/usr/bin/bash" "/home/memzfs_projects/MLBuf_extension/OR_latest/test/regression_test.sh")
set_tests_properties(par.write_artnet.tcl PROPERTIES  ENVIRONMENT "OPENROAD_EXE=/home/memzfs_projects/MLBuf_extension/OR_latest/build/bin/openroad;TEST_NAME=write_artnet;TEST_EXT=tcl;TEST_TYPE=tcl;TEST_CHECK_LOG=True;TEST_CHECK_PASSFAIL=False" LABELS "IntegrationTest tcl par log_compare" WORKING_DIRECTORY "/home/memzfs_projects/MLBuf_extension/OR_latest/src/par/test" _BACKTRACE_TRIPLES "/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;19;add_test;/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;86;or_integration_test_single;/home/memzfs_projects/MLBuf_extension/OR_latest/src/par/test/CMakeLists.txt;1;or_integration_tests;/home/memzfs_projects/MLBuf_extension/OR_latest/src/par/test/CMakeLists.txt;0;")
