/* Generated by Yosys 0.9+1706 (git sha1 ff4ca9dd, clang 11.0.3 -fPIC -Os) */

module gcd(clk, req_msg, req_rdy, req_val, reset, resp_msg, resp_rdy, resp_val);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  input clk;
  wire \ctrl.state.out[1] ;
  wire \ctrl.state.out[2] ;
  wire \dpath.a_lt_b$in0[0] ;
  wire \dpath.a_lt_b$in0[10] ;
  wire \dpath.a_lt_b$in0[11] ;
  wire \dpath.a_lt_b$in0[12] ;
  wire \dpath.a_lt_b$in0[13] ;
  wire \dpath.a_lt_b$in0[14] ;
  wire \dpath.a_lt_b$in0[15] ;
  wire \dpath.a_lt_b$in0[1] ;
  wire \dpath.a_lt_b$in0[2] ;
  wire \dpath.a_lt_b$in0[3] ;
  wire \dpath.a_lt_b$in0[4] ;
  wire \dpath.a_lt_b$in0[5] ;
  wire \dpath.a_lt_b$in0[6] ;
  wire \dpath.a_lt_b$in0[7] ;
  wire \dpath.a_lt_b$in0[8] ;
  wire \dpath.a_lt_b$in0[9] ;
  wire \dpath.a_lt_b$in1[0] ;
  wire \dpath.a_lt_b$in1[10] ;
  wire \dpath.a_lt_b$in1[11] ;
  wire \dpath.a_lt_b$in1[12] ;
  wire \dpath.a_lt_b$in1[13] ;
  wire \dpath.a_lt_b$in1[14] ;
  wire \dpath.a_lt_b$in1[15] ;
  wire \dpath.a_lt_b$in1[1] ;
  wire \dpath.a_lt_b$in1[2] ;
  wire \dpath.a_lt_b$in1[3] ;
  wire \dpath.a_lt_b$in1[4] ;
  wire \dpath.a_lt_b$in1[5] ;
  wire \dpath.a_lt_b$in1[6] ;
  wire \dpath.a_lt_b$in1[7] ;
  wire \dpath.a_lt_b$in1[8] ;
  wire \dpath.a_lt_b$in1[9] ;
  input [31:0] req_msg;
  output req_rdy;
  input req_val;
  input reset;
  output [15:0] resp_msg;
  input resp_rdy;
  output resp_val;
  sky130_fd_sc_hs__inv_1 _177_ (
    .A(req_rdy),
    .Y(_035_)
  );
  sky130_fd_sc_hs__nand2b_1 _178_ (
    .A_N(\dpath.a_lt_b$in0[15] ),
    .B(\dpath.a_lt_b$in1[15] ),
    .Y(_036_)
  );
  sky130_fd_sc_hs__xnor2_1 _179_ (
    .A(\dpath.a_lt_b$in1[14] ),
    .B(\dpath.a_lt_b$in0[14] ),
    .Y(_037_)
  );
  sky130_fd_sc_hs__inv_2 _180_ (
    .A(_037_),
    .Y(_038_)
  );
  sky130_fd_sc_hs__nor2b_1 _181_ (
    .A(\dpath.a_lt_b$in0[13] ),
    .B_N(\dpath.a_lt_b$in1[13] ),
    .Y(_039_)
  );
  sky130_fd_sc_hs__nor2b_1 _182_ (
    .A(\dpath.a_lt_b$in0[12] ),
    .B_N(\dpath.a_lt_b$in1[12] ),
    .Y(_040_)
  );
  sky130_fd_sc_hs__nor2b_1 _183_ (
    .A(\dpath.a_lt_b$in0[11] ),
    .B_N(\dpath.a_lt_b$in1[11] ),
    .Y(_041_)
  );
  sky130_fd_sc_hs__xnor2_1 _184_ (
    .A(\dpath.a_lt_b$in1[10] ),
    .B(\dpath.a_lt_b$in0[10] ),
    .Y(_042_)
  );
  sky130_fd_sc_hs__clkinv_1 _185_ (
    .A(_042_),
    .Y(_043_)
  );
  sky130_fd_sc_hs__nor2b_1 _186_ (
    .A(\dpath.a_lt_b$in0[9] ),
    .B_N(\dpath.a_lt_b$in1[9] ),
    .Y(_044_)
  );
  sky130_fd_sc_hs__xnor2_1 _187_ (
    .A(\dpath.a_lt_b$in1[8] ),
    .B(\dpath.a_lt_b$in0[8] ),
    .Y(_045_)
  );
  sky130_fd_sc_hs__nand2b_1 _188_ (
    .A_N(\dpath.a_lt_b$in0[7] ),
    .B(\dpath.a_lt_b$in1[7] ),
    .Y(_046_)
  );
  sky130_fd_sc_hs__xnor2_1 _189_ (
    .A(\dpath.a_lt_b$in1[6] ),
    .B(\dpath.a_lt_b$in0[6] ),
    .Y(_047_)
  );
  sky130_fd_sc_hs__nand2b_1 _190_ (
    .A_N(\dpath.a_lt_b$in0[5] ),
    .B(\dpath.a_lt_b$in1[5] ),
    .Y(_048_)
  );
  sky130_fd_sc_hs__xor2_1 _191_ (
    .A(\dpath.a_lt_b$in1[4] ),
    .B(\dpath.a_lt_b$in0[4] ),
    .X(_049_)
  );
  sky130_fd_sc_hs__inv_1 _192_ (
    .A(\dpath.a_lt_b$in0[3] ),
    .Y(_050_)
  );
  sky130_fd_sc_hs__inv_1 _193_ (
    .A(\dpath.a_lt_b$in0[2] ),
    .Y(_051_)
  );
  sky130_fd_sc_hs__inv_1 _194_ (
    .A(\dpath.a_lt_b$in0[1] ),
    .Y(_052_)
  );
  sky130_fd_sc_hs__and2b_2 _195_ (
    .A_N(\dpath.a_lt_b$in0[0] ),
    .B(\dpath.a_lt_b$in1[0] ),
    .X(_053_)
  );
  sky130_fd_sc_hs__maj3_1 _196_ (
    .A(\dpath.a_lt_b$in1[1] ),
    .B(_052_),
    .C(_053_),
    .X(_054_)
  );
  sky130_fd_sc_hs__maj3_1 _197_ (
    .A(\dpath.a_lt_b$in1[2] ),
    .B(_051_),
    .C(_054_),
    .X(_055_)
  );
  sky130_fd_sc_hs__maj3_1 _198_ (
    .A(\dpath.a_lt_b$in1[3] ),
    .B(_050_),
    .C(_055_),
    .X(_056_)
  );
  sky130_fd_sc_hs__nand2b_1 _199_ (
    .A_N(\dpath.a_lt_b$in1[5] ),
    .B(\dpath.a_lt_b$in0[5] ),
    .Y(_057_)
  );
  sky130_fd_sc_hs__nand2b_1 _200_ (
    .A_N(\dpath.a_lt_b$in1[4] ),
    .B(\dpath.a_lt_b$in0[4] ),
    .Y(_058_)
  );
  sky130_fd_sc_hs__o211ai_2 _201_ (
    .A1(_049_),
    .A2(_056_),
    .B1(_057_),
    .C1(_058_),
    .Y(_059_)
  );
  sky130_fd_sc_hs__nor2b_1 _202_ (
    .A(\dpath.a_lt_b$in1[6] ),
    .B_N(\dpath.a_lt_b$in0[6] ),
    .Y(_060_)
  );
  sky130_fd_sc_hs__nor2b_1 _203_ (
    .A(\dpath.a_lt_b$in1[7] ),
    .B_N(\dpath.a_lt_b$in0[7] ),
    .Y(_061_)
  );
  sky130_fd_sc_hs__a311o_1 _204_ (
    .A1(_047_),
    .A2(_048_),
    .A3(_059_),
    .B1(_060_),
    .C1(_061_),
    .X(_062_)
  );
  sky130_fd_sc_hs__nor2b_1 _205_ (
    .A(\dpath.a_lt_b$in1[8] ),
    .B_N(\dpath.a_lt_b$in0[8] ),
    .Y(_063_)
  );
  sky130_fd_sc_hs__nor2b_1 _206_ (
    .A(\dpath.a_lt_b$in1[9] ),
    .B_N(\dpath.a_lt_b$in0[9] ),
    .Y(_064_)
  );
  sky130_fd_sc_hs__a311oi_2 _207_ (
    .A1(_045_),
    .A2(_046_),
    .A3(_062_),
    .B1(_063_),
    .C1(_064_),
    .Y(_065_)
  );
  sky130_fd_sc_hs__nand2b_1 _208_ (
    .A_N(\dpath.a_lt_b$in1[10] ),
    .B(\dpath.a_lt_b$in0[10] ),
    .Y(_066_)
  );
  sky130_fd_sc_hs__nand2b_1 _209_ (
    .A_N(\dpath.a_lt_b$in1[11] ),
    .B(\dpath.a_lt_b$in0[11] ),
    .Y(_067_)
  );
  sky130_fd_sc_hs__o311a_1 _210_ (
    .A1(_043_),
    .A2(_044_),
    .A3(_065_),
    .B1(_066_),
    .C1(_067_),
    .X(_068_)
  );
  sky130_fd_sc_hs__nand2b_1 _211_ (
    .A_N(\dpath.a_lt_b$in1[12] ),
    .B(\dpath.a_lt_b$in0[12] ),
    .Y(_069_)
  );
  sky130_fd_sc_hs__nand2b_1 _212_ (
    .A_N(\dpath.a_lt_b$in1[13] ),
    .B(\dpath.a_lt_b$in0[13] ),
    .Y(_070_)
  );
  sky130_fd_sc_hs__o311a_2 _213_ (
    .A1(_040_),
    .A2(_041_),
    .A3(_068_),
    .B1(_069_),
    .C1(_070_),
    .X(_071_)
  );
  sky130_fd_sc_hs__nand2b_1 _214_ (
    .A_N(\dpath.a_lt_b$in1[14] ),
    .B(\dpath.a_lt_b$in0[14] ),
    .Y(_072_)
  );
  sky130_fd_sc_hs__nand2b_1 _215_ (
    .A_N(\dpath.a_lt_b$in1[15] ),
    .B(\dpath.a_lt_b$in0[15] ),
    .Y(_073_)
  );
  sky130_fd_sc_hs__o311ai_4 _216_ (
    .A1(_038_),
    .A2(_039_),
    .A3(_071_),
    .B1(_072_),
    .C1(_073_),
    .Y(_074_)
  );
  sky130_fd_sc_hs__and4_4 _217_ (
    .A(_035_),
    .B(\ctrl.state.out[2] ),
    .C(_036_),
    .D(_074_),
    .X(_075_)
  );
  sky130_fd_sc_hs__buf_8 _218_ (
    .A(_075_),
    .X(_076_)
  );
  sky130_fd_sc_hs__xor2_1 _219_ (
    .A(\dpath.a_lt_b$in0[0] ),
    .B(\dpath.a_lt_b$in1[0] ),
    .X(resp_msg[0])
  );
  sky130_fd_sc_hs__nand2_1 _220_ (
    .A(_076_),
    .B(resp_msg[0]),
    .Y(_077_)
  );
  sky130_fd_sc_hs__clkbuf_2 _221_ (
    .A(req_rdy),
    .X(_078_)
  );
  sky130_fd_sc_hs__clkbuf_2 _222_ (
    .A(_078_),
    .X(_079_)
  );
  sky130_fd_sc_hs__nand2_1 _223_ (
    .A(_035_),
    .B(\ctrl.state.out[2] ),
    .Y(_080_)
  );
  sky130_fd_sc_hs__a21oi_2 _224_ (
    .A1(_036_),
    .A2(_074_),
    .B1(_080_),
    .Y(_081_)
  );
  sky130_fd_sc_hs__buf_4 _225_ (
    .A(_081_),
    .X(_082_)
  );
  sky130_fd_sc_hs__nor2_1 _226_ (
    .A(_078_),
    .B(\ctrl.state.out[2] ),
    .Y(_083_)
  );
  sky130_fd_sc_hs__clkbuf_2 _227_ (
    .A(_083_),
    .X(_084_)
  );
  sky130_fd_sc_hs__a221oi_1 _228_ (
    .A1(req_msg[16]),
    .A2(_079_),
    .B1(\dpath.a_lt_b$in1[0] ),
    .B2(_082_),
    .C1(_084_),
    .Y(_085_)
  );
  sky130_fd_sc_hs__or2_1 _229_ (
    .A(_078_),
    .B(\ctrl.state.out[2] ),
    .X(_086_)
  );
  sky130_fd_sc_hs__clkbuf_2 _230_ (
    .A(_086_),
    .X(_087_)
  );
  sky130_fd_sc_hs__nor2_1 _231_ (
    .A(\dpath.a_lt_b$in0[0] ),
    .B(_087_),
    .Y(_088_)
  );
  sky130_fd_sc_hs__a21oi_1 _232_ (
    .A1(_077_),
    .A2(_085_),
    .B1(_088_),
    .Y(_003_)
  );
  sky130_fd_sc_hs__buf_4 _233_ (
    .A(_081_),
    .X(_089_)
  );
  sky130_fd_sc_hs__nand2_1 _234_ (
    .A(\dpath.a_lt_b$in1[1] ),
    .B(_089_),
    .Y(_090_)
  );
  sky130_fd_sc_hs__xnor2_1 _235_ (
    .A(\dpath.a_lt_b$in1[1] ),
    .B(\dpath.a_lt_b$in0[1] ),
    .Y(_091_)
  );
  sky130_fd_sc_hs__xnor2_1 _236_ (
    .A(_053_),
    .B(_091_),
    .Y(resp_msg[1])
  );
  sky130_fd_sc_hs__a221oi_1 _237_ (
    .A1(req_msg[17]),
    .A2(_079_),
    .B1(_076_),
    .B2(resp_msg[1]),
    .C1(_084_),
    .Y(_092_)
  );
  sky130_fd_sc_hs__a22oi_1 _238_ (
    .A1(_052_),
    .A2(_084_),
    .B1(_090_),
    .B2(_092_),
    .Y(_010_)
  );
  sky130_fd_sc_hs__a22oi_1 _239_ (
    .A1(req_msg[18]),
    .A2(_079_),
    .B1(_089_),
    .B2(\dpath.a_lt_b$in1[2] ),
    .Y(_093_)
  );
  sky130_fd_sc_hs__xnor2_1 _240_ (
    .A(\dpath.a_lt_b$in1[2] ),
    .B(\dpath.a_lt_b$in0[2] ),
    .Y(_094_)
  );
  sky130_fd_sc_hs__xnor2_1 _241_ (
    .A(_094_),
    .B(_054_),
    .Y(resp_msg[2])
  );
  sky130_fd_sc_hs__a21oi_1 _242_ (
    .A1(_076_),
    .A2(resp_msg[2]),
    .B1(_084_),
    .Y(_095_)
  );
  sky130_fd_sc_hs__a22oi_1 _243_ (
    .A1(_051_),
    .A2(_084_),
    .B1(_093_),
    .B2(_095_),
    .Y(_011_)
  );
  sky130_fd_sc_hs__a22oi_1 _244_ (
    .A1(req_msg[19]),
    .A2(_079_),
    .B1(_089_),
    .B2(\dpath.a_lt_b$in1[3] ),
    .Y(_096_)
  );
  sky130_fd_sc_hs__xnor2_1 _245_ (
    .A(\dpath.a_lt_b$in1[3] ),
    .B(\dpath.a_lt_b$in0[3] ),
    .Y(_097_)
  );
  sky130_fd_sc_hs__xnor2_1 _246_ (
    .A(_055_),
    .B(_097_),
    .Y(resp_msg[3])
  );
  sky130_fd_sc_hs__a21oi_1 _247_ (
    .A1(_076_),
    .A2(resp_msg[3]),
    .B1(_084_),
    .Y(_098_)
  );
  sky130_fd_sc_hs__a22oi_1 _248_ (
    .A1(_050_),
    .A2(_084_),
    .B1(_096_),
    .B2(_098_),
    .Y(_012_)
  );
  sky130_fd_sc_hs__clkbuf_2 _249_ (
    .A(_087_),
    .X(_099_)
  );
  sky130_fd_sc_hs__xor2_1 _250_ (
    .A(_049_),
    .B(_056_),
    .X(resp_msg[4])
  );
  sky130_fd_sc_hs__a222oi_1 _251_ (
    .A1(req_msg[20]),
    .A2(_080_),
    .B1(_075_),
    .B2(resp_msg[4]),
    .C1(_089_),
    .C2(\dpath.a_lt_b$in1[4] ),
    .Y(_100_)
  );
  sky130_fd_sc_hs__nor2_1 _252_ (
    .A(\dpath.a_lt_b$in0[4] ),
    .B(_099_),
    .Y(_101_)
  );
  sky130_fd_sc_hs__a21oi_1 _253_ (
    .A1(_099_),
    .A2(_100_),
    .B1(_101_),
    .Y(_013_)
  );
  sky130_fd_sc_hs__nand2_1 _254_ (
    .A(\dpath.a_lt_b$in1[5] ),
    .B(_089_),
    .Y(_102_)
  );
  sky130_fd_sc_hs__clkbuf_2 _255_ (
    .A(_078_),
    .X(_103_)
  );
  sky130_fd_sc_hs__o21a_1 _256_ (
    .A1(_049_),
    .A2(_056_),
    .B1(_058_),
    .X(_104_)
  );
  sky130_fd_sc_hs__and2_1 _257_ (
    .A(_057_),
    .B(_048_),
    .X(_105_)
  );
  sky130_fd_sc_hs__xnor2_1 _258_ (
    .A(_104_),
    .B(_105_),
    .Y(resp_msg[5])
  );
  sky130_fd_sc_hs__a221oi_1 _259_ (
    .A1(req_msg[21]),
    .A2(_103_),
    .B1(_076_),
    .B2(resp_msg[5]),
    .C1(_083_),
    .Y(_106_)
  );
  sky130_fd_sc_hs__nor2_1 _260_ (
    .A(\dpath.a_lt_b$in0[5] ),
    .B(_099_),
    .Y(_107_)
  );
  sky130_fd_sc_hs__a21oi_1 _261_ (
    .A1(_102_),
    .A2(_106_),
    .B1(_107_),
    .Y(_014_)
  );
  sky130_fd_sc_hs__and2_1 _262_ (
    .A(_048_),
    .B(_059_),
    .X(_108_)
  );
  sky130_fd_sc_hs__xor2_1 _263_ (
    .A(_047_),
    .B(_108_),
    .X(resp_msg[6])
  );
  sky130_fd_sc_hs__a222oi_1 _264_ (
    .A1(req_msg[22]),
    .A2(_080_),
    .B1(_075_),
    .B2(resp_msg[6]),
    .C1(_089_),
    .C2(\dpath.a_lt_b$in1[6] ),
    .Y(_109_)
  );
  sky130_fd_sc_hs__nor2_1 _265_ (
    .A(\dpath.a_lt_b$in0[6] ),
    .B(_087_),
    .Y(_110_)
  );
  sky130_fd_sc_hs__a21oi_1 _266_ (
    .A1(_099_),
    .A2(_109_),
    .B1(_110_),
    .Y(_015_)
  );
  sky130_fd_sc_hs__a21oi_1 _267_ (
    .A1(_047_),
    .A2(_108_),
    .B1(_060_),
    .Y(_111_)
  );
  sky130_fd_sc_hs__nor2b_1 _268_ (
    .A(_061_),
    .B_N(_046_),
    .Y(_112_)
  );
  sky130_fd_sc_hs__xnor2_1 _269_ (
    .A(_111_),
    .B(_112_),
    .Y(resp_msg[7])
  );
  sky130_fd_sc_hs__a222oi_1 _270_ (
    .A1(req_msg[23]),
    .A2(_080_),
    .B1(_075_),
    .B2(resp_msg[7]),
    .C1(_082_),
    .C2(\dpath.a_lt_b$in1[7] ),
    .Y(_113_)
  );
  sky130_fd_sc_hs__nor2_1 _271_ (
    .A(\dpath.a_lt_b$in0[7] ),
    .B(_099_),
    .Y(_114_)
  );
  sky130_fd_sc_hs__a21oi_1 _272_ (
    .A1(_099_),
    .A2(_113_),
    .B1(_114_),
    .Y(_016_)
  );
  sky130_fd_sc_hs__nand2_1 _273_ (
    .A(_046_),
    .B(_062_),
    .Y(_115_)
  );
  sky130_fd_sc_hs__xnor2_1 _274_ (
    .A(_045_),
    .B(_115_),
    .Y(resp_msg[8])
  );
  sky130_fd_sc_hs__a222oi_1 _275_ (
    .A1(req_msg[24]),
    .A2(_080_),
    .B1(_076_),
    .B2(resp_msg[8]),
    .C1(_089_),
    .C2(\dpath.a_lt_b$in1[8] ),
    .Y(_116_)
  );
  sky130_fd_sc_hs__nor2_1 _276_ (
    .A(\dpath.a_lt_b$in0[8] ),
    .B(_087_),
    .Y(_117_)
  );
  sky130_fd_sc_hs__a21oi_1 _277_ (
    .A1(_099_),
    .A2(_116_),
    .B1(_117_),
    .Y(_017_)
  );
  sky130_fd_sc_hs__a31oi_1 _278_ (
    .A1(_045_),
    .A2(_046_),
    .A3(_062_),
    .B1(_063_),
    .Y(_118_)
  );
  sky130_fd_sc_hs__nor2_1 _279_ (
    .A(_044_),
    .B(_064_),
    .Y(_119_)
  );
  sky130_fd_sc_hs__xnor2_1 _280_ (
    .A(_118_),
    .B(_119_),
    .Y(resp_msg[9])
  );
  sky130_fd_sc_hs__nand2_1 _281_ (
    .A(_076_),
    .B(resp_msg[9]),
    .Y(_120_)
  );
  sky130_fd_sc_hs__a221oi_1 _282_ (
    .A1(req_msg[25]),
    .A2(_103_),
    .B1(_082_),
    .B2(\dpath.a_lt_b$in1[9] ),
    .C1(_084_),
    .Y(_121_)
  );
  sky130_fd_sc_hs__nor2_1 _283_ (
    .A(\dpath.a_lt_b$in0[9] ),
    .B(_087_),
    .Y(_122_)
  );
  sky130_fd_sc_hs__a21oi_1 _284_ (
    .A1(_120_),
    .A2(_121_),
    .B1(_122_),
    .Y(_018_)
  );
  sky130_fd_sc_hs__nor2_1 _285_ (
    .A(_044_),
    .B(_065_),
    .Y(_123_)
  );
  sky130_fd_sc_hs__xnor2_1 _286_ (
    .A(_043_),
    .B(_123_),
    .Y(resp_msg[10])
  );
  sky130_fd_sc_hs__nand2_1 _287_ (
    .A(_076_),
    .B(resp_msg[10]),
    .Y(_124_)
  );
  sky130_fd_sc_hs__a221oi_1 _288_ (
    .A1(req_msg[26]),
    .A2(_103_),
    .B1(_082_),
    .B2(\dpath.a_lt_b$in1[10] ),
    .C1(_084_),
    .Y(_125_)
  );
  sky130_fd_sc_hs__nor2_1 _289_ (
    .A(\dpath.a_lt_b$in0[10] ),
    .B(_087_),
    .Y(_126_)
  );
  sky130_fd_sc_hs__a21oi_1 _290_ (
    .A1(_124_),
    .A2(_125_),
    .B1(_126_),
    .Y(_004_)
  );
  sky130_fd_sc_hs__o31ai_1 _291_ (
    .A1(_043_),
    .A2(_044_),
    .A3(_065_),
    .B1(_066_),
    .Y(_127_)
  );
  sky130_fd_sc_hs__nand2b_1 _292_ (
    .A_N(_041_),
    .B(_067_),
    .Y(_128_)
  );
  sky130_fd_sc_hs__xnor2_1 _293_ (
    .A(_127_),
    .B(_128_),
    .Y(resp_msg[11])
  );
  sky130_fd_sc_hs__a222oi_1 _294_ (
    .A1(req_msg[27]),
    .A2(_080_),
    .B1(_075_),
    .B2(resp_msg[11]),
    .C1(_089_),
    .C2(\dpath.a_lt_b$in1[11] ),
    .Y(_129_)
  );
  sky130_fd_sc_hs__nor2_1 _295_ (
    .A(\dpath.a_lt_b$in0[11] ),
    .B(_087_),
    .Y(_130_)
  );
  sky130_fd_sc_hs__a21oi_1 _296_ (
    .A1(_099_),
    .A2(_129_),
    .B1(_130_),
    .Y(_005_)
  );
  sky130_fd_sc_hs__xnor2_1 _297_ (
    .A(\dpath.a_lt_b$in1[12] ),
    .B(\dpath.a_lt_b$in0[12] ),
    .Y(_131_)
  );
  sky130_fd_sc_hs__or2_1 _298_ (
    .A(_041_),
    .B(_068_),
    .X(_132_)
  );
  sky130_fd_sc_hs__xnor2_1 _299_ (
    .A(_131_),
    .B(_132_),
    .Y(resp_msg[12])
  );
  sky130_fd_sc_hs__a222oi_1 _300_ (
    .A1(req_msg[28]),
    .A2(_080_),
    .B1(_075_),
    .B2(resp_msg[12]),
    .C1(_089_),
    .C2(\dpath.a_lt_b$in1[12] ),
    .Y(_133_)
  );
  sky130_fd_sc_hs__nor2_1 _301_ (
    .A(\dpath.a_lt_b$in0[12] ),
    .B(_087_),
    .Y(_134_)
  );
  sky130_fd_sc_hs__a21oi_1 _302_ (
    .A1(_099_),
    .A2(_133_),
    .B1(_134_),
    .Y(_006_)
  );
  sky130_fd_sc_hs__o21ai_1 _303_ (
    .A1(_040_),
    .A2(_132_),
    .B1(_069_),
    .Y(_135_)
  );
  sky130_fd_sc_hs__xor2_1 _304_ (
    .A(\dpath.a_lt_b$in1[13] ),
    .B(\dpath.a_lt_b$in0[13] ),
    .X(_136_)
  );
  sky130_fd_sc_hs__xnor2_1 _305_ (
    .A(_135_),
    .B(_136_),
    .Y(resp_msg[13])
  );
  sky130_fd_sc_hs__nand2_1 _306_ (
    .A(_076_),
    .B(resp_msg[13]),
    .Y(_137_)
  );
  sky130_fd_sc_hs__a221oi_1 _307_ (
    .A1(req_msg[29]),
    .A2(_103_),
    .B1(_082_),
    .B2(\dpath.a_lt_b$in1[13] ),
    .C1(_083_),
    .Y(_138_)
  );
  sky130_fd_sc_hs__nor2_1 _308_ (
    .A(\dpath.a_lt_b$in0[13] ),
    .B(_099_),
    .Y(_139_)
  );
  sky130_fd_sc_hs__a21oi_1 _309_ (
    .A1(_137_),
    .A2(_138_),
    .B1(_139_),
    .Y(_007_)
  );
  sky130_fd_sc_hs__or3_1 _310_ (
    .A(_038_),
    .B(_039_),
    .C(_071_),
    .X(_140_)
  );
  sky130_fd_sc_hs__o21ai_1 _311_ (
    .A1(_039_),
    .A2(_071_),
    .B1(_038_),
    .Y(_141_)
  );
  sky130_fd_sc_hs__and2_1 _312_ (
    .A(_140_),
    .B(_141_),
    .X(resp_msg[14])
  );
  sky130_fd_sc_hs__nand2_1 _313_ (
    .A(_076_),
    .B(resp_msg[14]),
    .Y(_142_)
  );
  sky130_fd_sc_hs__a221oi_1 _314_ (
    .A1(req_msg[30]),
    .A2(_103_),
    .B1(_082_),
    .B2(\dpath.a_lt_b$in1[14] ),
    .C1(_084_),
    .Y(_143_)
  );
  sky130_fd_sc_hs__nor2_1 _315_ (
    .A(\dpath.a_lt_b$in0[14] ),
    .B(_087_),
    .Y(_144_)
  );
  sky130_fd_sc_hs__a21oi_1 _316_ (
    .A1(_142_),
    .A2(_143_),
    .B1(_144_),
    .Y(_008_)
  );
  sky130_fd_sc_hs__and2_1 _317_ (
    .A(_072_),
    .B(_140_),
    .X(_145_)
  );
  sky130_fd_sc_hs__and2_1 _318_ (
    .A(_073_),
    .B(_036_),
    .X(_146_)
  );
  sky130_fd_sc_hs__xnor2_1 _319_ (
    .A(_145_),
    .B(_146_),
    .Y(resp_msg[15])
  );
  sky130_fd_sc_hs__and2_1 _320_ (
    .A(\dpath.a_lt_b$in1[15] ),
    .B(_081_),
    .X(_147_)
  );
  sky130_fd_sc_hs__nor4b_1 _321_ (
    .A(\dpath.a_lt_b$in1[15] ),
    .B(_145_),
    .C(_080_),
    .D_N(\dpath.a_lt_b$in0[15] ),
    .Y(_148_)
  );
  sky130_fd_sc_hs__o21a_1 _322_ (
    .A1(req_msg[31]),
    .A2(_035_),
    .B1(_080_),
    .X(_149_)
  );
  sky130_fd_sc_hs__o32a_1 _323_ (
    .A1(_147_),
    .A2(_148_),
    .A3(_149_),
    .B1(_087_),
    .B2(\dpath.a_lt_b$in0[15] ),
    .X(_009_)
  );
  sky130_fd_sc_hs__a31o_1 _324_ (
    .A1(_035_),
    .A2(_036_),
    .A3(_074_),
    .B1(_083_),
    .X(_150_)
  );
  sky130_fd_sc_hs__a222o_1 _325_ (
    .A1(_078_),
    .A2(req_msg[0]),
    .B1(\dpath.a_lt_b$in1[0] ),
    .B2(_150_),
    .C1(_089_),
    .C2(\dpath.a_lt_b$in0[0] ),
    .X(_019_)
  );
  sky130_fd_sc_hs__clkbuf_4 _326_ (
    .A(_150_),
    .X(_151_)
  );
  sky130_fd_sc_hs__a222o_1 _327_ (
    .A1(_078_),
    .A2(req_msg[1]),
    .B1(_082_),
    .B2(\dpath.a_lt_b$in0[1] ),
    .C1(\dpath.a_lt_b$in1[1] ),
    .C2(_151_),
    .X(_026_)
  );
  sky130_fd_sc_hs__a222o_1 _328_ (
    .A1(_103_),
    .A2(req_msg[2]),
    .B1(_082_),
    .B2(\dpath.a_lt_b$in0[2] ),
    .C1(\dpath.a_lt_b$in1[2] ),
    .C2(_151_),
    .X(_027_)
  );
  sky130_fd_sc_hs__a222o_1 _329_ (
    .A1(_103_),
    .A2(req_msg[3]),
    .B1(_082_),
    .B2(\dpath.a_lt_b$in0[3] ),
    .C1(\dpath.a_lt_b$in1[3] ),
    .C2(_151_),
    .X(_028_)
  );
  sky130_fd_sc_hs__clkbuf_2 _330_ (
    .A(_150_),
    .X(_152_)
  );
  sky130_fd_sc_hs__mux2i_1 _331_ (
    .A0(\dpath.a_lt_b$in0[4] ),
    .A1(req_msg[4]),
    .S(_079_),
    .Y(_153_)
  );
  sky130_fd_sc_hs__nand2_1 _332_ (
    .A(\dpath.a_lt_b$in1[4] ),
    .B(_152_),
    .Y(_154_)
  );
  sky130_fd_sc_hs__o21ai_1 _333_ (
    .A1(_152_),
    .A2(_153_),
    .B1(_154_),
    .Y(_029_)
  );
  sky130_fd_sc_hs__mux2i_1 _334_ (
    .A0(\dpath.a_lt_b$in0[5] ),
    .A1(req_msg[5]),
    .S(_079_),
    .Y(_155_)
  );
  sky130_fd_sc_hs__nand2_1 _335_ (
    .A(\dpath.a_lt_b$in1[5] ),
    .B(_152_),
    .Y(_156_)
  );
  sky130_fd_sc_hs__o21ai_1 _336_ (
    .A1(_152_),
    .A2(_155_),
    .B1(_156_),
    .Y(_030_)
  );
  sky130_fd_sc_hs__mux2_1 _337_ (
    .A0(\dpath.a_lt_b$in0[6] ),
    .A1(req_msg[6]),
    .S(_078_),
    .X(_157_)
  );
  sky130_fd_sc_hs__mux2_1 _338_ (
    .A0(_157_),
    .A1(\dpath.a_lt_b$in1[6] ),
    .S(_151_),
    .X(_031_)
  );
  sky130_fd_sc_hs__mux2_1 _339_ (
    .A0(\dpath.a_lt_b$in0[7] ),
    .A1(req_msg[7]),
    .S(_078_),
    .X(_158_)
  );
  sky130_fd_sc_hs__mux2_1 _340_ (
    .A0(_158_),
    .A1(\dpath.a_lt_b$in1[7] ),
    .S(_151_),
    .X(_032_)
  );
  sky130_fd_sc_hs__nor2_1 _341_ (
    .A(\dpath.a_lt_b$in0[8] ),
    .B(_079_),
    .Y(_159_)
  );
  sky130_fd_sc_hs__nor2_1 _342_ (
    .A(_035_),
    .B(req_msg[8]),
    .Y(_160_)
  );
  sky130_fd_sc_hs__nand2_1 _343_ (
    .A(\dpath.a_lt_b$in1[8] ),
    .B(_152_),
    .Y(_161_)
  );
  sky130_fd_sc_hs__o31ai_1 _344_ (
    .A1(_159_),
    .A2(_152_),
    .A3(_160_),
    .B1(_161_),
    .Y(_033_)
  );
  sky130_fd_sc_hs__a222o_2 _345_ (
    .A1(_103_),
    .A2(req_msg[9]),
    .B1(_081_),
    .B2(\dpath.a_lt_b$in0[9] ),
    .C1(\dpath.a_lt_b$in1[9] ),
    .C2(_151_),
    .X(_034_)
  );
  sky130_fd_sc_hs__a222o_1 _346_ (
    .A1(_078_),
    .A2(req_msg[10]),
    .B1(_081_),
    .B2(\dpath.a_lt_b$in0[10] ),
    .C1(\dpath.a_lt_b$in1[10] ),
    .C2(_151_),
    .X(_020_)
  );
  sky130_fd_sc_hs__mux2i_1 _347_ (
    .A0(\dpath.a_lt_b$in0[11] ),
    .A1(req_msg[11]),
    .S(_079_),
    .Y(_162_)
  );
  sky130_fd_sc_hs__nand2_1 _348_ (
    .A(\dpath.a_lt_b$in1[11] ),
    .B(_152_),
    .Y(_163_)
  );
  sky130_fd_sc_hs__o21ai_1 _349_ (
    .A1(_152_),
    .A2(_162_),
    .B1(_163_),
    .Y(_021_)
  );
  sky130_fd_sc_hs__mux2i_1 _350_ (
    .A0(\dpath.a_lt_b$in0[12] ),
    .A1(req_msg[12]),
    .S(_079_),
    .Y(_164_)
  );
  sky130_fd_sc_hs__nand2_1 _351_ (
    .A(\dpath.a_lt_b$in1[12] ),
    .B(_152_),
    .Y(_165_)
  );
  sky130_fd_sc_hs__o21ai_1 _352_ (
    .A1(_152_),
    .A2(_164_),
    .B1(_165_),
    .Y(_022_)
  );
  sky130_fd_sc_hs__a222o_1 _353_ (
    .A1(_103_),
    .A2(req_msg[13]),
    .B1(_082_),
    .B2(\dpath.a_lt_b$in0[13] ),
    .C1(\dpath.a_lt_b$in1[13] ),
    .C2(_151_),
    .X(_023_)
  );
  sky130_fd_sc_hs__a222o_1 _354_ (
    .A1(_103_),
    .A2(req_msg[14]),
    .B1(_081_),
    .B2(\dpath.a_lt_b$in0[14] ),
    .C1(\dpath.a_lt_b$in1[14] ),
    .C2(_151_),
    .X(_024_)
  );
  sky130_fd_sc_hs__mux2_1 _355_ (
    .A0(\dpath.a_lt_b$in0[15] ),
    .A1(req_msg[15]),
    .S(_078_),
    .X(_166_)
  );
  sky130_fd_sc_hs__mux2_1 _356_ (
    .A0(_166_),
    .A1(\dpath.a_lt_b$in1[15] ),
    .S(_151_),
    .X(_025_)
  );
  sky130_fd_sc_hs__and2_1 _357_ (
    .A(\ctrl.state.out[1] ),
    .B(_083_),
    .X(resp_val)
  );
  sky130_fd_sc_hs__inv_1 _358_ (
    .A(reset),
    .Y(_167_)
  );
  sky130_fd_sc_hs__or4_1 _359_ (
    .A(\dpath.a_lt_b$in1[13] ),
    .B(\dpath.a_lt_b$in1[14] ),
    .C(\dpath.a_lt_b$in1[15] ),
    .D(\dpath.a_lt_b$in1[0] ),
    .X(_168_)
  );
  sky130_fd_sc_hs__nor2_1 _360_ (
    .A(\dpath.a_lt_b$in1[3] ),
    .B(\dpath.a_lt_b$in1[5] ),
    .Y(_169_)
  );
  sky130_fd_sc_hs__nor4_1 _361_ (
    .A(\dpath.a_lt_b$in1[2] ),
    .B(\dpath.a_lt_b$in1[6] ),
    .C(\dpath.a_lt_b$in1[7] ),
    .D(\dpath.a_lt_b$in1[8] ),
    .Y(_170_)
  );
  sky130_fd_sc_hs__nor4_1 _362_ (
    .A(\dpath.a_lt_b$in1[1] ),
    .B(\dpath.a_lt_b$in1[4] ),
    .C(\dpath.a_lt_b$in1[10] ),
    .D(\dpath.a_lt_b$in1[11] ),
    .Y(_171_)
  );
  sky130_fd_sc_hs__nand3_1 _363_ (
    .A(_169_),
    .B(_170_),
    .C(_171_),
    .Y(_172_)
  );
  sky130_fd_sc_hs__nor4_1 _364_ (
    .A(\dpath.a_lt_b$in1[9] ),
    .B(\dpath.a_lt_b$in1[12] ),
    .C(_168_),
    .D(_172_),
    .Y(_173_)
  );
  sky130_fd_sc_hs__a21oi_1 _365_ (
    .A1(resp_rdy),
    .A2(resp_val),
    .B1(reset),
    .Y(_174_)
  );
  sky130_fd_sc_hs__a32o_1 _366_ (
    .A1(_167_),
    .A2(\ctrl.state.out[2] ),
    .A3(_173_),
    .B1(_174_),
    .B2(\ctrl.state.out[1] ),
    .X(_001_)
  );
  sky130_fd_sc_hs__nand2_1 _367_ (
    .A(_167_),
    .B(\ctrl.state.out[2] ),
    .Y(_175_)
  );
  sky130_fd_sc_hs__nand2_1 _368_ (
    .A(_079_),
    .B(req_val),
    .Y(_176_)
  );
  sky130_fd_sc_hs__o22ai_1 _369_ (
    .A1(_173_),
    .A2(_175_),
    .B1(_176_),
    .B2(reset),
    .Y(_002_)
  );
  sky130_fd_sc_hs__o21ai_1 _370_ (
    .A1(_035_),
    .A2(req_val),
    .B1(_174_),
    .Y(_000_)
  );
  sky130_fd_sc_hs__dfxtp_1 _371_ (
    .CLK(clk),
    .D(_000_),
    .Q(req_rdy)
  );
  sky130_fd_sc_hs__dfxtp_1 _372_ (
    .CLK(clk),
    .D(_001_),
    .Q(\ctrl.state.out[1] )
  );
  sky130_fd_sc_hs__dfxtp_1 _373_ (
    .CLK(clk),
    .D(_002_),
    .Q(\ctrl.state.out[2] )
  );
  sky130_fd_sc_hs__dfxtp_1 _374_ (
    .CLK(clk),
    .D(_003_),
    .Q(\dpath.a_lt_b$in0[0] )
  );
  sky130_fd_sc_hs__dfxtp_1 _375_ (
    .CLK(clk),
    .D(_010_),
    .Q(\dpath.a_lt_b$in0[1] )
  );
  sky130_fd_sc_hs__dfxtp_1 _376_ (
    .CLK(clk),
    .D(_011_),
    .Q(\dpath.a_lt_b$in0[2] )
  );
  sky130_fd_sc_hs__dfxtp_1 _377_ (
    .CLK(clk),
    .D(_012_),
    .Q(\dpath.a_lt_b$in0[3] )
  );
  sky130_fd_sc_hs__dfxtp_1 _378_ (
    .CLK(clk),
    .D(_013_),
    .Q(\dpath.a_lt_b$in0[4] )
  );
  sky130_fd_sc_hs__dfxtp_1 _379_ (
    .CLK(clk),
    .D(_014_),
    .Q(\dpath.a_lt_b$in0[5] )
  );
  sky130_fd_sc_hs__dfxtp_1 _380_ (
    .CLK(clk),
    .D(_015_),
    .Q(\dpath.a_lt_b$in0[6] )
  );
  sky130_fd_sc_hs__dfxtp_1 _381_ (
    .CLK(clk),
    .D(_016_),
    .Q(\dpath.a_lt_b$in0[7] )
  );
  sky130_fd_sc_hs__dfxtp_1 _382_ (
    .CLK(clk),
    .D(_017_),
    .Q(\dpath.a_lt_b$in0[8] )
  );
  sky130_fd_sc_hs__dfxtp_1 _383_ (
    .CLK(clk),
    .D(_018_),
    .Q(\dpath.a_lt_b$in0[9] )
  );
  sky130_fd_sc_hs__dfxtp_1 _384_ (
    .CLK(clk),
    .D(_004_),
    .Q(\dpath.a_lt_b$in0[10] )
  );
  sky130_fd_sc_hs__dfxtp_1 _385_ (
    .CLK(clk),
    .D(_005_),
    .Q(\dpath.a_lt_b$in0[11] )
  );
  sky130_fd_sc_hs__dfxtp_1 _386_ (
    .CLK(clk),
    .D(_006_),
    .Q(\dpath.a_lt_b$in0[12] )
  );
  sky130_fd_sc_hs__dfxtp_1 _387_ (
    .CLK(clk),
    .D(_007_),
    .Q(\dpath.a_lt_b$in0[13] )
  );
  sky130_fd_sc_hs__dfxtp_1 _388_ (
    .CLK(clk),
    .D(_008_),
    .Q(\dpath.a_lt_b$in0[14] )
  );
  sky130_fd_sc_hs__dfxtp_1 _389_ (
    .CLK(clk),
    .D(_009_),
    .Q(\dpath.a_lt_b$in0[15] )
  );
  sky130_fd_sc_hs__dfxtp_1 _390_ (
    .CLK(clk),
    .D(_019_),
    .Q(\dpath.a_lt_b$in1[0] )
  );
  sky130_fd_sc_hs__dfxtp_1 _391_ (
    .CLK(clk),
    .D(_026_),
    .Q(\dpath.a_lt_b$in1[1] )
  );
  sky130_fd_sc_hs__dfxtp_1 _392_ (
    .CLK(clk),
    .D(_027_),
    .Q(\dpath.a_lt_b$in1[2] )
  );
  sky130_fd_sc_hs__dfxtp_1 _393_ (
    .CLK(clk),
    .D(_028_),
    .Q(\dpath.a_lt_b$in1[3] )
  );
  sky130_fd_sc_hs__dfxtp_1 _394_ (
    .CLK(clk),
    .D(_029_),
    .Q(\dpath.a_lt_b$in1[4] )
  );
  sky130_fd_sc_hs__dfxtp_1 _395_ (
    .CLK(clk),
    .D(_030_),
    .Q(\dpath.a_lt_b$in1[5] )
  );
  sky130_fd_sc_hs__dfxtp_1 _396_ (
    .CLK(clk),
    .D(_031_),
    .Q(\dpath.a_lt_b$in1[6] )
  );
  sky130_fd_sc_hs__dfxtp_1 _397_ (
    .CLK(clk),
    .D(_032_),
    .Q(\dpath.a_lt_b$in1[7] )
  );
  sky130_fd_sc_hs__dfxtp_1 _398_ (
    .CLK(clk),
    .D(_033_),
    .Q(\dpath.a_lt_b$in1[8] )
  );
  sky130_fd_sc_hs__dfxtp_1 _399_ (
    .CLK(clk),
    .D(_034_),
    .Q(\dpath.a_lt_b$in1[9] )
  );
  sky130_fd_sc_hs__dfxtp_1 _400_ (
    .CLK(clk),
    .D(_020_),
    .Q(\dpath.a_lt_b$in1[10] )
  );
  sky130_fd_sc_hs__dfxtp_1 _401_ (
    .CLK(clk),
    .D(_021_),
    .Q(\dpath.a_lt_b$in1[11] )
  );
  sky130_fd_sc_hs__dfxtp_1 _402_ (
    .CLK(clk),
    .D(_022_),
    .Q(\dpath.a_lt_b$in1[12] )
  );
  sky130_fd_sc_hs__dfxtp_1 _403_ (
    .CLK(clk),
    .D(_023_),
    .Q(\dpath.a_lt_b$in1[13] )
  );
  sky130_fd_sc_hs__dfxtp_1 _404_ (
    .CLK(clk),
    .D(_024_),
    .Q(\dpath.a_lt_b$in1[14] )
  );
  sky130_fd_sc_hs__dfxtp_1 _405_ (
    .CLK(clk),
    .D(_025_),
    .Q(\dpath.a_lt_b$in1[15] )
  );
endmodule
