/* Generated by Yosys 0.9+3672 (git sha1 014c7e26, clang 12.0.0 -fPIC -Os) */

module gcd(clk, req_msg, req_rdy, req_val, reset, resp_msg, resp_rdy, resp_val);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  input clk;
  wire \ctrl.state.out[1] ;
  wire \ctrl.state.out[2] ;
  wire \dpath.a_lt_b$in0[0] ;
  wire \dpath.a_lt_b$in0[10] ;
  wire \dpath.a_lt_b$in0[11] ;
  wire \dpath.a_lt_b$in0[12] ;
  wire \dpath.a_lt_b$in0[13] ;
  wire \dpath.a_lt_b$in0[14] ;
  wire \dpath.a_lt_b$in0[15] ;
  wire \dpath.a_lt_b$in0[1] ;
  wire \dpath.a_lt_b$in0[2] ;
  wire \dpath.a_lt_b$in0[3] ;
  wire \dpath.a_lt_b$in0[4] ;
  wire \dpath.a_lt_b$in0[5] ;
  wire \dpath.a_lt_b$in0[6] ;
  wire \dpath.a_lt_b$in0[7] ;
  wire \dpath.a_lt_b$in0[8] ;
  wire \dpath.a_lt_b$in0[9] ;
  wire \dpath.a_lt_b$in1[0] ;
  wire \dpath.a_lt_b$in1[10] ;
  wire \dpath.a_lt_b$in1[11] ;
  wire \dpath.a_lt_b$in1[12] ;
  wire \dpath.a_lt_b$in1[13] ;
  wire \dpath.a_lt_b$in1[14] ;
  wire \dpath.a_lt_b$in1[15] ;
  wire \dpath.a_lt_b$in1[1] ;
  wire \dpath.a_lt_b$in1[2] ;
  wire \dpath.a_lt_b$in1[3] ;
  wire \dpath.a_lt_b$in1[4] ;
  wire \dpath.a_lt_b$in1[5] ;
  wire \dpath.a_lt_b$in1[6] ;
  wire \dpath.a_lt_b$in1[7] ;
  wire \dpath.a_lt_b$in1[8] ;
  wire \dpath.a_lt_b$in1[9] ;
  input [31:0] req_msg;
  output req_rdy;
  input req_val;
  input reset;
  output [15:0] resp_msg;
  input resp_rdy;
  output resp_val;
  sky130_fd_sc_hd__xor2_1 _182_ (
    .A(\dpath.a_lt_b$in0[0] ),
    .B(\dpath.a_lt_b$in1[0] ),
    .X(resp_msg[0])
  );
  sky130_fd_sc_hd__xnor2_1 _183_ (
    .A(\dpath.a_lt_b$in0[14] ),
    .B(\dpath.a_lt_b$in1[14] ),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nand2b_1 _184_ (
    .A_N(\dpath.a_lt_b$in0[13] ),
    .B(\dpath.a_lt_b$in1[13] ),
    .Y(_036_)
  );
  sky130_fd_sc_hd__xnor2_1 _185_ (
    .A(\dpath.a_lt_b$in0[12] ),
    .B(\dpath.a_lt_b$in1[12] ),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nand2b_1 _186_ (
    .A_N(\dpath.a_lt_b$in0[11] ),
    .B(\dpath.a_lt_b$in1[11] ),
    .Y(_038_)
  );
  sky130_fd_sc_hd__xnor2_1 _187_ (
    .A(\dpath.a_lt_b$in0[10] ),
    .B(\dpath.a_lt_b$in1[10] ),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nand2b_1 _188_ (
    .A_N(\dpath.a_lt_b$in0[9] ),
    .B(\dpath.a_lt_b$in1[9] ),
    .Y(_040_)
  );
  sky130_fd_sc_hd__xnor2_1 _189_ (
    .A(\dpath.a_lt_b$in0[8] ),
    .B(\dpath.a_lt_b$in1[8] ),
    .Y(_041_)
  );
  sky130_fd_sc_hd__inv_1 _190_ (
    .A(\dpath.a_lt_b$in0[7] ),
    .Y(_042_)
  );
  sky130_fd_sc_hd__nand2_1 _191_ (
    .A(_042_),
    .B(\dpath.a_lt_b$in1[7] ),
    .Y(_043_)
  );
  sky130_fd_sc_hd__xnor2_1 _192_ (
    .A(\dpath.a_lt_b$in0[6] ),
    .B(\dpath.a_lt_b$in1[6] ),
    .Y(_044_)
  );
  sky130_fd_sc_hd__inv_1 _193_ (
    .A(_044_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__inv_1 _194_ (
    .A(\dpath.a_lt_b$in0[5] ),
    .Y(_046_)
  );
  sky130_fd_sc_hd__inv_1 _195_ (
    .A(\dpath.a_lt_b$in0[4] ),
    .Y(_047_)
  );
  sky130_fd_sc_hd__inv_1 _196_ (
    .A(\dpath.a_lt_b$in0[3] ),
    .Y(_048_)
  );
  sky130_fd_sc_hd__inv_1 _197_ (
    .A(\dpath.a_lt_b$in0[2] ),
    .Y(_049_)
  );
  sky130_fd_sc_hd__inv_1 _198_ (
    .A(\dpath.a_lt_b$in0[1] ),
    .Y(_050_)
  );
  sky130_fd_sc_hd__nor2b_4 _199_ (
    .A(\dpath.a_lt_b$in0[0] ),
    .B_N(\dpath.a_lt_b$in1[0] ),
    .Y(_051_)
  );
  sky130_fd_sc_hd__maj3_2 _200_ (
    .A(_050_),
    .B(\dpath.a_lt_b$in1[1] ),
    .C(_051_),
    .X(_052_)
  );
  sky130_fd_sc_hd__maj3_2 _201_ (
    .A(_049_),
    .B(\dpath.a_lt_b$in1[2] ),
    .C(_052_),
    .X(_053_)
  );
  sky130_fd_sc_hd__maj3_2 _202_ (
    .A(_048_),
    .B(\dpath.a_lt_b$in1[3] ),
    .C(_053_),
    .X(_054_)
  );
  sky130_fd_sc_hd__maj3_2 _203_ (
    .A(_047_),
    .B(\dpath.a_lt_b$in1[4] ),
    .C(_054_),
    .X(_055_)
  );
  sky130_fd_sc_hd__maj3_2 _204_ (
    .A(_046_),
    .B(\dpath.a_lt_b$in1[5] ),
    .C(_055_),
    .X(_056_)
  );
  sky130_fd_sc_hd__nand2b_1 _205_ (
    .A_N(\dpath.a_lt_b$in1[6] ),
    .B(\dpath.a_lt_b$in0[6] ),
    .Y(_057_)
  );
  sky130_fd_sc_hd__o221ai_2 _206_ (
    .A1(_042_),
    .A2(\dpath.a_lt_b$in1[7] ),
    .B1(_045_),
    .B2(_056_),
    .C1(_057_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nor2b_1 _207_ (
    .A(\dpath.a_lt_b$in1[8] ),
    .B_N(\dpath.a_lt_b$in0[8] ),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nor2b_1 _208_ (
    .A(\dpath.a_lt_b$in1[9] ),
    .B_N(\dpath.a_lt_b$in0[9] ),
    .Y(_060_)
  );
  sky130_fd_sc_hd__a311o_1 _209_ (
    .A1(_041_),
    .A2(_043_),
    .A3(_058_),
    .B1(_059_),
    .C1(_060_),
    .X(_061_)
  );
  sky130_fd_sc_hd__nor2b_1 _210_ (
    .A(\dpath.a_lt_b$in1[10] ),
    .B_N(\dpath.a_lt_b$in0[10] ),
    .Y(_062_)
  );
  sky130_fd_sc_hd__nor2b_1 _211_ (
    .A(\dpath.a_lt_b$in1[11] ),
    .B_N(\dpath.a_lt_b$in0[11] ),
    .Y(_063_)
  );
  sky130_fd_sc_hd__a311o_1 _212_ (
    .A1(_039_),
    .A2(_040_),
    .A3(_061_),
    .B1(_062_),
    .C1(_063_),
    .X(_064_)
  );
  sky130_fd_sc_hd__nor2b_1 _213_ (
    .A(\dpath.a_lt_b$in1[12] ),
    .B_N(\dpath.a_lt_b$in0[12] ),
    .Y(_065_)
  );
  sky130_fd_sc_hd__nor2b_1 _214_ (
    .A(\dpath.a_lt_b$in1[13] ),
    .B_N(\dpath.a_lt_b$in0[13] ),
    .Y(_066_)
  );
  sky130_fd_sc_hd__a311o_2 _215_ (
    .A1(_037_),
    .A2(_038_),
    .A3(_064_),
    .B1(_065_),
    .C1(_066_),
    .X(_067_)
  );
  sky130_fd_sc_hd__nor2b_1 _216_ (
    .A(\dpath.a_lt_b$in1[14] ),
    .B_N(\dpath.a_lt_b$in0[14] ),
    .Y(_068_)
  );
  sky130_fd_sc_hd__a31oi_1 _217_ (
    .A1(_035_),
    .A2(_036_),
    .A3(_067_),
    .B1(_068_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nor2b_1 _218_ (
    .A(\dpath.a_lt_b$in0[15] ),
    .B_N(\dpath.a_lt_b$in1[15] ),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nor2b_1 _219_ (
    .A(\dpath.a_lt_b$in1[15] ),
    .B_N(\dpath.a_lt_b$in0[15] ),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nor2_1 _220_ (
    .A(_070_),
    .B(_071_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__xnor2_1 _221_ (
    .A(_069_),
    .B(_072_),
    .Y(resp_msg[15])
  );
  sky130_fd_sc_hd__xnor2_1 _222_ (
    .A(\dpath.a_lt_b$in0[1] ),
    .B(\dpath.a_lt_b$in1[1] ),
    .Y(_073_)
  );
  sky130_fd_sc_hd__xnor2_1 _223_ (
    .A(_051_),
    .B(_073_),
    .Y(resp_msg[1])
  );
  sky130_fd_sc_hd__xnor2_1 _224_ (
    .A(\dpath.a_lt_b$in0[2] ),
    .B(\dpath.a_lt_b$in1[2] ),
    .Y(_074_)
  );
  sky130_fd_sc_hd__xnor2_1 _225_ (
    .A(_074_),
    .B(_052_),
    .Y(resp_msg[2])
  );
  sky130_fd_sc_hd__xnor2_1 _226_ (
    .A(\dpath.a_lt_b$in0[3] ),
    .B(\dpath.a_lt_b$in1[3] ),
    .Y(_075_)
  );
  sky130_fd_sc_hd__xnor2_1 _227_ (
    .A(_053_),
    .B(_075_),
    .Y(resp_msg[3])
  );
  sky130_fd_sc_hd__xnor2_1 _228_ (
    .A(\dpath.a_lt_b$in0[4] ),
    .B(\dpath.a_lt_b$in1[4] ),
    .Y(_076_)
  );
  sky130_fd_sc_hd__xnor2_1 _229_ (
    .A(_076_),
    .B(_054_),
    .Y(resp_msg[4])
  );
  sky130_fd_sc_hd__xnor2_1 _230_ (
    .A(\dpath.a_lt_b$in0[5] ),
    .B(\dpath.a_lt_b$in1[5] ),
    .Y(_077_)
  );
  sky130_fd_sc_hd__xnor2_1 _231_ (
    .A(_055_),
    .B(_077_),
    .Y(resp_msg[5])
  );
  sky130_fd_sc_hd__xnor2_1 _232_ (
    .A(_044_),
    .B(_056_),
    .Y(resp_msg[6])
  );
  sky130_fd_sc_hd__o21a_1 _233_ (
    .A1(_045_),
    .A2(_056_),
    .B1(_057_),
    .X(_078_)
  );
  sky130_fd_sc_hd__xor2_1 _234_ (
    .A(\dpath.a_lt_b$in0[7] ),
    .B(\dpath.a_lt_b$in1[7] ),
    .X(_079_)
  );
  sky130_fd_sc_hd__xor2_1 _235_ (
    .A(_078_),
    .B(_079_),
    .X(resp_msg[7])
  );
  sky130_fd_sc_hd__nand2_1 _236_ (
    .A(_043_),
    .B(_058_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__xnor2_1 _237_ (
    .A(_041_),
    .B(_080_),
    .Y(resp_msg[8])
  );
  sky130_fd_sc_hd__a31o_2 _238_ (
    .A1(_041_),
    .A2(_043_),
    .A3(_058_),
    .B1(_059_),
    .X(_081_)
  );
  sky130_fd_sc_hd__nand2b_1 _239_ (
    .A_N(_060_),
    .B(_040_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__xnor2_1 _240_ (
    .A(_081_),
    .B(_082_),
    .Y(resp_msg[9])
  );
  sky130_fd_sc_hd__and2_1 _241_ (
    .A(_040_),
    .B(_061_),
    .X(_083_)
  );
  sky130_fd_sc_hd__xor2_1 _242_ (
    .A(_039_),
    .B(_083_),
    .X(resp_msg[10])
  );
  sky130_fd_sc_hd__a21oi_1 _243_ (
    .A1(_039_),
    .A2(_083_),
    .B1(_062_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__nand2b_1 _244_ (
    .A_N(_063_),
    .B(_038_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__xor2_1 _245_ (
    .A(_084_),
    .B(_085_),
    .X(resp_msg[11])
  );
  sky130_fd_sc_hd__nand2_1 _246_ (
    .A(_038_),
    .B(_064_),
    .Y(_086_)
  );
  sky130_fd_sc_hd__xnor2_1 _247_ (
    .A(_037_),
    .B(_086_),
    .Y(resp_msg[12])
  );
  sky130_fd_sc_hd__a31oi_1 _248_ (
    .A1(_037_),
    .A2(_038_),
    .A3(_064_),
    .B1(_065_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__nor2b_1 _249_ (
    .A(_066_),
    .B_N(_036_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__xnor2_1 _250_ (
    .A(_087_),
    .B(_088_),
    .Y(resp_msg[13])
  );
  sky130_fd_sc_hd__and2_1 _251_ (
    .A(_036_),
    .B(_067_),
    .X(_089_)
  );
  sky130_fd_sc_hd__xor2_1 _252_ (
    .A(_035_),
    .B(_089_),
    .X(resp_msg[14])
  );
  sky130_fd_sc_hd__nor2_1 _253_ (
    .A(\dpath.a_lt_b$in1[10] ),
    .B(\dpath.a_lt_b$in1[12] ),
    .Y(_090_)
  );
  sky130_fd_sc_hd__nor4_1 _254_ (
    .A(\dpath.a_lt_b$in1[9] ),
    .B(\dpath.a_lt_b$in1[13] ),
    .C(\dpath.a_lt_b$in1[14] ),
    .D(\dpath.a_lt_b$in1[15] ),
    .Y(_091_)
  );
  sky130_fd_sc_hd__nor4_1 _255_ (
    .A(\dpath.a_lt_b$in1[0] ),
    .B(\dpath.a_lt_b$in1[1] ),
    .C(\dpath.a_lt_b$in1[8] ),
    .D(\dpath.a_lt_b$in1[11] ),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nand3_1 _256_ (
    .A(_090_),
    .B(_091_),
    .C(_092_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__or4_1 _257_ (
    .A(\dpath.a_lt_b$in1[2] ),
    .B(\dpath.a_lt_b$in1[3] ),
    .C(\dpath.a_lt_b$in1[4] ),
    .D(\dpath.a_lt_b$in1[7] ),
    .X(_094_)
  );
  sky130_fd_sc_hd__nor4_1 _258_ (
    .A(\dpath.a_lt_b$in1[5] ),
    .B(\dpath.a_lt_b$in1[6] ),
    .C(_093_),
    .D(_094_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__inv_1 _259_ (
    .A(reset),
    .Y(_096_)
  );
  sky130_fd_sc_hd__nand2_1 _260_ (
    .A(\ctrl.state.out[2] ),
    .B(_096_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__clkbuf_1 _261_ (
    .A(req_rdy),
    .X(_098_)
  );
  sky130_fd_sc_hd__clkbuf_1 _262_ (
    .A(_098_),
    .X(_099_)
  );
  sky130_fd_sc_hd__nand2_1 _263_ (
    .A(_099_),
    .B(req_val),
    .Y(_100_)
  );
  sky130_fd_sc_hd__o22ai_1 _264_ (
    .A1(_095_),
    .A2(_097_),
    .B1(_100_),
    .B2(reset),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nor2_1 _265_ (
    .A(_098_),
    .B(\ctrl.state.out[2] ),
    .Y(_101_)
  );
  sky130_fd_sc_hd__and2_1 _266_ (
    .A(\ctrl.state.out[1] ),
    .B(_101_),
    .X(resp_val)
  );
  sky130_fd_sc_hd__inv_1 _267_ (
    .A(_098_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__a21oi_1 _268_ (
    .A1(resp_rdy),
    .A2(resp_val),
    .B1(reset),
    .Y(_103_)
  );
  sky130_fd_sc_hd__o21ai_0 _269_ (
    .A1(_102_),
    .A2(req_val),
    .B1(_103_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__a32o_1 _270_ (
    .A1(\ctrl.state.out[2] ),
    .A2(_096_),
    .A3(_095_),
    .B1(_103_),
    .B2(\ctrl.state.out[1] ),
    .X(_001_)
  );
  sky130_fd_sc_hd__a311oi_2 _271_ (
    .A1(_035_),
    .A2(_036_),
    .A3(_067_),
    .B1(_071_),
    .C1(_068_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__or2_2 _272_ (
    .A(_098_),
    .B(\ctrl.state.out[2] ),
    .X(_105_)
  );
  sky130_fd_sc_hd__o31ai_2 _273_ (
    .A1(_098_),
    .A2(_070_),
    .A3(_104_),
    .B1(_105_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__buf_6 _274_ (
    .A(_106_),
    .X(_107_)
  );
  sky130_fd_sc_hd__clkbuf_1 _275_ (
    .A(_098_),
    .X(_108_)
  );
  sky130_fd_sc_hd__mux2i_1 _276_ (
    .A0(\dpath.a_lt_b$in0[0] ),
    .A1(req_msg[0]),
    .S(_108_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__nand2_1 _277_ (
    .A(\dpath.a_lt_b$in1[0] ),
    .B(_107_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__o21ai_0 _278_ (
    .A1(_107_),
    .A2(_109_),
    .B1(_110_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__buf_6 _279_ (
    .A(_106_),
    .X(_111_)
  );
  sky130_fd_sc_hd__nand2_1 _280_ (
    .A(_102_),
    .B(\ctrl.state.out[2] ),
    .Y(_112_)
  );
  sky130_fd_sc_hd__o21ba_1 _281_ (
    .A1(_070_),
    .A2(_104_),
    .B1_N(_112_),
    .X(_113_)
  );
  sky130_fd_sc_hd__buf_6 _282_ (
    .A(_113_),
    .X(_114_)
  );
  sky130_fd_sc_hd__a222oi_1 _283_ (
    .A1(_099_),
    .A2(req_msg[1]),
    .B1(\dpath.a_lt_b$in1[1] ),
    .B2(_111_),
    .C1(_114_),
    .C2(\dpath.a_lt_b$in0[1] ),
    .Y(_115_)
  );
  sky130_fd_sc_hd__inv_1 _284_ (
    .A(_115_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__buf_4 _285_ (
    .A(_114_),
    .X(_116_)
  );
  sky130_fd_sc_hd__a222oi_1 _286_ (
    .A1(_108_),
    .A2(req_msg[2]),
    .B1(\dpath.a_lt_b$in1[2] ),
    .B2(_111_),
    .C1(_116_),
    .C2(\dpath.a_lt_b$in0[2] ),
    .Y(_117_)
  );
  sky130_fd_sc_hd__inv_1 _287_ (
    .A(_117_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__a222oi_1 _288_ (
    .A1(_099_),
    .A2(req_msg[3]),
    .B1(\dpath.a_lt_b$in1[3] ),
    .B2(_111_),
    .C1(_116_),
    .C2(\dpath.a_lt_b$in0[3] ),
    .Y(_118_)
  );
  sky130_fd_sc_hd__inv_1 _289_ (
    .A(_118_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__a222oi_1 _290_ (
    .A1(_099_),
    .A2(req_msg[4]),
    .B1(\dpath.a_lt_b$in1[4] ),
    .B2(_107_),
    .C1(_116_),
    .C2(\dpath.a_lt_b$in0[4] ),
    .Y(_119_)
  );
  sky130_fd_sc_hd__inv_1 _291_ (
    .A(_119_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__a222oi_1 _292_ (
    .A1(_108_),
    .A2(req_msg[5]),
    .B1(\dpath.a_lt_b$in1[5] ),
    .B2(_111_),
    .C1(_116_),
    .C2(\dpath.a_lt_b$in0[5] ),
    .Y(_120_)
  );
  sky130_fd_sc_hd__inv_1 _293_ (
    .A(_120_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__a222oi_1 _294_ (
    .A1(_108_),
    .A2(req_msg[6]),
    .B1(\dpath.a_lt_b$in1[6] ),
    .B2(_111_),
    .C1(_114_),
    .C2(\dpath.a_lt_b$in0[6] ),
    .Y(_121_)
  );
  sky130_fd_sc_hd__inv_1 _295_ (
    .A(_121_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__a222oi_1 _296_ (
    .A1(_108_),
    .A2(req_msg[7]),
    .B1(\dpath.a_lt_b$in1[7] ),
    .B2(_107_),
    .C1(_116_),
    .C2(\dpath.a_lt_b$in0[7] ),
    .Y(_122_)
  );
  sky130_fd_sc_hd__inv_1 _297_ (
    .A(_122_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__a222oi_1 _298_ (
    .A1(_099_),
    .A2(req_msg[8]),
    .B1(\dpath.a_lt_b$in1[8] ),
    .B2(_111_),
    .C1(_116_),
    .C2(\dpath.a_lt_b$in0[8] ),
    .Y(_123_)
  );
  sky130_fd_sc_hd__inv_1 _299_ (
    .A(_123_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__mux2i_1 _300_ (
    .A0(\dpath.a_lt_b$in0[9] ),
    .A1(req_msg[9]),
    .S(_108_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__nand2_1 _301_ (
    .A(\dpath.a_lt_b$in1[9] ),
    .B(_107_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__o21ai_0 _302_ (
    .A1(_107_),
    .A2(_124_),
    .B1(_125_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__a222oi_1 _303_ (
    .A1(_099_),
    .A2(req_msg[10]),
    .B1(\dpath.a_lt_b$in1[10] ),
    .B2(_111_),
    .C1(_116_),
    .C2(\dpath.a_lt_b$in0[10] ),
    .Y(_126_)
  );
  sky130_fd_sc_hd__inv_1 _304_ (
    .A(_126_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__a222oi_1 _305_ (
    .A1(_099_),
    .A2(req_msg[11]),
    .B1(\dpath.a_lt_b$in1[11] ),
    .B2(_111_),
    .C1(_116_),
    .C2(\dpath.a_lt_b$in0[11] ),
    .Y(_127_)
  );
  sky130_fd_sc_hd__inv_1 _306_ (
    .A(_127_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__a222oi_1 _307_ (
    .A1(_108_),
    .A2(req_msg[12]),
    .B1(\dpath.a_lt_b$in1[12] ),
    .B2(_111_),
    .C1(_116_),
    .C2(\dpath.a_lt_b$in0[12] ),
    .Y(_128_)
  );
  sky130_fd_sc_hd__inv_1 _308_ (
    .A(_128_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__mux2i_1 _309_ (
    .A0(\dpath.a_lt_b$in0[13] ),
    .A1(req_msg[13]),
    .S(_108_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__nand2_1 _310_ (
    .A(\dpath.a_lt_b$in1[13] ),
    .B(_107_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__o21ai_0 _311_ (
    .A1(_107_),
    .A2(_129_),
    .B1(_130_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__a222oi_1 _312_ (
    .A1(_099_),
    .A2(req_msg[14]),
    .B1(\dpath.a_lt_b$in1[14] ),
    .B2(_111_),
    .C1(_116_),
    .C2(\dpath.a_lt_b$in0[14] ),
    .Y(_131_)
  );
  sky130_fd_sc_hd__inv_1 _313_ (
    .A(_131_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__mux2i_1 _314_ (
    .A0(\dpath.a_lt_b$in0[15] ),
    .A1(req_msg[15]),
    .S(_108_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__nand2_1 _315_ (
    .A(\dpath.a_lt_b$in1[15] ),
    .B(_107_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__o21ai_0 _316_ (
    .A1(_107_),
    .A2(_132_),
    .B1(_133_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__buf_8 _317_ (
    .A(_114_),
    .X(_134_)
  );
  sky130_fd_sc_hd__nand2_1 _318_ (
    .A(\dpath.a_lt_b$in1[0] ),
    .B(_134_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__clkbuf_1 _319_ (
    .A(_098_),
    .X(_136_)
  );
  sky130_fd_sc_hd__nor3_2 _320_ (
    .A(_070_),
    .B(_104_),
    .C(_112_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__buf_6 _321_ (
    .A(_137_),
    .X(_138_)
  );
  sky130_fd_sc_hd__clkbuf_1 _322_ (
    .A(_101_),
    .X(_139_)
  );
  sky130_fd_sc_hd__a221oi_2 _323_ (
    .A1(_136_),
    .A2(req_msg[16]),
    .B1(resp_msg[0]),
    .B2(_138_),
    .C1(_139_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__clkbuf_1 _324_ (
    .A(_105_),
    .X(_141_)
  );
  sky130_fd_sc_hd__nor2_1 _325_ (
    .A(\dpath.a_lt_b$in0[0] ),
    .B(_141_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__a21oi_1 _326_ (
    .A1(_135_),
    .A2(_140_),
    .B1(_142_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__clkbuf_1 _327_ (
    .A(_101_),
    .X(_143_)
  );
  sky130_fd_sc_hd__nand2_1 _328_ (
    .A(\dpath.a_lt_b$in1[1] ),
    .B(_134_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__a221oi_1 _329_ (
    .A1(_098_),
    .A2(req_msg[17]),
    .B1(resp_msg[1]),
    .B2(_137_),
    .C1(_101_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__a22oi_1 _330_ (
    .A1(_050_),
    .A2(_143_),
    .B1(_144_),
    .B2(_145_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nand2_1 _331_ (
    .A(\dpath.a_lt_b$in1[2] ),
    .B(_134_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__a221oi_1 _332_ (
    .A1(_136_),
    .A2(req_msg[18]),
    .B1(resp_msg[2]),
    .B2(_137_),
    .C1(_139_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__a22oi_1 _333_ (
    .A1(_049_),
    .A2(_143_),
    .B1(_146_),
    .B2(_147_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nand2_1 _334_ (
    .A(\dpath.a_lt_b$in1[3] ),
    .B(_134_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__a221oi_1 _335_ (
    .A1(_136_),
    .A2(req_msg[19]),
    .B1(resp_msg[3]),
    .B2(_137_),
    .C1(_139_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__a22oi_1 _336_ (
    .A1(_048_),
    .A2(_143_),
    .B1(_148_),
    .B2(_149_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__a22oi_1 _337_ (
    .A1(_099_),
    .A2(req_msg[20]),
    .B1(resp_msg[4]),
    .B2(_138_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__a21oi_1 _338_ (
    .A1(\dpath.a_lt_b$in1[4] ),
    .A2(_114_),
    .B1(_143_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__a22oi_1 _339_ (
    .A1(_047_),
    .A2(_143_),
    .B1(_150_),
    .B2(_151_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nand2_1 _340_ (
    .A(\dpath.a_lt_b$in1[5] ),
    .B(_134_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__a221oi_1 _341_ (
    .A1(_136_),
    .A2(req_msg[21]),
    .B1(resp_msg[5]),
    .B2(_137_),
    .C1(_139_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__a22oi_1 _342_ (
    .A1(_046_),
    .A2(_143_),
    .B1(_152_),
    .B2(_153_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nand2_1 _343_ (
    .A(\dpath.a_lt_b$in1[6] ),
    .B(_134_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__a221oi_2 _344_ (
    .A1(_108_),
    .A2(req_msg[22]),
    .B1(resp_msg[6]),
    .B2(_138_),
    .C1(_143_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__a2bb2oi_2 _345_ (
    .A1_N(\dpath.a_lt_b$in0[6] ),
    .A2_N(_141_),
    .B1(_154_),
    .B2(_155_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__nand2_1 _346_ (
    .A(resp_msg[7]),
    .B(_138_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__a221oi_1 _347_ (
    .A1(_136_),
    .A2(req_msg[23]),
    .B1(_114_),
    .B2(\dpath.a_lt_b$in1[7] ),
    .C1(_139_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__a22oi_1 _348_ (
    .A1(_042_),
    .A2(_143_),
    .B1(_156_),
    .B2(_157_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__o21ai_0 _349_ (
    .A1(_102_),
    .A2(req_msg[24]),
    .B1(_112_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__a22oi_1 _350_ (
    .A1(\dpath.a_lt_b$in1[8] ),
    .A2(_114_),
    .B1(_138_),
    .B2(resp_msg[8]),
    .Y(_159_)
  );
  sky130_fd_sc_hd__nor2_1 _351_ (
    .A(\dpath.a_lt_b$in0[8] ),
    .B(_141_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__a21oi_1 _352_ (
    .A1(_158_),
    .A2(_159_),
    .B1(_160_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__nand2_1 _353_ (
    .A(\dpath.a_lt_b$in1[9] ),
    .B(_134_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__a221oi_1 _354_ (
    .A1(_136_),
    .A2(req_msg[25]),
    .B1(resp_msg[9]),
    .B2(_137_),
    .C1(_139_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__nor2_1 _355_ (
    .A(\dpath.a_lt_b$in0[9] ),
    .B(_141_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__a21oi_1 _356_ (
    .A1(_161_),
    .A2(_162_),
    .B1(_163_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nand2_1 _357_ (
    .A(\dpath.a_lt_b$in1[10] ),
    .B(_134_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__a221oi_1 _358_ (
    .A1(_136_),
    .A2(req_msg[26]),
    .B1(resp_msg[10]),
    .B2(_137_),
    .C1(_143_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__nor2_1 _359_ (
    .A(\dpath.a_lt_b$in0[10] ),
    .B(_141_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__a21oi_1 _360_ (
    .A1(_164_),
    .A2(_165_),
    .B1(_166_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__nand2_1 _361_ (
    .A(resp_msg[11]),
    .B(_138_),
    .Y(_167_)
  );
  sky130_fd_sc_hd__a221oi_1 _362_ (
    .A1(_136_),
    .A2(req_msg[27]),
    .B1(_114_),
    .B2(\dpath.a_lt_b$in1[11] ),
    .C1(_139_),
    .Y(_168_)
  );
  sky130_fd_sc_hd__nor2_1 _363_ (
    .A(\dpath.a_lt_b$in0[11] ),
    .B(_141_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__a21oi_1 _364_ (
    .A1(_167_),
    .A2(_168_),
    .B1(_169_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__nand2_1 _365_ (
    .A(\dpath.a_lt_b$in1[12] ),
    .B(_134_),
    .Y(_170_)
  );
  sky130_fd_sc_hd__a221oi_2 _366_ (
    .A1(_136_),
    .A2(req_msg[28]),
    .B1(resp_msg[12]),
    .B2(_138_),
    .C1(_139_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__nor2_1 _367_ (
    .A(\dpath.a_lt_b$in0[12] ),
    .B(_141_),
    .Y(_172_)
  );
  sky130_fd_sc_hd__a21oi_1 _368_ (
    .A1(_170_),
    .A2(_171_),
    .B1(_172_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__nand2_1 _369_ (
    .A(\dpath.a_lt_b$in1[13] ),
    .B(_134_),
    .Y(_173_)
  );
  sky130_fd_sc_hd__a221oi_2 _370_ (
    .A1(_136_),
    .A2(req_msg[29]),
    .B1(resp_msg[13]),
    .B2(_138_),
    .C1(_139_),
    .Y(_174_)
  );
  sky130_fd_sc_hd__nor2_1 _371_ (
    .A(\dpath.a_lt_b$in0[13] ),
    .B(_141_),
    .Y(_175_)
  );
  sky130_fd_sc_hd__a21oi_1 _372_ (
    .A1(_173_),
    .A2(_174_),
    .B1(_175_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__a22oi_1 _373_ (
    .A1(_099_),
    .A2(req_msg[30]),
    .B1(resp_msg[14]),
    .B2(_138_),
    .Y(_176_)
  );
  sky130_fd_sc_hd__a21oi_1 _374_ (
    .A1(\dpath.a_lt_b$in1[14] ),
    .A2(_114_),
    .B1(_143_),
    .Y(_177_)
  );
  sky130_fd_sc_hd__nor2_1 _375_ (
    .A(\dpath.a_lt_b$in0[14] ),
    .B(_141_),
    .Y(_178_)
  );
  sky130_fd_sc_hd__a21oi_1 _376_ (
    .A1(_176_),
    .A2(_177_),
    .B1(_178_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nand2_1 _377_ (
    .A(resp_msg[15]),
    .B(_138_),
    .Y(_179_)
  );
  sky130_fd_sc_hd__a221oi_1 _378_ (
    .A1(req_msg[31]),
    .A2(_112_),
    .B1(_114_),
    .B2(\dpath.a_lt_b$in1[15] ),
    .C1(_139_),
    .Y(_180_)
  );
  sky130_fd_sc_hd__nor2_1 _379_ (
    .A(\dpath.a_lt_b$in0[15] ),
    .B(_141_),
    .Y(_181_)
  );
  sky130_fd_sc_hd__a21oi_1 _380_ (
    .A1(_179_),
    .A2(_180_),
    .B1(_181_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__dfxtp_1 _381_ (
    .CLK(clk),
    .D(_000_),
    .Q(req_rdy)
  );
  sky130_fd_sc_hd__dfxtp_1 _382_ (
    .CLK(clk),
    .D(_001_),
    .Q(\ctrl.state.out[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 _383_ (
    .CLK(clk),
    .D(_002_),
    .Q(\ctrl.state.out[2] )
  );
  sky130_fd_sc_hd__dfxtp_1 _384_ (
    .CLK(clk),
    .D(_003_),
    .Q(\dpath.a_lt_b$in1[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 _385_ (
    .CLK(clk),
    .D(_004_),
    .Q(\dpath.a_lt_b$in1[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 _386_ (
    .CLK(clk),
    .D(_005_),
    .Q(\dpath.a_lt_b$in1[2] )
  );
  sky130_fd_sc_hd__dfxtp_1 _387_ (
    .CLK(clk),
    .D(_006_),
    .Q(\dpath.a_lt_b$in1[3] )
  );
  sky130_fd_sc_hd__dfxtp_1 _388_ (
    .CLK(clk),
    .D(_007_),
    .Q(\dpath.a_lt_b$in1[4] )
  );
  sky130_fd_sc_hd__dfxtp_1 _389_ (
    .CLK(clk),
    .D(_008_),
    .Q(\dpath.a_lt_b$in1[5] )
  );
  sky130_fd_sc_hd__dfxtp_1 _390_ (
    .CLK(clk),
    .D(_009_),
    .Q(\dpath.a_lt_b$in1[6] )
  );
  sky130_fd_sc_hd__dfxtp_1 _391_ (
    .CLK(clk),
    .D(_010_),
    .Q(\dpath.a_lt_b$in1[7] )
  );
  sky130_fd_sc_hd__dfxtp_1 _392_ (
    .CLK(clk),
    .D(_011_),
    .Q(\dpath.a_lt_b$in1[8] )
  );
  sky130_fd_sc_hd__dfxtp_1 _393_ (
    .CLK(clk),
    .D(_012_),
    .Q(\dpath.a_lt_b$in1[9] )
  );
  sky130_fd_sc_hd__dfxtp_1 _394_ (
    .CLK(clk),
    .D(_013_),
    .Q(\dpath.a_lt_b$in1[10] )
  );
  sky130_fd_sc_hd__dfxtp_1 _395_ (
    .CLK(clk),
    .D(_014_),
    .Q(\dpath.a_lt_b$in1[11] )
  );
  sky130_fd_sc_hd__dfxtp_1 _396_ (
    .CLK(clk),
    .D(_015_),
    .Q(\dpath.a_lt_b$in1[12] )
  );
  sky130_fd_sc_hd__dfxtp_1 _397_ (
    .CLK(clk),
    .D(_016_),
    .Q(\dpath.a_lt_b$in1[13] )
  );
  sky130_fd_sc_hd__dfxtp_1 _398_ (
    .CLK(clk),
    .D(_017_),
    .Q(\dpath.a_lt_b$in1[14] )
  );
  sky130_fd_sc_hd__dfxtp_1 _399_ (
    .CLK(clk),
    .D(_018_),
    .Q(\dpath.a_lt_b$in1[15] )
  );
  sky130_fd_sc_hd__dfxtp_1 _400_ (
    .CLK(clk),
    .D(_019_),
    .Q(\dpath.a_lt_b$in0[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 _401_ (
    .CLK(clk),
    .D(_020_),
    .Q(\dpath.a_lt_b$in0[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 _402_ (
    .CLK(clk),
    .D(_021_),
    .Q(\dpath.a_lt_b$in0[2] )
  );
  sky130_fd_sc_hd__dfxtp_1 _403_ (
    .CLK(clk),
    .D(_022_),
    .Q(\dpath.a_lt_b$in0[3] )
  );
  sky130_fd_sc_hd__dfxtp_1 _404_ (
    .CLK(clk),
    .D(_023_),
    .Q(\dpath.a_lt_b$in0[4] )
  );
  sky130_fd_sc_hd__dfxtp_1 _405_ (
    .CLK(clk),
    .D(_024_),
    .Q(\dpath.a_lt_b$in0[5] )
  );
  sky130_fd_sc_hd__dfxtp_1 _406_ (
    .CLK(clk),
    .D(_025_),
    .Q(\dpath.a_lt_b$in0[6] )
  );
  sky130_fd_sc_hd__dfxtp_1 _407_ (
    .CLK(clk),
    .D(_026_),
    .Q(\dpath.a_lt_b$in0[7] )
  );
  sky130_fd_sc_hd__dfxtp_1 _408_ (
    .CLK(clk),
    .D(_027_),
    .Q(\dpath.a_lt_b$in0[8] )
  );
  sky130_fd_sc_hd__dfxtp_1 _409_ (
    .CLK(clk),
    .D(_028_),
    .Q(\dpath.a_lt_b$in0[9] )
  );
  sky130_fd_sc_hd__dfxtp_1 _410_ (
    .CLK(clk),
    .D(_029_),
    .Q(\dpath.a_lt_b$in0[10] )
  );
  sky130_fd_sc_hd__dfxtp_1 _411_ (
    .CLK(clk),
    .D(_030_),
    .Q(\dpath.a_lt_b$in0[11] )
  );
  sky130_fd_sc_hd__dfxtp_1 _412_ (
    .CLK(clk),
    .D(_031_),
    .Q(\dpath.a_lt_b$in0[12] )
  );
  sky130_fd_sc_hd__dfxtp_1 _413_ (
    .CLK(clk),
    .D(_032_),
    .Q(\dpath.a_lt_b$in0[13] )
  );
  sky130_fd_sc_hd__dfxtp_1 _414_ (
    .CLK(clk),
    .D(_033_),
    .Q(\dpath.a_lt_b$in0[14] )
  );
  sky130_fd_sc_hd__dfxtp_1 _415_ (
    .CLK(clk),
    .D(_034_),
    .Q(\dpath.a_lt_b$in0[15] )
  );
endmodule
