#!/bin/sh
# The next line is executed by /bin/sh, but not Tcl \
exec tclsh $0 ${1+"$@"}

# Copyright (c) 2019, Parallax Software, Inc.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Usage: regression help | test1 [test2...]
# where test is all or the name of a tcl script in $STA/test

# Directory containing tests.
set test_dir [file dirname [file normalize [info script]]]

source [file join $test_dir "regression_vars.tcl"]
source [file join $test_dir "regression.tcl"]

regression_main
if {0} {
puts "OpenROAD"
puts "----------------------------------------------------------------"
regression_main

puts "ioPlacer"
puts "----------------------------------------------------------------"
puts [exec "src/ioPlacer/tests/run_all.sh"]

puts "Resizer"
puts "----------------------------------------------------------------"
puts [exec "src/resizer/test/regression"]

puts "pdngen"
puts "----------------------------------------------------------------"
puts [exec "src/pdngen/test/regression"]

puts "Macro Place"
puts "----------------------------------------------------------------"
puts [exec "src/TritonMacroPlace/test/regression"]

puts "OpenDP"
puts "----------------------------------------------------------------"
puts [exec "src/opendp/test/regression"]

puts "TritonCTS"
puts "----------------------------------------------------------------"
puts [exec "src/TritonCTS/tests/run_all.sh"]

if {0} {
# hangs indefinitely
#pushd src/replace/test && python3 regression.py run openroad && popd

# errors: sed: 1: "/Users/cherry/sta/openr ...": command c expects \ followed by text
#cp etc/PO* . && tclsh ./src/FastRoute/tests/run_all.tcl
}
}

# Local Variables:
# mode:tcl
# End:
