###############################################################################
# Created by write_sdc
# Thu Apr  6 10:37:06 2023
###############################################################################
current_design Element
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clock -period 8000.0000 [get_ports {clock}]
set_input_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_ins_0[0]}]
set_input_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_ins_0[1]}]
set_input_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_ins_0[2]}]
set_input_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_ins_0[3]}]
set_input_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_ins_0[4]}]
set_input_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_ins_0[5]}]
set_input_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_ins_0[6]}]
set_input_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_ins_0[7]}]
set_input_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_ins_1[0]}]
set_input_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_ins_1[1]}]
set_input_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_ins_1[2]}]
set_input_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_ins_1[3]}]
set_input_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_ins_1[4]}]
set_input_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_ins_1[5]}]
set_input_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_ins_1[6]}]
set_input_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_ins_1[7]}]
set_input_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_ins_2[0]}]
set_input_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_ins_2[1]}]
set_input_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_ins_2[2]}]
set_input_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_ins_2[3]}]
set_input_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_ins_2[4]}]
set_input_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_ins_2[5]}]
set_input_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_ins_2[6]}]
set_input_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_ins_2[7]}]
set_input_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_ins_3[0]}]
set_input_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_ins_3[1]}]
set_input_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_ins_3[2]}]
set_input_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_ins_3[3]}]
set_input_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_ins_3[4]}]
set_input_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_ins_3[5]}]
set_input_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_ins_3[6]}]
set_input_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_ins_3[7]}]
set_output_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_outs_0[0]}]
set_output_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_outs_0[1]}]
set_output_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_outs_0[2]}]
set_output_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_outs_0[3]}]
set_output_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_outs_0[4]}]
set_output_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_outs_0[5]}]
set_output_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_outs_0[6]}]
set_output_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_outs_0[7]}]
set_output_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_outs_1[0]}]
set_output_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_outs_1[1]}]
set_output_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_outs_1[2]}]
set_output_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_outs_1[3]}]
set_output_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_outs_1[4]}]
set_output_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_outs_1[5]}]
set_output_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_outs_1[6]}]
set_output_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_outs_1[7]}]
set_output_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_outs_2[0]}]
set_output_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_outs_2[1]}]
set_output_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_outs_2[2]}]
set_output_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_outs_2[3]}]
set_output_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_outs_2[4]}]
set_output_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_outs_2[5]}]
set_output_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_outs_2[6]}]
set_output_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_outs_2[7]}]
set_output_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_outs_3[0]}]
set_output_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_outs_3[1]}]
set_output_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_outs_3[2]}]
set_output_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_outs_3[3]}]
set_output_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_outs_3[4]}]
set_output_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_outs_3[5]}]
set_output_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_outs_3[6]}]
set_output_delay 1600.0000 -clock [get_clocks {clock}] -add_delay [get_ports {io_outs_3[7]}]
###############################################################################
# Environment
###############################################################################
###############################################################################
# Design Rules
###############################################################################
