if(EXISTS "/home/memzfs_projects/MLBuf_extension/OR_latest/build/src/dbSta/test/cpp/TestHconn[1]_tests.cmake")
  include("/home/memzfs_projects/MLBuf_extension/OR_latest/build/src/dbSta/test/cpp/TestHconn[1]_tests.cmake")
else()
  add_test(TestHconn_NOT_BUILT TestHconn_NOT_BUILT)
endif()
