// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2019-2025, The OpenROAD Authors

#pragma once

#include <cstdint>
#include <cstring>

#include "dbCore.h"
#include "odb/dbId.h"
#include "odb/dbTypes.h"
#include "odb/dbViaParams.h"
#include "odb/geom.h"

namespace odb {

class _dbBox;
class _dbDatabase;
class _dbTech;
class _dbTechLayer;
class _dbTechViaGenerateRule;
class dbIStream;
class dbOStream;

struct _dbViaFlags
{
  uint32_t is_rotated : 1;
  uint32_t is_tech_via : 1;
  uint32_t has_params : 1;
  dbOrientType::Value orient : 4;
  bool default_via : 1;
  uint32_t spare_bits : 24;
};

class _dbVia : public _dbObject
{
 public:
  _dbVia(_dbDatabase*, const _dbVia& v);
  _dbVia(_dbDatabase*);
  ~_dbVia();

  bool operator==(const _dbVia& rhs) const;
  bool operator!=(const _dbVia& rhs) const { return !operator==(rhs); }
  bool operator<(const _dbVia& rhs) const
  {
    return strcmp(name_, rhs.name_) < 0;
  }

  _dbTech* getTech();
  void collectMemInfo(MemInfo& info);

  // PERSISTANT-MEMBERS
  _dbViaFlags flags_;  // 5.6 DEF
  char* name_;
  char* pattern_;
  dbId<_dbBox> bbox_;  // Caching the bbox speeds up defin imports.
  dbId<_dbBox> boxes_;
  dbId<_dbTechLayer> top_;     // Caching the layer speeds up defin imports.
  dbId<_dbTechLayer> bottom_;  // Caching the layer speeds up defin imports.

  // via generated by tech-via-rule, 5.6 DEF
  dbId<_dbTechViaGenerateRule> generate_rule_;
  uint32_t
      rotated_via_id_;  // via-id that was roated to produce this via, 5.6 DEF
  _dbViaParams via_params_;  // params used to generate this via, 5.6 DEF
};

dbOStream& operator<<(dbOStream& stream, const _dbVia& v);
dbIStream& operator>>(dbIStream& stream, _dbVia& v);

}  // namespace odb
