# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2026, The OpenROAD Authors
"""Hermetic Bazel driver for OpenROAD man page generation.

Replaces the docs/Makefile + make + nroff chain with an explicit
Python + pandoc workflow that Bazel can fully sandbox.  All inputs
(pandoc binary, README files, messages, scripts) are passed as
explicit CLI arguments; nothing is looked up from PATH or the host
filesystem.

Usage (generated by //bazel:man_pages.bzl):
  python manpages_impl.py \\
    --pandoc     /path/to/pandoc \\
    --script     docs/src/scripts/md_roff_compat.py \\
    --script     docs/src/scripts/manpage.py \\
    --script     docs/src/scripts/extract_utils.py \\
    --readme     ant:src/ant/README.md \\
    --readme     cts:src/cts/README.md \\
    ...
    --messages   ant:src/ant/messages.txt \\
    ...
    --man1-src   docs/md/man1/openroad.md \\
    ...
    --cat-out    bazel-out/.../docs/cat \\
    --html-out   bazel-out/.../docs/html
"""

import argparse
import os
import shutil
import subprocess
import sys
import tempfile


def _run_pandoc(pandoc, src, dst, to_format):
    subprocess.run(
        [pandoc, "-s", "-t", to_format, src, "-o", dst, "--quiet"],
        check=True,
    )


def _process_section(pandoc, md_dir, roff_scratch, html_dir, cat_dir,
                     section_num, skip_stems=None):
    """Convert every .md in md_dir → roff → HTML + cat pages."""
    skip_stems = skip_stems or set()
    for fname in sorted(os.listdir(md_dir)):
        if not fname.endswith(".md"):
            continue
        stem = fname[:-3]
        if stem in skip_stems:
            continue
        src = os.path.join(md_dir, fname)
        roff = os.path.join(roff_scratch, f"{stem}.{section_num}")
        _run_pandoc(pandoc, src, roff, "man")
        _run_pandoc(pandoc, roff,
                    os.path.join(html_dir, f"{stem}.html"), "html")
        # pandoc plain replaces nroff -man | col -b
        _run_pandoc(pandoc, roff,
                    os.path.join(cat_dir, f"{stem}.{section_num}"), "plain")


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--pandoc", required=True,
                   help="Path to pandoc binary")
    p.add_argument("--script", action="append", default=[],
                   help="Python script path (may be repeated)")
    p.add_argument("--readme", action="append", default=[],
                   help="module:path pairs for README.md files")
    p.add_argument("--messages", action="append", default=[],
                   help="module:path pairs for messages.txt files")
    p.add_argument("--man1-src", action="append", default=[],
                   help="man1 source .md files")
    p.add_argument("--cat-out", required=True,
                   help="Output directory for cat pages")
    p.add_argument("--html-out", required=True,
                   help="Output directory for html pages")
    args = p.parse_args()

    with tempfile.TemporaryDirectory() as workdir:
        # Copy pandoc into a writable temp location and make it executable.
        # Input files in the Bazel sandbox may be on a read-only mount, so
        # chmod-ing the original path would fail on some platforms/zip archives.
        pandoc = os.path.join(workdir, "pandoc")
        shutil.copy(args.pandoc, pandoc)
        os.chmod(pandoc, 0o755)
        # Mirror the directory layout that md_roff_compat.py expects when
        # run from docs/:
        #   ./md/man2/{module}.md   ← README copies
        #   ../src/{module}/messages.txt
        docs_dir = os.path.join(workdir, "docs")
        man1_md = os.path.join(docs_dir, "md", "man1")
        man2_md = os.path.join(docs_dir, "md", "man2")
        man3_md = os.path.join(docs_dir, "md", "man3")
        scripts_dir = os.path.join(docs_dir, "src", "scripts")
        for d in [man1_md, man2_md, man3_md, scripts_dir]:
            os.makedirs(d)

        # Copy Python helper scripts so their relative imports resolve.
        for script_path in args.script:
            if script_path.endswith(".py"):
                shutil.copy(script_path, scripts_dir)

        # Copy man1 source files.
        for f in args.man1_src:
            shutil.copy(f, man1_md)

        # Copy README files as {module}.md (replacing link_readmes.sh).
        for spec in args.readme:
            module, path = spec.split(":", 1)
            shutil.copy(path, os.path.join(man2_md, f"{module}.md"))

        # Copy messages.txt files next to each other as ../src/{module}/.
        for spec in args.messages:
            module, path = spec.split(":", 1)
            mod_dir = os.path.join(workdir, "src", module)
            os.makedirs(mod_dir, exist_ok=True)
            shutil.copy(path, os.path.join(mod_dir, "messages.txt"))

        # Track which .md files exist in man2 BEFORE the generator runs so
        # we can skip them when running pandoc (they're module-level READMEs,
        # not individual function man pages).
        readme_stems = {
            os.path.splitext(f)[0]
            for f in os.listdir(man2_md)
            if f.endswith(".md")
        }

        # Run md_roff_compat.py from docs_dir so its relative paths
        # (./md/man2, ../src) resolve correctly.
        subprocess.run(
            [sys.executable,
             os.path.join(scripts_dir, "md_roff_compat.py")],
            cwd=docs_dir,
            env={**os.environ, "PYTHONPATH": scripts_dir},
            check=True,
        )

        # Prepare output sub-directories inside the declared output trees.
        cat_out = args.cat_out
        html_out = args.html_out
        roff_scratch = os.path.join(workdir, "roff")
        for section in ["1", "2", "3"]:
            os.makedirs(os.path.join(cat_out, f"cat{section}"), exist_ok=True)
            os.makedirs(os.path.join(html_out, f"html{section}"), exist_ok=True)
            os.makedirs(os.path.join(roff_scratch, f"man{section}"))

        # man1: straight from source .md files
        _process_section(
            pandoc, man1_md,
            os.path.join(roff_scratch, "man1"),
            os.path.join(html_out, "html1"),
            os.path.join(cat_out, "cat1"),
            section_num=1,
        )

        # man2: only the per-function files generated by md_roff_compat.py
        _process_section(
            pandoc, man2_md,
            os.path.join(roff_scratch, "man2"),
            os.path.join(html_out, "html2"),
            os.path.join(cat_out, "cat2"),
            section_num=2,
            skip_stems=readme_stems,
        )

        # man3: all files written to man3 (messages-derived pages)
        _process_section(
            pandoc, man3_md,
            os.path.join(roff_scratch, "man3"),
            os.path.join(html_out, "html3"),
            os.path.join(cat_out, "cat3"),
            section_num=3,
        )


if __name__ == "__main__":
    main()
