# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2025, The OpenROAD Authors
#
# Bazel repository rule to locate and expose the system-installed
# tclreadline library (Linux only).
#
# On Debian/Ubuntu: apt install tcl-tclreadline
# On RHEL/CentOS:   yum install tcl-tclreadline-devel
#
# This rule uses pkg-config (if available) or falls back to
# common installation paths used by the official OpenROAD Docker image.

def _tclreadline_system_repo_impl(ctx):
    """Detects the system tclreadline library and exposes it as a cc_library."""

    # Try pkg-config first
    result = ctx.execute(["pkg-config", "--cflags", "--libs", "tclreadline"])
    if result.return_code == 0:
        flags = result.stdout.strip().split()
        include_dirs = [f[2:] for f in flags if f.startswith("-I")]
        lib_dirs = [f[2:] for f in flags if f.startswith("-L")]
        libs = [f[2:] for f in flags if f.startswith("-l")]
    else:
        # Fall back to common system paths used in the official OpenROAD
        # Docker image (ubuntu:22.04 / ubuntu:24.04 based).
        include_dirs = ["/usr/include"]
        lib_dirs = ["/usr/lib", "/usr/lib/x86_64-linux-gnu"]
        libs = ["tclreadline"]

    # Find the header
    header_found = False
    header_dir = ""
    unique_include_dirs = {}
    for d in include_dirs + ["/usr/include", "/usr/local/include"]:
        unique_include_dirs[d] = True
    for d in unique_include_dirs.keys():
        result = ctx.execute(["test", "-f", d + "/tclreadline.h"])
        if result.return_code == 0:
            header_found = True
            header_dir = d
            break

    # Find the library
    lib_found = False
    lib_path = ""
    unique_lib_dirs = {}
    for d in lib_dirs + [
        "/usr/lib",
        "/usr/lib/x86_64-linux-gnu",
        "/usr/lib/aarch64-linux-gnu",
        "/usr/local/lib",
    ]:
        unique_lib_dirs[d] = True
        
    unique_libs = {}
    for name in libs + ["tclreadline"]:
        unique_libs[name] = True

    for d in unique_lib_dirs.keys():
        for name in unique_libs.keys():
            for suffix in [".so", ".a"]:
                candidate = d + "/lib" + name + suffix
                result = ctx.execute(["test", "-f", candidate])
                if result.return_code == 0:
                    lib_found = True
                    lib_path = candidate
                    break
            if lib_found:
                break
        if lib_found:
            break

    # Also search for versioned names (tclreadline-2.3.x)
    if not lib_found:
        unique_lib_dirs_versioned = {}
        for d in lib_dirs + ["/usr/lib", "/usr/lib/x86_64-linux-gnu", "/usr/lib/aarch64-linux-gnu"]:
            unique_lib_dirs_versioned[d] = True
        for d in unique_lib_dirs_versioned.keys():
            result = ctx.execute(["sh", "-c", "ls " + d + "/libtclreadline* 2>/dev/null | head -1"])
            if result.return_code == 0 and result.stdout.strip():
                lib_path = result.stdout.strip()
                lib_found = True
                break

    # Determine the TCLRL_LIBRARY path (where tclreadlineInit.tcl lives)
    tclrl_library = ""
    result = ctx.execute(["sh", "-c", "find /usr/share/tcltk /usr/lib -name 'tclreadlineInit.tcl' 2>/dev/null | head -1"])
    if result.return_code == 0 and result.stdout.strip():
        tclrl_library = result.stdout.strip().replace("/tclreadlineInit.tcl", "")

    if not tclrl_library:
        # Common default path in Ubuntu Docker image
        tclrl_library = "/usr/lib/tclreadline"

    if lib_found and header_found:
        ctx.file("BUILD.bazel", """
# Auto-generated by bazel/tclreadline.bzl
# Do not edit manually.
cc_import(
    name = "tclreadline",
    hdrs = ["tclreadline.h"],
    shared_library = "{lib_path}",
    visibility = ["//visibility:public"],
)

# Exposes the path to tclreadlineInit.tcl as a cc_library define,
# so Main.cc can load the correct init script at runtime.
cc_library(
    name = "tclreadline_defs",
    defines = [
        "ENABLE_READLINE",
        'TCLRL_LIBRARY=\\\\"{tclrl_library}\\\\"',
    ],
    visibility = ["//visibility:public"],
)
""".format(lib_path = lib_path, tclrl_library = tclrl_library))
        ctx.symlink(header_dir + "/tclreadline.h", "tclreadline.h")
    else:
        # Create an empty stub so the build does not fail on systems
        # where tclreadline is not installed (e.g., macOS CI).
        ctx.file("BUILD.bazel", """
# tclreadline not found on this system — empty stub targets.
cc_library(
    name = "tclreadline",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "tclreadline_defs",
    visibility = ["//visibility:public"],
)
""")

    return {
        "tclrl_library": tclrl_library,
        "found": lib_found and header_found,
    }

tclreadline_system_repo = repository_rule(
    implementation = _tclreadline_system_repo_impl,
    local = True,
    doc = """
Detects the system-installed tclreadline library.

On Linux (the official OpenROAD Docker image), tclreadline is installed via:
  apt install tcl-tclreadline

This rule creates a @tclreadline//:tclreadline cc_import target that can be
used as a dependency in the openroad cc_binary.
""",
)
