# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2026, The OpenROAD Authors

"""The browser libraries the web viewer serves from the OpenROAD binary.

They are fetched rather than checked in, so third-party/packages.json is the one
place their versions live; this extension turns each entry there into an
http_archive, and hands //src/web the served path -> label mapping through a
generated assets.bzl.  The CMake build reads the same manifest through
third-party/fetch_packages.py.
"""

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

_MANIFEST = Label("//src/web:third-party/packages.json")

def _tarball_url(registry, name, version):
    # Scoped names live at @scope/name/-/name-version.tgz.
    basename = name.split("/")[-1]
    return "{}/{}/-/{}-{}.tgz".format(registry, name, basename, version)

def _package_repo(name):
    return "web_" + name.replace("-", "_").replace("/", "_")

def _esbuild_repo(platform):
    return "esbuild_" + platform.replace("-", "_")

def _build_file(exported, bundle):
    lines = [
        'package(default_visibility = ["//visibility:public"])',
        "",
        "exports_files([",
    ]
    lines += ['    "{}",'.format(path) for path in exported]
    lines.append("])")
    if bundle:
        lines += [
            "",
            "filegroup(",
            '    name = "bundle_tree",',
            '    srcs = glob(["{}/**"]),'.format(bundle["tree"]),
            ")",
        ]
    return "\n".join(lines) + "\n"

def _assets_bzl(assets, bundles):
    """The manifest as Starlark, so //src/web does not restate it."""
    lines = [
        "# Generated by //bazel:web_third_party.bzl -- do not edit.",
        "",
        "# (served path, label of the file to serve there).",
        "WEB_THIRD_PARTY_ASSETS = [",
    ]
    lines += ['    ("{}", "{}"),'.format(served, label) for served, label in assets]
    lines += [
        "]",
        "",
        "# Packages that publish no browser build and are bundled by the build.",
        "WEB_THIRD_PARTY_BUNDLES = [",
    ]
    for bundle in bundles:
        lines += [
            "    struct(",
            '        package = "{}",'.format(bundle["package"]),
            '        tree = "{}",'.format(bundle["tree"]),
            '        entry = "{}",'.format(bundle["entry"]),
            '        out = "{}",'.format(bundle["out"]),
            '        served = "{}",'.format(bundle["served"]),
            "    ),",
        ]
    lines.append("]")
    return "\n".join(lines) + "\n"

def _assets_repo_impl(repository_ctx):
    repository_ctx.file("BUILD", "")
    repository_ctx.file("assets.bzl", repository_ctx.attr.content)

_assets_repo = repository_rule(
    implementation = _assets_repo_impl,
    attrs = {"content": attr.string(mandatory = True)},
)

def _web_third_party_impl(module_ctx):
    manifest = json.decode(module_ctx.read(_MANIFEST))
    registry = manifest["registry"]

    assets = []
    bundles = []
    for name, spec in manifest["packages"].items():
        repo = _package_repo(name)
        bundle = spec.get("bundle")
        exported = sorted(spec["files"].keys())
        if bundle:
            exported = sorted(exported + [bundle["entry"]])

        http_archive(
            name = repo,
            build_file_content = _build_file(exported, bundle),
            sha256 = spec["sha256"],
            strip_prefix = "package",
            urls = [_tarball_url(registry, name, spec["version"])],
        )

        for source, served in spec["files"].items():
            assets.append(
                ("/third-party/" + served, "@{}//:{}".format(repo, source)),
            )
        if bundle:
            bundles.append({
                "entry": "@{}//:{}".format(repo, bundle["entry"]),
                # A genrule output, so it is a path in //src/web, not a label.
                "out": "third-party/" + bundle["output"],
                "package": name,
                "served": "/third-party/" + bundle["output"],
                "tree": "@{}//:bundle_tree".format(repo),
            })

    esbuild = manifest["esbuild"]
    for platform, sha256 in esbuild["platforms"].items():
        http_archive(
            name = _esbuild_repo(platform),
            build_file_content = (
                'exports_files(["bin/esbuild"], visibility = ["//visibility:public"])\n'
            ),
            sha256 = sha256,
            strip_prefix = "package",
            urls = [
                _tarball_url(
                    registry,
                    "@esbuild/" + platform,
                    esbuild["version"],
                ),
            ],
        )

    _assets_repo(
        name = "web_third_party",
        content = _assets_bzl(sorted(assets), bundles),
    )

web_third_party = module_extension(implementation = _web_third_party_impl)
