# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.0
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError('Python 2.7 or later required')

# Import the low-level C/C++ module
if __package__ or '.' in __name__:
    from . import _dpl_py
else:
    import _dpl_py

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if name == "thisown":
        return self.this.own(value)
    if name == "this":
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if not static:
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if name == "thisown":
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _dpl_py.delete_SwigPyIterator

    def value(self):
        return _dpl_py.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _dpl_py.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _dpl_py.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _dpl_py.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _dpl_py.SwigPyIterator_equal(self, x)

    def copy(self):
        return _dpl_py.SwigPyIterator_copy(self)

    def next(self):
        return _dpl_py.SwigPyIterator_next(self)

    def __next__(self):
        return _dpl_py.SwigPyIterator___next__(self)

    def previous(self):
        return _dpl_py.SwigPyIterator_previous(self)

    def advance(self, n):
        return _dpl_py.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _dpl_py.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _dpl_py.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _dpl_py.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _dpl_py.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _dpl_py.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _dpl_py.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _dpl_py:
_dpl_py.SwigPyIterator_swigregister(SwigPyIterator)

class Opendp(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, db, logger):
        _dpl_py.Opendp_swiginit(self, _dpl_py.new_Opendp(db, logger))
    __swig_destroy__ = _dpl_py.delete_Opendp

    def legalCellPos(self, db_inst):
        return _dpl_py.Opendp_legalCellPos(self, db_inst)

    def initMacrosAndGrid(self):
        return _dpl_py.Opendp_initMacrosAndGrid(self)

    def detailedPlacement(self, *args):
        return _dpl_py.Opendp_detailedPlacement(self, *args)

    def reportLegalizationStats(self):
        return _dpl_py.Opendp_reportLegalizationStats(self)

    def setPaddingGlobal(self, left, right):
        return _dpl_py.Opendp_setPaddingGlobal(self, left, right)

    def setPadding(self, *args):
        return _dpl_py.Opendp_setPadding(self, *args)

    def setDebug(self, observer):
        return _dpl_py.Opendp_setDebug(self, observer)

    def padGlobalLeft(self):
        return _dpl_py.Opendp_padGlobalLeft(self)

    def padGlobalRight(self):
        return _dpl_py.Opendp_padGlobalRight(self)

    def padLeft(self, inst):
        return _dpl_py.Opendp_padLeft(self, inst)

    def padRight(self, inst):
        return _dpl_py.Opendp_padRight(self, inst)

    def checkPlacement(self, *args):
        return _dpl_py.Opendp_checkPlacement(self, *args)

    def fillerPlacement(self, filler_masters, prefix, verbose):
        return _dpl_py.Opendp_fillerPlacement(self, filler_masters, prefix, verbose)

    def removeFillers(self):
        return _dpl_py.Opendp_removeFillers(self)

    def optimizeMirroring(self):
        return _dpl_py.Opendp_optimizeMirroring(self)

    def addDecapMaster(self, decap_master, decap_cap):
        return _dpl_py.Opendp_addDecapMaster(self, decap_master, decap_cap)

    def insertDecapCells(self, target, psm_ir_drops):
        return _dpl_py.Opendp_insertDecapCells(self, target, psm_ir_drops)

    def getAdjacentInstance(self, inst, left):
        return _dpl_py.Opendp_getAdjacentInstance(self, inst, left)

    def getAdjacentInstancesCluster(self, inst):
        return _dpl_py.Opendp_getAdjacentInstancesCluster(self, inst)

    def getPadding(self):
        return _dpl_py.Opendp_getPadding(self)

    def improvePlacement(self, seed, max_displacement_x, max_displacement_y):
        return _dpl_py.Opendp_improvePlacement(self, seed, max_displacement_x, max_displacement_y)

    def getJournal(self):
        return _dpl_py.Opendp_getJournal(self)

    def setJournal(self, journal):
        return _dpl_py.Opendp_setJournal(self, journal)

# Register Opendp in _dpl_py:
_dpl_py.Opendp_swigregister(Opendp)


def divRound(dividend, divisor):
    return _dpl_py.divRound(dividend, divisor)

def divCeil(dividend, divisor):
    return _dpl_py.divCeil(dividend, divisor)

def divFloor(dividend, divisor):
    return _dpl_py.divFloor(dividend, divisor)


