# CMake generated Testfile for 
# Source directory: /home/memzfs_projects/MLBuf_extension/OR_latest/src/ant/test
# Build directory: /home/memzfs_projects/MLBuf_extension/OR_latest/build/src/ant/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ant.ant_check.tcl "/usr/bin/bash" "/home/memzfs_projects/MLBuf_extension/OR_latest/test/regression_test.sh")
set_tests_properties(ant.ant_check.tcl PROPERTIES  ENVIRONMENT "OPENROAD_EXE=/home/memzfs_projects/MLBuf_extension/OR_latest/build/bin/openroad;TEST_NAME=ant_check;TEST_EXT=tcl;TEST_TYPE=tcl;TEST_CHECK_LOG=True;TEST_CHECK_PASSFAIL=False" LABELS "IntegrationTest tcl ant log_compare" WORKING_DIRECTORY "/home/memzfs_projects/MLBuf_extension/OR_latest/src/ant/test" _BACKTRACE_TRIPLES "/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;19;add_test;/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;86;or_integration_test_single;/home/memzfs_projects/MLBuf_extension/OR_latest/src/ant/test/CMakeLists.txt;1;or_integration_tests;/home/memzfs_projects/MLBuf_extension/OR_latest/src/ant/test/CMakeLists.txt;0;")
add_test(ant.ant_check.py "/usr/bin/bash" "/home/memzfs_projects/MLBuf_extension/OR_latest/test/regression_test.sh")
set_tests_properties(ant.ant_check.py PROPERTIES  ENVIRONMENT "OPENROAD_EXE=/home/memzfs_projects/MLBuf_extension/OR_latest/build/bin/openroad;TEST_NAME=ant_check;TEST_EXT=py;TEST_TYPE=python;TEST_CHECK_LOG=True;TEST_CHECK_PASSFAIL=False" LABELS "IntegrationTest python ant log_compare" WORKING_DIRECTORY "/home/memzfs_projects/MLBuf_extension/OR_latest/src/ant/test" _BACKTRACE_TRIPLES "/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;19;add_test;/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;88;or_integration_test_single;/home/memzfs_projects/MLBuf_extension/OR_latest/src/ant/test/CMakeLists.txt;1;or_integration_tests;/home/memzfs_projects/MLBuf_extension/OR_latest/src/ant/test/CMakeLists.txt;0;")
add_test(ant.ant_report.tcl "/usr/bin/bash" "/home/memzfs_projects/MLBuf_extension/OR_latest/test/regression_test.sh")
set_tests_properties(ant.ant_report.tcl PROPERTIES  ENVIRONMENT "OPENROAD_EXE=/home/memzfs_projects/MLBuf_extension/OR_latest/build/bin/openroad;TEST_NAME=ant_report;TEST_EXT=tcl;TEST_TYPE=tcl;TEST_CHECK_LOG=True;TEST_CHECK_PASSFAIL=False" LABELS "IntegrationTest tcl ant log_compare" WORKING_DIRECTORY "/home/memzfs_projects/MLBuf_extension/OR_latest/src/ant/test" _BACKTRACE_TRIPLES "/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;19;add_test;/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;86;or_integration_test_single;/home/memzfs_projects/MLBuf_extension/OR_latest/src/ant/test/CMakeLists.txt;1;or_integration_tests;/home/memzfs_projects/MLBuf_extension/OR_latest/src/ant/test/CMakeLists.txt;0;")
add_test(ant.ant_report.py "/usr/bin/bash" "/home/memzfs_projects/MLBuf_extension/OR_latest/test/regression_test.sh")
set_tests_properties(ant.ant_report.py PROPERTIES  ENVIRONMENT "OPENROAD_EXE=/home/memzfs_projects/MLBuf_extension/OR_latest/build/bin/openroad;TEST_NAME=ant_report;TEST_EXT=py;TEST_TYPE=python;TEST_CHECK_LOG=True;TEST_CHECK_PASSFAIL=False" LABELS "IntegrationTest python ant log_compare" WORKING_DIRECTORY "/home/memzfs_projects/MLBuf_extension/OR_latest/src/ant/test" _BACKTRACE_TRIPLES "/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;19;add_test;/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;88;or_integration_test_single;/home/memzfs_projects/MLBuf_extension/OR_latest/src/ant/test/CMakeLists.txt;1;or_integration_tests;/home/memzfs_projects/MLBuf_extension/OR_latest/src/ant/test/CMakeLists.txt;0;")
add_test(ant.check_api1.tcl "/usr/bin/bash" "/home/memzfs_projects/MLBuf_extension/OR_latest/test/regression_test.sh")
set_tests_properties(ant.check_api1.tcl PROPERTIES  ENVIRONMENT "OPENROAD_EXE=/home/memzfs_projects/MLBuf_extension/OR_latest/build/bin/openroad;TEST_NAME=check_api1;TEST_EXT=tcl;TEST_TYPE=tcl;TEST_CHECK_LOG=True;TEST_CHECK_PASSFAIL=False" LABELS "IntegrationTest tcl ant log_compare" WORKING_DIRECTORY "/home/memzfs_projects/MLBuf_extension/OR_latest/src/ant/test" _BACKTRACE_TRIPLES "/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;19;add_test;/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;86;or_integration_test_single;/home/memzfs_projects/MLBuf_extension/OR_latest/src/ant/test/CMakeLists.txt;1;or_integration_tests;/home/memzfs_projects/MLBuf_extension/OR_latest/src/ant/test/CMakeLists.txt;0;")
add_test(ant.check_api1.py "/usr/bin/bash" "/home/memzfs_projects/MLBuf_extension/OR_latest/test/regression_test.sh")
set_tests_properties(ant.check_api1.py PROPERTIES  ENVIRONMENT "OPENROAD_EXE=/home/memzfs_projects/MLBuf_extension/OR_latest/build/bin/openroad;TEST_NAME=check_api1;TEST_EXT=py;TEST_TYPE=python;TEST_CHECK_LOG=True;TEST_CHECK_PASSFAIL=False" LABELS "IntegrationTest python ant log_compare" WORKING_DIRECTORY "/home/memzfs_projects/MLBuf_extension/OR_latest/src/ant/test" _BACKTRACE_TRIPLES "/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;19;add_test;/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;88;or_integration_test_single;/home/memzfs_projects/MLBuf_extension/OR_latest/src/ant/test/CMakeLists.txt;1;or_integration_tests;/home/memzfs_projects/MLBuf_extension/OR_latest/src/ant/test/CMakeLists.txt;0;")
add_test(ant.check_drt1.tcl "/usr/bin/bash" "/home/memzfs_projects/MLBuf_extension/OR_latest/test/regression_test.sh")
set_tests_properties(ant.check_drt1.tcl PROPERTIES  ENVIRONMENT "OPENROAD_EXE=/home/memzfs_projects/MLBuf_extension/OR_latest/build/bin/openroad;TEST_NAME=check_drt1;TEST_EXT=tcl;TEST_TYPE=tcl;TEST_CHECK_LOG=True;TEST_CHECK_PASSFAIL=False" LABELS "IntegrationTest tcl ant log_compare" WORKING_DIRECTORY "/home/memzfs_projects/MLBuf_extension/OR_latest/src/ant/test" _BACKTRACE_TRIPLES "/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;19;add_test;/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;86;or_integration_test_single;/home/memzfs_projects/MLBuf_extension/OR_latest/src/ant/test/CMakeLists.txt;1;or_integration_tests;/home/memzfs_projects/MLBuf_extension/OR_latest/src/ant/test/CMakeLists.txt;0;")
add_test(ant.check_drt1.py "/usr/bin/bash" "/home/memzfs_projects/MLBuf_extension/OR_latest/test/regression_test.sh")
set_tests_properties(ant.check_drt1.py PROPERTIES  ENVIRONMENT "OPENROAD_EXE=/home/memzfs_projects/MLBuf_extension/OR_latest/build/bin/openroad;TEST_NAME=check_drt1;TEST_EXT=py;TEST_TYPE=python;TEST_CHECK_LOG=True;TEST_CHECK_PASSFAIL=False" LABELS "IntegrationTest python ant log_compare" WORKING_DIRECTORY "/home/memzfs_projects/MLBuf_extension/OR_latest/src/ant/test" _BACKTRACE_TRIPLES "/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;19;add_test;/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;88;or_integration_test_single;/home/memzfs_projects/MLBuf_extension/OR_latest/src/ant/test/CMakeLists.txt;1;or_integration_tests;/home/memzfs_projects/MLBuf_extension/OR_latest/src/ant/test/CMakeLists.txt;0;")
add_test(ant.check_grt1.tcl "/usr/bin/bash" "/home/memzfs_projects/MLBuf_extension/OR_latest/test/regression_test.sh")
set_tests_properties(ant.check_grt1.tcl PROPERTIES  ENVIRONMENT "OPENROAD_EXE=/home/memzfs_projects/MLBuf_extension/OR_latest/build/bin/openroad;TEST_NAME=check_grt1;TEST_EXT=tcl;TEST_TYPE=tcl;TEST_CHECK_LOG=True;TEST_CHECK_PASSFAIL=False" LABELS "IntegrationTest tcl ant log_compare" WORKING_DIRECTORY "/home/memzfs_projects/MLBuf_extension/OR_latest/src/ant/test" _BACKTRACE_TRIPLES "/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;19;add_test;/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;86;or_integration_test_single;/home/memzfs_projects/MLBuf_extension/OR_latest/src/ant/test/CMakeLists.txt;1;or_integration_tests;/home/memzfs_projects/MLBuf_extension/OR_latest/src/ant/test/CMakeLists.txt;0;")
