# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.0
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError('Python 2.7 or later required')

# Import the low-level C/C++ module
if __package__ or '.' in __name__:
    from . import _ppl_py
else:
    import _ppl_py

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if name == "thisown":
        return self.this.own(value)
    if name == "this":
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if not static:
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if name == "thisown":
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class Parameters(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def setReportHPWL(self, report):
        return _ppl_py.Parameters_setReportHPWL(self, report)

    def getReportHPWL(self):
        return _ppl_py.Parameters_getReportHPWL(self)

    def setSlotsPerSection(self, slots_per_section):
        return _ppl_py.Parameters_setSlotsPerSection(self, slots_per_section)

    def getSlotsPerSection(self):
        return _ppl_py.Parameters_getSlotsPerSection(self)

    def setHorizontalLengthExtend(self, length):
        return _ppl_py.Parameters_setHorizontalLengthExtend(self, length)

    def getHorizontalLengthExtend(self):
        return _ppl_py.Parameters_getHorizontalLengthExtend(self)

    def setVerticalLengthExtend(self, length):
        return _ppl_py.Parameters_setVerticalLengthExtend(self, length)

    def getVerticalLengthExtend(self):
        return _ppl_py.Parameters_getVerticalLengthExtend(self)

    def setHorizontalLength(self, length):
        return _ppl_py.Parameters_setHorizontalLength(self, length)

    def getHorizontalLength(self):
        return _ppl_py.Parameters_getHorizontalLength(self)

    def setVerticalLength(self, length):
        return _ppl_py.Parameters_setVerticalLength(self, length)

    def getVerticalLength(self):
        return _ppl_py.Parameters_getVerticalLength(self)

    def setRandSeed(self, seed):
        return _ppl_py.Parameters_setRandSeed(self, seed)

    def getRandSeed(self):
        return _ppl_py.Parameters_getRandSeed(self)

    def setHorizontalThicknessMultiplier(self, length):
        return _ppl_py.Parameters_setHorizontalThicknessMultiplier(self, length)

    def getHorizontalThicknessMultiplier(self):
        return _ppl_py.Parameters_getHorizontalThicknessMultiplier(self)

    def setVerticalThicknessMultiplier(self, length):
        return _ppl_py.Parameters_setVerticalThicknessMultiplier(self, length)

    def getVerticalThicknessMultiplier(self):
        return _ppl_py.Parameters_getVerticalThicknessMultiplier(self)

    def setCornerAvoidance(self, length):
        return _ppl_py.Parameters_setCornerAvoidance(self, length)

    def getCornerAvoidance(self):
        return _ppl_py.Parameters_getCornerAvoidance(self)

    def setMinDistance(self, min_dist):
        return _ppl_py.Parameters_setMinDistance(self, min_dist)

    def getMinDistance(self):
        return _ppl_py.Parameters_getMinDistance(self)

    def setMinDistanceInTracks(self, in_tracks):
        return _ppl_py.Parameters_setMinDistanceInTracks(self, in_tracks)

    def getMinDistanceInTracks(self):
        return _ppl_py.Parameters_getMinDistanceInTracks(self)

    def setPinPlacementFile(self, file_name):
        return _ppl_py.Parameters_setPinPlacementFile(self, file_name)

    def getPinPlacementFile(self):
        return _ppl_py.Parameters_getPinPlacementFile(self)

    def __init__(self):
        _ppl_py.Parameters_swiginit(self, _ppl_py.new_Parameters())
    __swig_destroy__ = _ppl_py.delete_Parameters

# Register Parameters in _ppl_py:
_ppl_py.Parameters_swigregister(Parameters)

class PinGroupByIndex(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    pin_indices = property(_ppl_py.PinGroupByIndex_pin_indices_get, _ppl_py.PinGroupByIndex_pin_indices_set)
    order = property(_ppl_py.PinGroupByIndex_order_get, _ppl_py.PinGroupByIndex_order_set)

    def __init__(self):
        _ppl_py.PinGroupByIndex_swiginit(self, _ppl_py.new_PinGroupByIndex())
    __swig_destroy__ = _ppl_py.delete_PinGroupByIndex

# Register PinGroupByIndex in _ppl_py:
_ppl_py.PinGroupByIndex_swigregister(PinGroupByIndex)

class FallbackPins(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    groups = property(_ppl_py.FallbackPins_groups_get, _ppl_py.FallbackPins_groups_set)
    pins = property(_ppl_py.FallbackPins_pins_get, _ppl_py.FallbackPins_pins_set)

    def __init__(self):
        _ppl_py.FallbackPins_swiginit(self, _ppl_py.new_FallbackPins())
    __swig_destroy__ = _ppl_py.delete_FallbackPins

# Register FallbackPins in _ppl_py:
_ppl_py.FallbackPins_swigregister(FallbackPins)

Edge_top = _ppl_py.Edge_top
Edge_bottom = _ppl_py.Edge_bottom
Edge_left = _ppl_py.Edge_left
Edge_right = _ppl_py.Edge_right
Edge_invalid = _ppl_py.Edge_invalid
Edge_polygonEdge = _ppl_py.Edge_polygonEdge
Direction_input = _ppl_py.Direction_input
Direction_output = _ppl_py.Direction_output
Direction_inout = _ppl_py.Direction_inout
Direction_feedthru = _ppl_py.Direction_feedthru
Direction_invalid = _ppl_py.Direction_invalid
class IOPlacer(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, db, logger):
        _ppl_py.IOPlacer_swiginit(self, _ppl_py.new_IOPlacer(db, logger))
    __swig_destroy__ = _ppl_py.delete_IOPlacer

    def clear(self):
        return _ppl_py.IOPlacer_clear(self)

    def clearConstraints(self):
        return _ppl_py.IOPlacer_clearConstraints(self)

    def runHungarianMatching(self):
        return _ppl_py.IOPlacer_runHungarianMatching(self)

    def runAnnealing(self):
        return _ppl_py.IOPlacer_runAnnealing(self)

    def getParameters(self):
        return _ppl_py.IOPlacer_getParameters(self)

    def computeIONetsHPWL(self):
        return _ppl_py.IOPlacer_computeIONetsHPWL(self)

    def excludeInterval(self, edge, begin, end):
        return _ppl_py.IOPlacer_excludeInterval(self, edge, begin, end)

    def addHorLayer(self, layer):
        return _ppl_py.IOPlacer_addHorLayer(self, layer)

    def addVerLayer(self, layer):
        return _ppl_py.IOPlacer_addVerLayer(self, layer)

    def placePin(self, bterm, layer, x, y, width, height, force_to_die_bound, placed_status):
        return _ppl_py.IOPlacer_placePin(self, bterm, layer, x, y, width, height, force_to_die_bound, placed_status)

    def setAnnealingConfig(self, temperature, max_iterations, perturb_per_iter, alpha):
        return _ppl_py.IOPlacer_setAnnealingConfig(self, temperature, max_iterations, perturb_per_iter, alpha)

    def setAnnealingDebugOn(self):
        return _ppl_py.IOPlacer_setAnnealingDebugOn(self)

    def isAnnealingDebugOn(self):
        return _ppl_py.IOPlacer_isAnnealingDebugOn(self)

    def setAnnealingDebugPaintInterval(self, iters_between_paintings):
        return _ppl_py.IOPlacer_setAnnealingDebugPaintInterval(self, iters_between_paintings)

    def setAnnealingDebugNoPauseMode(self, no_pause_mode):
        return _ppl_py.IOPlacer_setAnnealingDebugNoPauseMode(self, no_pause_mode)

    def writePinPlacement(self, file_name, placed):
        return _ppl_py.IOPlacer_writePinPlacement(self, file_name, placed)

    @staticmethod
    def getDirection(direction):
        return _ppl_py.IOPlacer_getDirection(direction)

    @staticmethod
    def getEdge(edge):
        return _ppl_py.IOPlacer_getEdge(edge)

# Register IOPlacer in _ppl_py:
_ppl_py.IOPlacer_swigregister(IOPlacer)

def IOPlacer_getDirection(direction):
    return _ppl_py.IOPlacer_getDirection(direction)

def IOPlacer_getEdge(edge):
    return _ppl_py.IOPlacer_getEdge(edge)



