# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2026, The OpenROAD Authors

import unittest

from tldr.parsers.lockfile import LockfileParser
from tldr.strip import strip_line

from _fixture_helpers import read_lines, StaticStageContext


class LockfileTest(unittest.TestCase):
    def test_parses_module_lock_drift(self) -> None:
        raw = read_lines("gha_check_bazel_lock.txt")
        stripped = [strip_line(l) for l in raw]
        out = list(LockfileParser().scan(stripped, StaticStageContext()))
        self.assertEqual(len(out), 1)
        self.assertEqual(out[0].location, "MODULE.bazel.lock")
        # MODULE.bazel.lock is regenerated by `bazelisk mod deps`.
        self.assertEqual(
            out[0].auto_fix_command,
            ("bazelisk", "mod", "deps", "--lockfile_mode=update"),
        )

    def test_requirements_lock_uses_pip_update_target(self) -> None:
        # requirements_lock_3_13.txt drift should map to the pip-update target,
        # not the Bzlmod refresh.
        out = list(
            LockfileParser().scan(
                ["requirements_lock_3_13.txt is out of date"],
                StaticStageContext(),
            )
        )
        self.assertEqual(len(out), 1)
        self.assertEqual(
            out[0].auto_fix_command,
            ("bazelisk", "run", "//bazel:requirements.update"),
        )


if __name__ == "__main__":
    unittest.main()
