if(EXISTS "/home/memzfs_projects/MLBuf_extension/OR_latest/build/src/dpl/test/dpl_test[1]_tests.cmake")
  include("/home/memzfs_projects/MLBuf_extension/OR_latest/build/src/dpl/test/dpl_test[1]_tests.cmake")
else()
  add_test(dpl_test_NOT_BUILT dpl_test_NOT_BUILT)
endif()
