# CMake generated Testfile for 
# Source directory: /home/memzfs_projects/MLBuf_extension/OR_latest/test
# Build directory: /home/memzfs_projects/MLBuf_extension/OR_latest/build/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(openroad.error1.tcl "/usr/bin/bash" "/home/memzfs_projects/MLBuf_extension/OR_latest/test/regression_test.sh")
set_tests_properties(openroad.error1.tcl PROPERTIES  ENVIRONMENT "OPENROAD_EXE=/home/memzfs_projects/MLBuf_extension/OR_latest/build/bin/openroad;TEST_NAME=error1;TEST_EXT=tcl;TEST_TYPE=tcl;TEST_CHECK_LOG=True;TEST_CHECK_PASSFAIL=False" LABELS "IntegrationTest tcl openroad log_compare" WORKING_DIRECTORY "/home/memzfs_projects/MLBuf_extension/OR_latest/test" _BACKTRACE_TRIPLES "/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;19;add_test;/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;86;or_integration_test_single;/home/memzfs_projects/MLBuf_extension/OR_latest/test/CMakeLists.txt;1;or_integration_tests;/home/memzfs_projects/MLBuf_extension/OR_latest/test/CMakeLists.txt;0;")
add_test(openroad.get_core_die_areas.tcl "/usr/bin/bash" "/home/memzfs_projects/MLBuf_extension/OR_latest/test/regression_test.sh")
set_tests_properties(openroad.get_core_die_areas.tcl PROPERTIES  ENVIRONMENT "OPENROAD_EXE=/home/memzfs_projects/MLBuf_extension/OR_latest/build/bin/openroad;TEST_NAME=get_core_die_areas;TEST_EXT=tcl;TEST_TYPE=tcl;TEST_CHECK_LOG=True;TEST_CHECK_PASSFAIL=False" LABELS "IntegrationTest tcl openroad log_compare" WORKING_DIRECTORY "/home/memzfs_projects/MLBuf_extension/OR_latest/test" _BACKTRACE_TRIPLES "/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;19;add_test;/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;86;or_integration_test_single;/home/memzfs_projects/MLBuf_extension/OR_latest/test/CMakeLists.txt;1;or_integration_tests;/home/memzfs_projects/MLBuf_extension/OR_latest/test/CMakeLists.txt;0;")
add_test(openroad.place_inst.tcl "/usr/bin/bash" "/home/memzfs_projects/MLBuf_extension/OR_latest/test/regression_test.sh")
set_tests_properties(openroad.place_inst.tcl PROPERTIES  ENVIRONMENT "OPENROAD_EXE=/home/memzfs_projects/MLBuf_extension/OR_latest/build/bin/openroad;TEST_NAME=place_inst;TEST_EXT=tcl;TEST_TYPE=tcl;TEST_CHECK_LOG=True;TEST_CHECK_PASSFAIL=False" LABELS "IntegrationTest tcl openroad log_compare" WORKING_DIRECTORY "/home/memzfs_projects/MLBuf_extension/OR_latest/test" _BACKTRACE_TRIPLES "/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;19;add_test;/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;86;or_integration_test_single;/home/memzfs_projects/MLBuf_extension/OR_latest/test/CMakeLists.txt;1;or_integration_tests;/home/memzfs_projects/MLBuf_extension/OR_latest/test/CMakeLists.txt;0;")
add_test(openroad.timing_api.py "/usr/bin/bash" "/home/memzfs_projects/MLBuf_extension/OR_latest/test/regression_test.sh")
set_tests_properties(openroad.timing_api.py PROPERTIES  ENVIRONMENT "OPENROAD_EXE=/home/memzfs_projects/MLBuf_extension/OR_latest/build/bin/openroad;TEST_NAME=timing_api;TEST_EXT=py;TEST_TYPE=python;TEST_CHECK_LOG=True;TEST_CHECK_PASSFAIL=False" LABELS "IntegrationTest python openroad log_compare" WORKING_DIRECTORY "/home/memzfs_projects/MLBuf_extension/OR_latest/test" _BACKTRACE_TRIPLES "/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;19;add_test;/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;88;or_integration_test_single;/home/memzfs_projects/MLBuf_extension/OR_latest/test/CMakeLists.txt;1;or_integration_tests;/home/memzfs_projects/MLBuf_extension/OR_latest/test/CMakeLists.txt;0;")
add_test(openroad.timing_api_2.py "/usr/bin/bash" "/home/memzfs_projects/MLBuf_extension/OR_latest/test/regression_test.sh")
set_tests_properties(openroad.timing_api_2.py PROPERTIES  ENVIRONMENT "OPENROAD_EXE=/home/memzfs_projects/MLBuf_extension/OR_latest/build/bin/openroad;TEST_NAME=timing_api_2;TEST_EXT=py;TEST_TYPE=python;TEST_CHECK_LOG=True;TEST_CHECK_PASSFAIL=False" LABELS "IntegrationTest python openroad log_compare" WORKING_DIRECTORY "/home/memzfs_projects/MLBuf_extension/OR_latest/test" _BACKTRACE_TRIPLES "/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;19;add_test;/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;88;or_integration_test_single;/home/memzfs_projects/MLBuf_extension/OR_latest/test/CMakeLists.txt;1;or_integration_tests;/home/memzfs_projects/MLBuf_extension/OR_latest/test/CMakeLists.txt;0;")
add_test(openroad.timing_api_3.py "/usr/bin/bash" "/home/memzfs_projects/MLBuf_extension/OR_latest/test/regression_test.sh")
set_tests_properties(openroad.timing_api_3.py PROPERTIES  ENVIRONMENT "OPENROAD_EXE=/home/memzfs_projects/MLBuf_extension/OR_latest/build/bin/openroad;TEST_NAME=timing_api_3;TEST_EXT=py;TEST_TYPE=python;TEST_CHECK_LOG=True;TEST_CHECK_PASSFAIL=False" LABELS "IntegrationTest python openroad log_compare" WORKING_DIRECTORY "/home/memzfs_projects/MLBuf_extension/OR_latest/test" _BACKTRACE_TRIPLES "/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;19;add_test;/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;88;or_integration_test_single;/home/memzfs_projects/MLBuf_extension/OR_latest/test/CMakeLists.txt;1;or_integration_tests;/home/memzfs_projects/MLBuf_extension/OR_latest/test/CMakeLists.txt;0;")
add_test(openroad.timing_api_4.py "/usr/bin/bash" "/home/memzfs_projects/MLBuf_extension/OR_latest/test/regression_test.sh")
set_tests_properties(openroad.timing_api_4.py PROPERTIES  ENVIRONMENT "OPENROAD_EXE=/home/memzfs_projects/MLBuf_extension/OR_latest/build/bin/openroad;TEST_NAME=timing_api_4;TEST_EXT=py;TEST_TYPE=python;TEST_CHECK_LOG=True;TEST_CHECK_PASSFAIL=False" LABELS "IntegrationTest python openroad log_compare" WORKING_DIRECTORY "/home/memzfs_projects/MLBuf_extension/OR_latest/test" _BACKTRACE_TRIPLES "/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;19;add_test;/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;88;or_integration_test_single;/home/memzfs_projects/MLBuf_extension/OR_latest/test/CMakeLists.txt;1;or_integration_tests;/home/memzfs_projects/MLBuf_extension/OR_latest/test/CMakeLists.txt;0;")
add_test(openroad.two_designs.py "/usr/bin/bash" "/home/memzfs_projects/MLBuf_extension/OR_latest/test/regression_test.sh")
set_tests_properties(openroad.two_designs.py PROPERTIES  ENVIRONMENT "OPENROAD_EXE=/home/memzfs_projects/MLBuf_extension/OR_latest/build/bin/openroad;TEST_NAME=two_designs;TEST_EXT=py;TEST_TYPE=python;TEST_CHECK_LOG=True;TEST_CHECK_PASSFAIL=False" LABELS "IntegrationTest python openroad log_compare" WORKING_DIRECTORY "/home/memzfs_projects/MLBuf_extension/OR_latest/test" _BACKTRACE_TRIPLES "/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;19;add_test;/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;88;or_integration_test_single;/home/memzfs_projects/MLBuf_extension/OR_latest/test/CMakeLists.txt;1;or_integration_tests;/home/memzfs_projects/MLBuf_extension/OR_latest/test/CMakeLists.txt;0;")
add_test(openroad.upf_test.tcl "/usr/bin/bash" "/home/memzfs_projects/MLBuf_extension/OR_latest/test/regression_test.sh")
set_tests_properties(openroad.upf_test.tcl PROPERTIES  ENVIRONMENT "OPENROAD_EXE=/home/memzfs_projects/MLBuf_extension/OR_latest/build/bin/openroad;TEST_NAME=upf_test;TEST_EXT=tcl;TEST_TYPE=tcl;TEST_CHECK_LOG=True;TEST_CHECK_PASSFAIL=False" LABELS "IntegrationTest tcl openroad log_compare" WORKING_DIRECTORY "/home/memzfs_projects/MLBuf_extension/OR_latest/test" _BACKTRACE_TRIPLES "/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;19;add_test;/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;86;or_integration_test_single;/home/memzfs_projects/MLBuf_extension/OR_latest/test/CMakeLists.txt;1;or_integration_tests;/home/memzfs_projects/MLBuf_extension/OR_latest/test/CMakeLists.txt;0;")
add_test(openroad.upf_aes.tcl "/usr/bin/bash" "/home/memzfs_projects/MLBuf_extension/OR_latest/test/regression_test.sh")
set_tests_properties(openroad.upf_aes.tcl PROPERTIES  ENVIRONMENT "OPENROAD_EXE=/home/memzfs_projects/MLBuf_extension/OR_latest/build/bin/openroad;TEST_NAME=upf_aes;TEST_EXT=tcl;TEST_TYPE=tcl;TEST_CHECK_LOG=True;TEST_CHECK_PASSFAIL=False" LABELS "IntegrationTest tcl openroad log_compare" WORKING_DIRECTORY "/home/memzfs_projects/MLBuf_extension/OR_latest/test" _BACKTRACE_TRIPLES "/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;19;add_test;/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;86;or_integration_test_single;/home/memzfs_projects/MLBuf_extension/OR_latest/test/CMakeLists.txt;1;or_integration_tests;/home/memzfs_projects/MLBuf_extension/OR_latest/test/CMakeLists.txt;0;")
add_test(openroad.write_db.tcl "/usr/bin/bash" "/home/memzfs_projects/MLBuf_extension/OR_latest/test/regression_test.sh")
set_tests_properties(openroad.write_db.tcl PROPERTIES  ENVIRONMENT "OPENROAD_EXE=/home/memzfs_projects/MLBuf_extension/OR_latest/build/bin/openroad;TEST_NAME=write_db;TEST_EXT=tcl;TEST_TYPE=tcl;TEST_CHECK_LOG=True;TEST_CHECK_PASSFAIL=False" LABELS "IntegrationTest tcl openroad log_compare" WORKING_DIRECTORY "/home/memzfs_projects/MLBuf_extension/OR_latest/test" _BACKTRACE_TRIPLES "/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;19;add_test;/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;86;or_integration_test_single;/home/memzfs_projects/MLBuf_extension/OR_latest/test/CMakeLists.txt;1;or_integration_tests;/home/memzfs_projects/MLBuf_extension/OR_latest/test/CMakeLists.txt;0;")
add_test(openroad.commands_without_load.tcl "/usr/bin/bash" "/home/memzfs_projects/MLBuf_extension/OR_latest/test/regression_test.sh")
set_tests_properties(openroad.commands_without_load.tcl PROPERTIES  ENVIRONMENT "OPENROAD_EXE=/home/memzfs_projects/MLBuf_extension/OR_latest/build/bin/openroad;TEST_NAME=commands_without_load;TEST_EXT=tcl;TEST_TYPE=tcl;TEST_CHECK_LOG=False;TEST_CHECK_PASSFAIL=True" LABELS "IntegrationTest tcl openroad passfail" WORKING_DIRECTORY "/home/memzfs_projects/MLBuf_extension/OR_latest/test" _BACKTRACE_TRIPLES "/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;19;add_test;/home/memzfs_projects/MLBuf_extension/OR_latest/src/cmake/testing.cmake;101;or_integration_test_single;/home/memzfs_projects/MLBuf_extension/OR_latest/test/CMakeLists.txt;1;or_integration_tests;/home/memzfs_projects/MLBuf_extension/OR_latest/test/CMakeLists.txt;0;")
