record_tests {
  buffer_ports1
  buffer_ports3
  buffer_ports4
  buffer_ports5
  buffer_ports6
  buffer_ports7
  buffer_ports8
  buffer_varying_lengths
  eqy_repair_setup2
  eqy_repair_setup5
  fanin_fanout1
  make_parasitics1
  make_parasitics2
  make_parasitics3
  make_parasitics4
  make_parasitics5
  make_parasitics6
  resize1
  resize4
  resize5
  resize6
  resize_slack1
  resize_slack2
  resize_slack3
  remove_buffers1
  remove_buffers2
  repair_clk_nets1
  repair_clk_inverters1
  repair_cap1
  repair_cap2
  repair_cap3
  repair_design1
  repair_design2
  repair_design3
  repair_design4
  repair_design5
  repair_fanout1
  repair_fanout2
  repair_fanout3
  repair_fanout4
  repair_fanout5
  repair_fanout6
  repair_fanout7
  repair_fanout8
  repair_hold1
  repair_hold2
  repair_hold3
  repair_hold4
  repair_hold5
  repair_hold6
  repair_hold7
  repair_hold8
  repair_hold9
  repair_hold10
  repair_hold11
  repair_hold12
  repair_hold13
  repair_hold14
  repair_setup1
  repair_setup2
  repair_setup3
  repair_setup4
  repair_setup5
  repair_setup6
  repair_slew1
  repair_slew2
  repair_slew3
  repair_slew4
  repair_slew5
  repair_slew6
  repair_slew7
  repair_slew8
  repair_slew9
  repair_slew10
  repair_slew11
  repair_slew12
  repair_slew13
  repair_slew14
  repair_slew15
  repair_slew16
  repair_slew17
  report_floating_nets1
  report_floating_nets2
  report_floating_nets3
  repair_tie1
  repair_tie2
  repair_tie3
  repair_tie4
  repair_tie5
  repair_tie6
  repair_tie7
  repair_tie8
  repair_wire1
  repair_wire2
  repair_wire3
  repair_wire4
  repair_wire5
  repair_wire6
  repair_wire7
  repair_wire8
  repair_wire9
  repair_wire10
  repair_wire11
  gcd_resize
  repair_design3_verbose
  repair_setup4_verbose
  repair_hold9_verbose
  set_dont_touch1
  set_dont_use1
}
