record_tests {
  make_parasitics1
  make_parasitics2
  make_parasitics3
  make_parasitics4
  make_parasitics5
  buffer_ports1
  buffer_ports3
  buffer_ports4
  buffer_ports5
  buffer_ports6
  resize1
  resize2
  resize3
  resize4
  resize5
  resize6
  resize_slack1
  resize_slack2
  remove_buffers1
  repair_clk_nets1
  repair_clk_inverters1
  repair_cap1
  repair_cap2
  repair_fanout1
  repair_fanout2
  repair_hold1
  repair_hold2
  repair_hold3
  repair_hold4
  repair_hold5
  repair_hold6
  repair_hold7
  repair_hold8
  repair_hold9
  repair_hold10
  repair_setup1
  repair_setup2
  repair_setup3
  repair_slew1
  repair_slew2
  repair_slew3
  repair_slew4
  repair_slew5
  repair_slew6
  report_floating_nets1
  repair_tie1
  repair_tie2
  repair_tie3
  repair_tie4
  repair_tie5
  repair_tie6
  repair_tie7
  repair_wire1
  repair_wire2
  repair_wire3
  repair_wire4
  repair_wire5
  repair_wire6
  gcd_resize
}
# injured reserve
#  repair_slew3

