if(EXISTS "/home/memzfs_projects/MLBuf_extension/OR_latest/build/src/mpl/test/cpp/TestSnapper[1]_tests.cmake")
  include("/home/memzfs_projects/MLBuf_extension/OR_latest/build/src/mpl/test/cpp/TestSnapper[1]_tests.cmake")
else()
  add_test(TestSnapper_NOT_BUILT TestSnapper_NOT_BUILT)
endif()
