record_tests {
  simple_test_hier
  array
  array_no_blockages
  array_ins_delay
  balance_levels
  check_buffers
  check_buffers_blockages
  check_charBuf
  check_max_fanout1
  check_max_fanout2
  check_wire_rc_cts
  dummy_load
  find_clock
  find_clock_pad
  insertion_delay
  max_cap
  no_clocks
  no_sinks
  post_cts_opt
  simple_test
  simple_test_clustered
  simple_test_clustered_max_cap
  lvt_lib
  #cts_readme_msgs_check
  #cts_man_tcl_check
}
