record_tests {
  check_buffers
  check_buffers_blockages
  check_charBuf
  find_clock
  find_clock_pad
  no_clocks
  no_sinks
  simple_test
  simple_test_clustered
  simple_test_clustered_max_cap
  check_wire_rc_cts
  post_cts_opt
  balance_levels
  max_cap
  array
  array_no_blockages
  array_ins_delay
  insertion_delay    
  dummy_load
}
