#!/bin/sh
make DEPENDOPT="-MM" CC4LIBS="g++" OPTFLAGS="-g -m64 -DABKDEBUG"  CCFLAGS="-fPIC -Wall -pedantic -pipe" C='gcc $(OPTFLAGS) $(CCFLAGS)' CC='g++ $(OPTFLAGS) $(CCFLAGS)' LD="g++ -shared -m64" LDFINAL="g++ -m64" SOLABEL="" SODIRKEY="-Wl,-rpath,"  $1 $2 $3 $4 $5
# SONAMEKEY="-Wl,-soname," 
