name: OpenROAD Bug report with OpenLane
description: File a bug report if you're running from OpenLane

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! It helps us more quickly track, narrow down, and address bugs.
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
        #### This part is incredibly important:

        Please run the following shell command in the OpenROAD root folder:
        ```
        ./etc/Env.sh
        ```
        Secondly, please run the following shell command in the OpenLane root folder:
        ```
        python3 ./env.py issue-survey
        ```
        Then copy and paste the ENTIRE output in the corresponding text fields below.

        *If the command **does not succeed**, you are using an out-of-date version of OpenROAD, and it is recommended that you update.*
  - type: textarea
    id: or-environment
    attributes:
      label: OpenROAD Environment
      render: shell
      description: Please paste the output from the previous command. It will be automatically formatted into code, so no need for backticks.
    validations:
      required: true
  - type: textarea
    id: ol-environment
    attributes:
      label: OpenLane Environment
      render: shell
      description: Please paste the output from the previous command. It will be automatically formatted into code, so no need for backticks.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
        #### To reproduce the bug: 
        ##### Please run the following shell command in the OpenLane root folder:
        ```
        python3 ./scripts/or_issue.py\
            --tool openroad\
            --script ./scripts/openroad/<script-name>\
            <run-path> # e.g designs/spm/runs/RUN_2022.03.01_19.21.10/tmp/routing/17-fill.def
            # run path is implicitly specified by input def
        ```
        *For more information, follow this link https://openlane.readthedocs.io/en/latest/for_developers/using_or_issue.html*

        ##### Otherwise, you can upload relevant files:

        &nbsp;&nbsp;&nbsp;&nbsp;- Upload a tar file containing the relevant files (.def, .lef and flow.tcl).

        &nbsp;&nbsp;&nbsp;&nbsp;- List the commands used.
  - type: textarea
    id: to-reproduce
    attributes:
      label: To Reproduce
    validations:
      required: true
  - type: markdown
    attributes:
      value: ---
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Feel free to add any relevant log snippets to this section. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, drag and drop screenshots to help explain your problem.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false