filegroup(
    name = "asap7_files",
    srcs = [
        "asap7sc7p5t_AO_RVT_TT_201020.v",
        "asap7sc7p5t_INVBUF_RVT_TT_201020.v",
        "asap7sc7p5t_OA_RVT_TT_201020.v",
        "asap7sc7p5t_SIMPLE_RVT_TT_201020.v",
        "@docker_orfs//:OpenROAD-flow-scripts/flow/platforms/asap7/verilog/stdcell/dff.v",
    ],
    visibility = ["//visibility:public"],
)
