ASAP7_VERILOG = [
    "asap7sc7p5t_AO_RVT_TT_201020.v",
    "asap7sc7p5t_INVBUF_RVT_TT_201020.v",
    "asap7sc7p5t_OA_RVT_TT_201020.v",
    "asap7sc7p5t_SIMPLE_RVT_TT_201020.v",
    "dff.v",
    "empty.v",
]

filegroup(
    name = "asap7_files",
    srcs = ASAP7_VERILOG,
    visibility = ["//visibility:public"],
)

exports_files(
    ASAP7_VERILOG,
    visibility = ["//visibility:public"],
)
