// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2026, The OpenROAD Authors

#include "syn/MakeSynthesis.h"

#include "tcl.h"
#include "utl/decode.h"

// Generated by swig from the synthesis.i
extern "C" {
extern int Syn_Init(Tcl_Interp* interp);
}

namespace syn {

// synthesis.tcl encoded as strings.
extern const char* syn_tcl_inits[];

void initSynthesis(Tcl_Interp* tcl_interp)
{
  // Define swig TCL commands.
  Syn_Init(tcl_interp);
  // Eval encoded TCL sources.
  utl::evalTclInit(tcl_interp, syn_tcl_inits);
}

}  // namespace syn
