load("@openroad_rules_python//python:defs.bzl", "py_binary")

py_binary(
    name = "file_to_string",
    srcs = [
        "file_to_string.py",
    ],
    main = "file_to_string.py",
    visibility = ["//visibility:public"],
)
