#!/bin/bash

set -e

cd "$(dirname $(readlink -f $0))/../"

_help() {
    cat <<EOF
usage: $0 [gcc]
       $0 clang
       $0 coverage
       $0 no-gui
EOF
    exit 1
}

if [[ "$#" -gt 0 ]]; then
    case "$@" in
        "coverage" )
            cmakeOptions="-DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=ON"
            ;;
        "no-gui" )
            cmakeOptions="-DBUILD_GUI=OFF"
            ;;
        "clang" )
            compiler="clang"
            ;;
        "gcc" )
            compiler="gcc"
            ;;
        *)
            echo "Option not recognized"
            _help
            ;;
    esac
fi

case "${compiler:-gcc}" in
    "gcc" )
        if [[ -f "/opt/rh/devtoolset-8/enable" ]]; then
            source /opt/rh/devtoolset-8/enable
        fi
        ;;
    "clang" )
        if [[ -f "/opt/rh/llvm-toolset-7.0/enable" ]]; then
            source /opt/rh/llvm-toolset-7.0/enable
            export CC=/opt/rh/llvm-toolset-7.0/root/usr/bin/clang
            export CXX=/opt/rh/llvm-toolset-7.0/root/usr/bin/clang++
        else
            export CC="$(command -v clang)"
            export CXX="$(command -v clang++)"
        fi
        ;;
    *)
        echo "Compiler $compiler is not supported"
        _help
esac

logName="openroad-build-$(date +%s).log"
cmake "$cmakeOptions" -B build . | tee "$logName"
time cmake --build build -j $(nproc) | tee -a "$logName"
mv "$logName" build/.
