#! /bin/sh
# The next line is executed by /bin/sh, but not Tcl \
exec tclsh $0 ${1+"$@"}

# Parallax Static Timing Analyzer
# Copyright (c) 2019, Parallax Software, Inc.
# All rights reserved.
# 
# No part of this document may be copied, transmitted or
# disclosed in any form or fashion without the express
# written consent of Parallax Software, Inc.

# Directory containing tests.
set test_dir [file dirname [info script]]
source [file join $test_dir find_parent_dir.tcl]
set sta_dir [find_parent_dir $test_dir]
source [file join $test_dir regression_vars.tcl]
source [file join $test_dir regression.tcl]

save_ok_main

# Local Variables:
# mode:tcl
# End:
