// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2025-2025, The OpenROAD Authors

#include "exa/MakeExample.h"

#include "tcl.h"
#include "utl/decode.h"

// Generated by swig from the example.i
extern "C" {
extern int Exa_Init(Tcl_Interp* interp);
}

namespace exa {

// example.tcl encoded as strings.
extern const char* exa_tcl_inits[];

void initExample(Tcl_Interp* tcl_interp)
{
  // Define swig TCL commands.
  Exa_Init(tcl_interp);
  // Eval encoded TCL sources.
  utl::evalTclInit(tcl_interp, exa_tcl_inits);
}

}  // namespace exa
