#!/bin/sh
make MAKE="./make-gnu" DEPENDOPT="-MM" CC4LIBS="g++" OPTFLAGS="-g -m64 -DABKDEBUG"  CCFLAGS="-fPIC -Wall -pedantic -pipe" CC='g++ $(OPTFLAGS) $(CCFLAGS)' LD="g++ -shared -m64" LDFINAL="g++ -m64" SOLABEL="" SODIRKEY="-Wl,-rpath," QLIBS="" $1 $2 $3 $4 $5
# SONAMEKEY="-Wl,-soname," 
