#!/bin/bash
set -x
set -e

cd "$(dirname $(readlink -f $0))/../"

for os in ubuntu20 centos7
do
    docker build -f "docker/Dockerfile.$os" --tag "openroad:$os" --target=base .
    for target in dev runner
    do
        docker build -f "docker/Dockerfile.$os" --tag "openroad:$os-$target" --target="$target" .
    done
done
