# create image with only dependencies
FROM centos:centos7 AS base
COPY ./etc/InstallDeps /tmp/
RUN /tmp/InstallDeps && rm -f /tmp/InstallDeps

# create image with dependencies + compiled app
FROM openroad:centos7 AS dev
ARG compiler=gcc
COPY . /OpenROAD
WORKDIR /OpenROAD
RUN ./etc/BuildHelper $compiler

# create image with dependencies + compiled app + run app automatically
FROM openroad:centos7-dev AS runner
ENTRYPOINT [ "/OpenROAD/build/src/openroad" ]
