# create image with dependencies needed to compile openroad app
# NOTE: don't use this file directly unless you know what you are doing,
# instead use etc/DockerHelper.sh
ARG fromImage=centos:centos7
FROM $fromImage

COPY DependencyInstaller.sh /tmp/.
RUN /tmp/DependencyInstaller.sh -dev && rm -f /tmp/DependencyInstaller.sh
