# create image with dependencies needed to compile openroad app
# NOTE: don't use this file directly unless you know what you are doing,
# instead use etc/DockerHelper.sh

# https://github.com/moby/moby/issues/38379#issuecomment-448445652
ARG fromImage=centos:centos7

FROM $fromImage

ARG INSTALLER_ARGS=""

COPY DependencyInstaller.sh /tmp/.

RUN /tmp/DependencyInstaller.sh -base
RUN /tmp/DependencyInstaller.sh -common $INSTALLER_ARGS
RUN rm -f /tmp/DependencyInstaller.sh
