# create image with all dependencies to compiler openroad app
# copy source code to the docker image and compile the app
# NOTE: don't use this file directly unless you know what you are doing,
# instead use etc/DockerHelper.sh

FROM openroad/ubuntu22.04-dev:latest

# Install clang
RUN apt-get install -y lsb-release wget software-properties-common gnupg \
      && wget https://apt.llvm.org/llvm.sh \
      && chmod +x llvm.sh \
      && ./llvm.sh 16 all \
      && rm llvm.sh
