#!/bin/bash
set -x
set -e

if [[ $# -ne 2 ]]; then
    echo "usage: $0 TARGET_OS TARGET_COMPILER"
    exit 1
fi

TARGET_OS="$1"
TARGET_COMPILER="$2"

DOCKER_TAG="openroad/${TARGET_OS}"

docker create
docker cp
docker start
docker exec "$DOCKER_TAG" bash -c "./jenkins/test.sh $TARGET_COMPILER"
docker stop
docker delete
