#define OPENROAD_GPU_COMPILED "${OPENROAD_GPU_COMPILED}"

#define OPENROAD_PYTHON_COMPILED "${OPENROAD_PYTHON_COMPILED}"

#define OPENROAD_GUI_COMPILED "${OPENROAD_GUI_COMPILED}"

#define OPENROAD_CHARTS_COMPILED "${OPENROAD_CHARTS_COMPILED}"