# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2025-2025, The OpenROAD Authors

load("@rules_python//python:defs.bzl", "py_binary")

py_binary(
    name = "compile_time",
    srcs = ["compile_time.py"],
    deps = [
        "@openroad-pip//matplotlib",
        "@openroad-pip//pyyaml",
    ],
)
