/* Generated by Yosys 0.9+4052 (git sha1 5c1e6a0e, clang 7.0.1 -fPIC -Os) */

module top(clk, c);
  input clk;
  output c;

  wire flop_net;
  wire _unconnected_;

  sky130_fd_sc_hd__conb_1 _403_ (
    .HI(flop_net),
    .LO(_unconnected_)
  );

  sky130_fd_sc_hd__dfxtp_1 output_flop (
    .D(flop_net),
    .Q(c),
    .CLK(clk)
  );

endmodule
