if(EXISTS "/home/memzfs_projects/MLBuf_extension/OR_latest/build/src/odb/test/cpp/scan/TestScanChain[1]_tests.cmake")
  include("/home/memzfs_projects/MLBuf_extension/OR_latest/build/src/odb/test/cpp/scan/TestScanChain[1]_tests.cmake")
else()
  add_test(TestScanChain_NOT_BUILT TestScanChain_NOT_BUILT)
endif()
