# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2026, The OpenROAD Authors

# Repository rules for the opt-in GPU build live in system_gpu.bzl;
# this package only exists to make that file loadable.
