# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2026, The OpenROAD Authors

"""Wrap the system CUDA toolkit used by the opt-in GPU build.

Kokkos and KokkosFFT are fetched and built from pinned source archives. The
CUDA toolkit is the only remaining host-provided build dependency. This rule
exposes its files through an execroot-relative symlink tree so clang sees only
declared inputs. An unusable toolkit becomes a stub that fails only when a GPU
target is analyzed; CPU builds remain unaffected.
"""

_CUDA_LOCAL_BUILD = """\
# Generated by //bazel/gpu:system_gpu.bzl — system CUDA toolkit at {root}.
load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "compiler_inputs",
    srcs = glob(
        [
            "bin/fatbinary",
            "bin/ptxas",
            "include/**",
            "nvvm/**",
            "version.json",
        ],
        allow_empty = True,
    ),
)

# Link the driver stub, but let the runtime loader find the real libcuda.so.1.
cc_library(
    name = "cudart",
    linkopts = [
        "-L{root}/{libdir}",
        "-Wl,-rpath,{root}/{libdir}",
        "-lcudart",
        "-L{root}/{libdir}/stubs",
        "-lcuda",
    ],
)

cc_library(
    name = "cufft",
    linkopts = [
        "-L{root}/{libdir}",
        "-lcufft",
    ],
    deps = [":cudart"],
)
"""

_MISSING_BZL = """\
def _missing_cuda_impl(ctx):
    fail(ctx.attr.message)

missing_cuda = rule(
    implementation = _missing_cuda_impl,
    attrs = {"message": attr.string(mandatory = True)},
)
"""

_STUB_BUILD = """\
# Generated by //bazel/gpu:system_gpu.bzl — stub: {reason}
load(":missing.bzl", "missing_cuda")

package(default_visibility = ["//visibility:public"])

missing_cuda(name = "compiler_inputs", message = {message})
missing_cuda(name = "cudart", message = {message})
missing_cuda(name = "cufft", message = {message})
"""

_REQUIRED_FILES = [
    ["include/cuda.h"],
    ["bin/ptxas"],
    ["nvvm/libdevice"],
    ["lib64/libcudart.so", "lib/libcudart.so"],
    ["lib64/libcufft.so", "lib/libcufft.so"],
]

def _prefix_problem(rctx, where, root):
    if not rctx.path(root).exists:
        return where + " does not exist"
    for alternatives in _REQUIRED_FILES:
        if not any([rctx.path(root + "/" + path).exists for path in alternatives]):
            return where + " is missing " + " or ".join(alternatives) + " (incomplete install?)"
    return None

def _write_stub(rctx, reason):
    message = (
        "GPU build is not usable: " + reason + ". Point OPENROAD_CUDA_PATH " +
        "at a full CUDA toolkit containing bin/ptxas, nvvm/libdevice, " +
        "libcudart, and libcufft."
    )
    rctx.file("missing.bzl", _MISSING_BZL)
    rctx.file(
        "BUILD.bazel",
        _STUB_BUILD.format(reason = reason, message = repr(message)),
    )

def _cuda_local_repository_impl(rctx):
    env_value = rctx.getenv("OPENROAD_CUDA_PATH")
    explicit = env_value != None
    root = env_value if explicit else rctx.attr.default_path
    where = (
        "OPENROAD_CUDA_PATH=" + root if explicit else "the default prefix " + root + " (OPENROAD_CUDA_PATH is unset)"
    )

    if explicit and not env_value.strip():
        problem = "OPENROAD_CUDA_PATH is set but empty"
    else:
        problem = _prefix_problem(rctx, where, root)

    if problem != None:
        _write_stub(rctx, problem)
    else:
        for entry in ["include", "lib", "lib64", "bin", "nvvm", "version.json"]:
            if rctx.path(root + "/" + entry).exists:
                rctx.symlink(root + "/" + entry, entry)
        libdir = "lib64" if rctx.path(root + "/lib64").exists else "lib"
        rctx.file(
            "BUILD.bazel",
            _CUDA_LOCAL_BUILD.replace("{root}", root).replace("{libdir}", libdir),
        )

    # Loaded unconditionally by bazel/gpu/copts.bzl, including CPU builds.
    rctx.file("defs.bzl", 'CUDA_PATH = "external/%s"\n' % rctx.name)

cuda_local_repository = repository_rule(
    implementation = _cuda_local_repository_impl,
    local = True,
    environ = ["OPENROAD_CUDA_PATH"],
    attrs = {
        "default_path": attr.string(mandatory = True),
    },
    doc = "Wraps a system CUDA toolkit without affecting default CPU builds.",
)
