# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2026, The OpenROAD Authors

"""Repository rules for the opt-in, non-hermetic GPU build (--config=gpu).

The GPU build compiles the Kokkos-based gpl backends (src/gpl/src/gpu)
with clang's native CUDA support against system-installed Kokkos,
KokkosFFT and CUDA toolkit — mirroring the CMake flow (ENABLE_GPU +
cmake/KokkosBackend.cmake), which also uses local installs.

system_prefix_repo wraps one system install prefix (Kokkos, KokkosFFT or
the CUDA toolkit) as an external repo. The prefix is taken from an
environment variable (forwarded with --repo_env by the build:gpu config)
with a fallback default. When the prefix does not exist the repo degrades
to an empty stub so that loading, querying and analyzing on CPU-only
machines and CI always works.

The cuda_local flavor additionally generates defs.bzl with the
--cuda-path/--cuda-gpu-arch values for clang's native CUDA mode. The
CUDA_PATH constant is the repo's own execroot-relative path (not the
absolute system path): the toolkit headers must reach the compiler
through the repo's symlink tree so that dependency-checking sees
declared, execroot-relative inputs instead of undeclared absolute paths.

Because the installs live outside Bazel's control, their contents are
undeclared inputs: after upgrading Kokkos or CUDA in place, re-run with
changed --repo_env values or `bazel shutdown` to refetch.

The hermetic LLVM toolchain builds against its bundled libc++, so the
Kokkos install referenced here must itself be built with clang and
-stdlib=libc++ (a Kokkos built with nvcc/g++ against libstdc++ does not
link). See docs for the build recipe.
"""

_KOKKOS_BUILD = """\
# Generated by //bazel/gpu:system_gpu.bzl — system Kokkos install at {root}.
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "kokkos",
    # Alphabetical glob order (algorithms, containers, core, simd) is a
    # valid link order: containers/algorithms precede core.
    srcs = glob(
        [
            "lib/libkokkos*.a",
            "lib64/libkokkos*.a",
        ],
        allow_empty = True,
    ),
    hdrs = glob(
        ["include/**"],
        allow_empty = True,
    ),
    includes = ["include"],
    linkopts = ["-ldl"],
    deps = ["@cuda_local//:cudart"],
)
"""

_KOKKOS_STUB_BUILD = """\
# Generated by //bazel/gpu:system_gpu.bzl — stub: no Kokkos install found.
package(default_visibility = ["//visibility:public"])

cc_library(name = "kokkos")
"""

_KOKKOS_FFT_BUILD = """\
# Generated by //bazel/gpu:system_gpu.bzl — system KokkosFFT install at {root}.
package(default_visibility = ["//visibility:public"])

# KokkosFFT is header-only; it dispatches to cuFFT for device-space
# plans and to the system FFTW for host-space plans (the install must be
# built with KokkosFFT_ENABLE_FFTW=ON — gpl's dct.cpp creates host plans).
cc_library(
    name = "kokkos_fft",
    hdrs = glob(
        ["include/**"],
        allow_empty = True,
    ),
    includes = ["include"],
    linkopts = [
        "-lfftw3",
        "-lfftw3f",
    ],
    deps = [
        "@cuda_local//:cufft",
        "@kokkos",
    ],
)
"""

_KOKKOS_FFT_STUB_BUILD = """\
# Generated by //bazel/gpu:system_gpu.bzl — stub: no KokkosFFT install found.
package(default_visibility = ["//visibility:public"])

cc_library(name = "kokkos_fft")
"""

_CUDA_LOCAL_BUILD = """\
# Generated by //bazel/gpu:system_gpu.bzl — system CUDA toolkit at {root}.
#
# Compile-side CUDA files (headers, libdevice, ptxas/fatbinary) are
# declared through :compiler_inputs and reached via the repo's symlink
# tree (--cuda-path points here, see defs.bzl). Linking uses the absolute
# system paths; the rpath lets libcudart/libcufft resolve at runtime
# without LD_LIBRARY_PATH (which Bazel's test environment scrubs);
# libcuda.so.1 comes from the driver in the default loader path.
package(default_visibility = ["//visibility:public"])

# Everything clang's CUDA mode reads or runs at compile time.
filegroup(
    name = "compiler_inputs",
    srcs = glob(
        [
            "bin/fatbinary",
            "bin/ptxas",
            "include/**",
            "nvvm/**",
            "version.json",
        ],
        allow_empty = True,
    ),
)

# The driver API (libcuda) links against the toolkit's stub — the stubs
# dir must NOT be in the rpath: at runtime the loader resolves the
# libcuda.so.1 soname to the real driver in the default search path.
cc_library(
    name = "cudart",
    linkopts = [
        "-L{root}/{libdir}",
        "-Wl,-rpath,{root}/{libdir}",
        "-lcudart",
        "-L{root}/{libdir}/stubs",
        "-lcuda",
    ],
)

cc_library(
    name = "cufft",
    linkopts = [
        "-L{root}/{libdir}",
        "-lcufft",
    ],
    deps = [":cudart"],
)
"""

_CUDA_LOCAL_STUB_BUILD = """\
# Generated by //bazel/gpu:system_gpu.bzl — stub: no CUDA toolkit found.
package(default_visibility = ["//visibility:public"])

filegroup(
    name = "compiler_inputs",
    srcs = [],
)

cc_library(name = "cudart")

cc_library(name = "cufft")
"""

_BUILD_TEMPLATES = {
    "cuda_local": _CUDA_LOCAL_BUILD,
    "kokkos": _KOKKOS_BUILD,
    "kokkos_fft": _KOKKOS_FFT_BUILD,
}

_STUB_TEMPLATES = {
    "cuda_local": _CUDA_LOCAL_STUB_BUILD,
    "kokkos": _KOKKOS_STUB_BUILD,
    "kokkos_fft": _KOKKOS_FFT_STUB_BUILD,
}

# Files that must exist under a real install prefix, per flavor. Each
# entry lists alternatives (any one satisfies the check). Failing fast at
# fetch time turns "half an install" into an actionable error instead of
# a confusing compile or link failure much later (e.g. a lib-less Kokkos
# prefix otherwise surfaces as undefined Kokkos symbols at final link —
# the same symptom as the libstdc++/libc++ ABI mismatch).
_REQUIRED_FILES = {
    "cuda_local": [
        ["include/cuda.h"],
        ["bin/ptxas"],
        ["nvvm/libdevice"],
        ["lib64/libcudart.so", "lib/libcudart.so"],
    ],
    "kokkos": [
        ["include/Kokkos_Core.hpp"],
        ["lib/libkokkoscore.a", "lib64/libkokkoscore.a"],
    ],
    "kokkos_fft": [
        ["include/KokkosFFT.hpp"],
    ],
}

def _check_required_files(rctx, root):
    for alternatives in _REQUIRED_FILES[rctx.attr.flavor]:
        found = False
        for alt in alternatives:
            if rctx.path(root + "/" + alt).exists:
                found = True
                break
        if not found:
            fail(("{flavor} install at {root} (from {var}) is missing " +
                  "{alts} — incomplete install?").format(
                flavor = rctx.attr.flavor,
                root = root,
                var = rctx.attr.env_var,
                alts = " or ".join(alternatives),
            ))

def _system_prefix_repo_impl(rctx):
    env_value = rctx.getenv(rctx.attr.env_var)
    root = env_value or rctx.attr.default_path
    if not rctx.path(root).exists:
        if env_value:
            # An explicitly-set path that does not exist is a user error;
            # degrading to a stub here would surface minutes later as a
            # misleading "header not found" compile error that never
            # mentions the variable.
            fail(("{var}={root} does not exist. Fix the path or unset " +
                  "{var} (it is read from the shell environment even " +
                  "without --config=gpu).").format(
                var = rctx.attr.env_var,
                root = root,
            ))
        rctx.file("BUILD.bazel", _STUB_TEMPLATES[rctx.attr.flavor])
    else:
        _check_required_files(rctx, root)
        for entry in ["include", "lib", "lib64", "bin", "nvvm", "version.json"]:
            if rctx.path(root + "/" + entry).exists:
                rctx.symlink(root + "/" + entry, entry)
        libdir = "lib64" if rctx.path(root + "/lib64").exists else "lib"
        build_content = _BUILD_TEMPLATES[rctx.attr.flavor]
        build_content = build_content.replace("{root}", root)
        build_content = build_content.replace("{libdir}", libdir)
        rctx.file("BUILD.bazel", build_content)
    if rctx.attr.flavor == "cuda_local":
        cuda_arch = rctx.getenv("OPENROAD_CUDA_ARCH") or "sm_120"
        rctx.file("defs.bzl", (
            '"""GPU compile configuration (generated by //bazel/gpu:system_gpu.bzl)."""\n' +
            "\n" +
            "CUDA_ARCH = %r\n" % cuda_arch +
            "\n" +
            "# Execroot-relative path of this repo's toolkit symlink tree.\n" +
            'CUDA_PATH = "external/%s"\n' % rctx.name
        ))

system_prefix_repo = repository_rule(
    implementation = _system_prefix_repo_impl,
    local = True,
    # rctx.getenv already registers these as dependencies, but declare them
    # explicitly so a changed prefix / arch always refetches the repo.
    environ = [
        "KOKKOS_ROOT",
        "KOKKOS_FFT_ROOT",
        "OPENROAD_CUDA_PATH",
        "OPENROAD_CUDA_ARCH",
    ],
    attrs = {
        "default_path": attr.string(
            doc = "Install prefix used when the environment variable is unset.",
            mandatory = True,
        ),
        "env_var": attr.string(
            doc = "Environment variable naming the install prefix " +
                  "(forward it with --repo_env, as build:gpu does).",
            mandatory = True,
        ),
        "flavor": attr.string(
            doc = "Which BUILD template to generate.",
            mandatory = True,
            values = ["cuda_local", "kokkos", "kokkos_fft"],
        ),
    },
    doc = "Wraps a system install prefix (headers + libs) as an external " +
          "repo, degrading to an empty stub when the prefix is missing.",
)
