# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2026, The OpenROAD Authors

"""Repository rules for the opt-in, non-hermetic GPU build (--config=gpu).

The GPU build compiles the Kokkos-based gpl backends (src/gpl/src/gpu)
with clang's native CUDA support against system-installed Kokkos,
KokkosFFT and CUDA toolkit — mirroring the CMake flow (ENABLE_GPU +
cmake/KokkosBackend.cmake), which also uses local installs.

system_prefix_repo wraps one system install prefix (Kokkos, KokkosFFT or
the CUDA toolkit) as an external repo. The prefix is taken from an
environment variable with a fallback default.

Fetching never fails. Whatever is wrong with a prefix — missing,
incomplete, a Kokkos built without the CUDA backend, an arch that does
not match OPENROAD_CUDA_ARCH — the repo degrades to a stub whose targets
fail at analysis time with a message naming the variable and the problem.
The default CPU build, CI, `bazel query` and downstream consumers are
therefore never affected by a stale KOKKOS_ROOT or a half-installed
toolkit (the stub targets are only reachable under --//:gpu=cuda), while
a --config=gpu build reports the misconfiguration before compiling
anything instead of as a "header not found" or undefined-symbol error
minutes later.

The kokkos flavor additionally generates defs.bzl with CUDA_ARCH, the
--cuda-gpu-arch value for clang's CUDA mode, read from the install's
KokkosCore_config.h (KOKKOS_ARCH_BLACKWELL120 -> sm_120). A Kokkos CUDA
build targets exactly one architecture and gpl's kernels must be compiled
for the same one: a mismatch is not a build error but silently wrong
numerics (sm_120 kernels on an sm_121 device diverge to NaN). If
OPENROAD_CUDA_ARCH is set it must agree with the install; it exists for
the case where the config header defines no recognizable arch macro.

The cuda_local flavor generates defs.bzl with CUDA_PATH, the repo's own
execroot-relative path (not the absolute system path): the toolkit
headers must reach the compiler through the repo's symlink tree so that
dependency-checking sees declared, execroot-relative inputs instead of
undeclared absolute paths.

The repo's file list is computed at fetch time. After upgrading Kokkos or
CUDA in place (new or renamed files) refetch with `bazel shutdown` or a
changed environment value; edits to existing files are seen normally.

The hermetic LLVM toolchain compiles against its bundled libc++ and links
against its own glibc-2.28 sysroot, so the Kokkos and KokkosFFT installs
referenced here must be built with that same compiler and header set: a
Kokkos built with nvcc/g++ against libstdc++, or with clang against the
host's glibc headers, does not link. The recipe is in docs/user/Bazel.md,
section "GPU build (--config=gpu)".
"""

_KOKKOS_BUILD = """\
# Generated by //bazel/gpu:system_gpu.bzl — system Kokkos install at {root}.
load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "kokkos",
    # Alphabetical glob order (algorithms, containers, core, simd) is a
    # valid link order: containers/algorithms precede core.
    srcs = glob(
        [
            "lib/libkokkos*.a",
            "lib64/libkokkos*.a",
        ],
        allow_empty = True,
    ),
    hdrs = glob(
        ["include/**"],
        allow_empty = True,
    ),
    includes = ["include"],
    # Kokkos_Core dlopen()s CUDA's profiling/tools hooks (KOKKOS_ENABLE_LIBDL).
    linkopts = ["-ldl"],
    deps = ["@cuda_local//:cudart"],
)
"""

_KOKKOS_FFT_BUILD = """\
# Generated by //bazel/gpu:system_gpu.bzl — system KokkosFFT install at {root}.
load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

# KokkosFFT is header-only; it dispatches to cuFFT for device-space plans
# and to FFTW for host-space plans (the install must be built with
# KokkosFFT_ENABLE_FFTW=ON — gpl's dct.cpp creates host plans). FFTW itself
# comes from the @fftw module rather than the host distribution: the
# hermetic toolchain links against its own sysroot, and a distro libfftw3
# built against a newer glibc does not resolve against it.
cc_library(
    name = "kokkos_fft",
    hdrs = glob(
        ["include/**"],
        allow_empty = True,
    ),
    includes = ["include"],
    deps = [
        "@cuda_local//:cufft",
        "@fftw",
        "@kokkos",
    ],
)
"""

_CUDA_LOCAL_BUILD = """\
# Generated by //bazel/gpu:system_gpu.bzl — system CUDA toolkit at {root}.
#
# Compile-side CUDA files (headers, libdevice, ptxas/fatbinary) are
# declared through :compiler_inputs and reached via the repo's symlink
# tree (--cuda-path points here, see defs.bzl). Linking uses the absolute
# system paths, so a --config=gpu binary is tied to this host's toolkit
# location; the rpath lets libcudart/libcufft resolve at runtime without
# LD_LIBRARY_PATH (which Bazel's test environment scrubs). libcuda.so.1
# comes from the driver in the default loader path.
load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

# Everything clang's CUDA mode reads or runs at compile time.
filegroup(
    name = "compiler_inputs",
    srcs = glob(
        [
            "bin/fatbinary",
            "bin/ptxas",
            "include/**",
            "nvvm/**",
            "version.json",
        ],
        allow_empty = True,
    ),
)

# The driver API (libcuda) links against the toolkit's stub — the stubs
# dir must NOT be in the rpath: at runtime the loader resolves the
# libcuda.so.1 soname to the real driver in the default search path.
cc_library(
    name = "cudart",
    linkopts = [
        "-L{root}/{libdir}",
        "-Wl,-rpath,{root}/{libdir}",
        "-lcudart",
        "-L{root}/{libdir}/stubs",
        "-lcuda",
    ],
)

cc_library(
    name = "cufft",
    linkopts = [
        "-L{root}/{libdir}",
        "-lcufft",
    ],
    deps = [":cudart"],
)
"""

_BUILD_TEMPLATES = {
    "cuda_local": _CUDA_LOCAL_BUILD,
    "kokkos": _KOKKOS_BUILD,
    "kokkos_fft": _KOKKOS_FFT_BUILD,
}

# Stub repos: every target the real BUILD would provide exists, but each
# one fails at analysis with the reason the prefix was rejected. Nothing on
# the default CPU build depends on them (see GPU_ONLY in defs.bzl), so the
# stub is inert there.
_MISSING_BZL = """\
# Generated by //bazel/gpu:system_gpu.bzl.
\"\"\"A target that fails at analysis time with an actionable message.\"\"\"

def _missing_gpu_prefix_impl(ctx):
    fail(ctx.attr.message)

missing_gpu_prefix = rule(
    implementation = _missing_gpu_prefix_impl,
    attrs = {"message": attr.string(mandatory = True)},
)
"""

_STUB_BUILD = """\
# Generated by //bazel/gpu:system_gpu.bzl — stub: {reason}
#
# Nothing here can be built. The default CPU build never analyzes these
# targets; a --config=gpu build fails at analysis with the message below.
load(":missing.bzl", "missing_gpu_prefix")

package(default_visibility = ["//visibility:public"])
{targets}"""

_STUB_TARGETS = {
    "cuda_local": ["compiler_inputs", "cudart", "cufft"],
    "kokkos": ["kokkos"],
    "kokkos_fft": ["kokkos_fft"],
}

_STUB_HINTS = {
    "cuda_local": "Point OPENROAD_CUDA_PATH at a full CUDA toolkit (one " +
                  "that includes the compiler files bin/ptxas and " +
                  "nvvm/libdevice, not a runtime-only install).",
    "kokkos": "Point KOKKOS_ROOT at a static Kokkos built with the CUDA " +
              "backend for this toolchain; see docs/user/Bazel.md, " +
              "section \"GPU build (--config=gpu)\", for the recipe.",
    "kokkos_fft": "Point KOKKOS_FFT_ROOT at a KokkosFFT install built " +
                  "against that Kokkos with KokkosFFT_ENABLE_FFTW=ON; " +
                  "see docs/user/Bazel.md, section \"GPU build " +
                  "(--config=gpu)\".",
}

# Files that must exist under a usable install prefix, per flavor. Each
# entry lists alternatives (any one satisfies the check). Checking at
# fetch time turns "half an install" into an actionable analysis error
# instead of a confusing compile or link failure much later (e.g. a
# lib-less Kokkos prefix otherwise surfaces as undefined Kokkos symbols at
# final link — the same symptom as the libstdc++/libc++ ABI mismatch).
_REQUIRED_FILES = {
    "cuda_local": [
        ["include/cuda.h"],
        ["bin/ptxas"],
        ["nvvm/libdevice"],
        ["lib64/libcudart.so", "lib/libcudart.so"],
    ],
    "kokkos": [
        ["include/Kokkos_Core.hpp"],
        ["include/KokkosCore_config.h"],
        ["lib/libkokkoscore.a", "lib64/libkokkoscore.a"],
    ],
    "kokkos_fft": [
        ["include/KokkosFFT.hpp"],
    ],
}

# NVIDIA entries of Kokkos_ARCH_*; the trailing digits are the compute
# capability (KOKKOS_ARCH_BLACKWELL121 -> sm_121). Family-only macros
# such as KOKKOS_ARCH_BLACKWELL carry no digits and are skipped.
_NVIDIA_ARCH_FAMILIES = [
    "KEPLER",
    "MAXWELL",
    "PASCAL",
    "VOLTA",
    "TURING",
    "AMPERE",
    "ADA",
    "HOPPER",
    "BLACKWELL",
]

def _prefix_problem(rctx, where, root):
    """Returns why `root` is unusable for this flavor, or None if it is."""
    if not rctx.path(root).exists:
        return where + " does not exist"
    for alternatives in _REQUIRED_FILES[rctx.attr.flavor]:
        found = False
        for alt in alternatives:
            if rctx.path(root + "/" + alt).exists:
                found = True
                break
        if not found:
            hint = " (incomplete install?)"
            if rctx.attr.flavor == "kokkos" and alternatives[0].endswith(".a"):
                hint = " (incomplete install, or a shared-library build; " + \
                       "Kokkos must be built with BUILD_SHARED_LIBS=OFF)"
            return where + " is missing " + " or ".join(alternatives) + hint
    return None

def _parse_kokkos_config(rctx, root):
    """Reads KokkosCore_config.h: (has_cuda, (arch_macro, sm_XX) or None)."""
    has_cuda = False
    arch = None
    for line in rctx.read(root + "/include/KokkosCore_config.h").splitlines():
        parts = [p for p in line.replace("\t", " ").split(" ") if p]
        if len(parts) < 2 or parts[0] != "#define":
            continue
        name = parts[1]
        if name == "KOKKOS_ENABLE_CUDA":
            has_cuda = True
        elif name.startswith("KOKKOS_ARCH_"):
            tail = name[len("KOKKOS_ARCH_"):]
            for family in _NVIDIA_ARCH_FAMILIES:
                digits = tail[len(family):]
                if tail.startswith(family) and digits.isdigit():
                    arch = (name, "sm_" + digits)
    return has_cuda, arch

def _kokkos_cuda_arch(rctx, where, root):
    """Returns (cuda_arch, problem); exactly one of the two is None."""
    has_cuda, arch = _parse_kokkos_config(rctx, root)
    if not has_cuda:
        return None, ("the Kokkos at " + root + " was built without the CUDA " +
                      "backend (KOKKOS_ENABLE_CUDA is not defined in " +
                      "include/KokkosCore_config.h)")
    env_arch = rctx.getenv("OPENROAD_CUDA_ARCH")
    if env_arch != None and env_arch.strip() == "":
        return None, "OPENROAD_CUDA_ARCH is set but empty"
    if arch != None:
        if env_arch != None and env_arch != arch[1]:
            return None, ("OPENROAD_CUDA_ARCH=" + env_arch + " does not match " +
                          where + ", which was built for " + arch[1] + " (" +
                          arch[0] + "); unset OPENROAD_CUDA_ARCH or rebuild " +
                          "Kokkos for the device you have")
        return arch[1], None
    if env_arch != None:
        return env_arch, None
    return None, ("include/KokkosCore_config.h under " + where + " defines " +
                  "no KOKKOS_ARCH_<NVIDIA arch> macro, so the compute " +
                  "capability is unknown; set OPENROAD_CUDA_ARCH (e.g. sm_120)")

def _write_stub(rctx, reason):
    message = ("GPU build (--config=gpu) is not usable: " + reason + ". " +
               _STUB_HINTS[rctx.attr.flavor])
    targets = ""
    for name in _STUB_TARGETS[rctx.attr.flavor]:
        targets += ("\nmissing_gpu_prefix(\n    name = %r,\n    message = %r,\n)\n" %
                    (name, message))
    rctx.file("missing.bzl", _MISSING_BZL)
    rctx.file("BUILD.bazel", _STUB_BUILD.format(reason = reason, targets = targets))

def _system_prefix_repo_impl(rctx):
    var = rctx.attr.env_var
    env_value = rctx.getenv(var)
    explicit = env_value != None
    root = env_value if explicit else rctx.attr.default_path
    if explicit:
        where = var + "=" + root
    else:
        where = "the default prefix " + root + " (" + var + " is unset)"

    cuda_arch = None
    if explicit and env_value.strip() == "":
        problem = var + " is set but empty"
    else:
        problem = _prefix_problem(rctx, where, root)
    if problem == None and rctx.attr.flavor == "kokkos":
        cuda_arch, problem = _kokkos_cuda_arch(rctx, where, root)

    if problem != None:
        _write_stub(rctx, problem)
    else:
        for entry in ["include", "lib", "lib64", "bin", "nvvm", "version.json"]:
            if rctx.path(root + "/" + entry).exists:
                rctx.symlink(root + "/" + entry, entry)
        libdir = "lib64" if rctx.path(root + "/lib64").exists else "lib"
        build_content = _BUILD_TEMPLATES[rctx.attr.flavor]
        build_content = build_content.replace("{root}", root)
        build_content = build_content.replace("{libdir}", libdir)
        rctx.file("BUILD.bazel", build_content)

    # defs.bzl is loaded unconditionally (bazel/gpu/copts.bzl), so it must
    # exist for stubs too. An empty CUDA_ARCH means "stub": copts.bzl then
    # emits no --cuda-gpu-arch, which is fine because analysis fails on the
    # stub target before any CUDA translation unit is compiled.
    if rctx.attr.flavor == "kokkos":
        rctx.file("defs.bzl", (
            '"""CUDA target architecture (generated by //bazel/gpu:system_gpu.bzl)."""\n' +
            "\n" +
            "# From KokkosCore_config.h of the wrapped install; \"\" when the repo is a stub.\n" +
            "CUDA_ARCH = %r\n" % (cuda_arch or "")
        ))
    if rctx.attr.flavor == "cuda_local":
        rctx.file("defs.bzl", (
            '"""CUDA toolkit location (generated by //bazel/gpu:system_gpu.bzl)."""\n' +
            "\n" +
            "# Execroot-relative path of this repo's toolkit symlink tree. Assumes\n" +
            "# the default external/<canonical repo name> execroot layout.\n" +
            'CUDA_PATH = "external/%s"\n' % rctx.name
        ))

system_prefix_repo = repository_rule(
    implementation = _system_prefix_repo_impl,
    local = True,
    # rctx.getenv already registers these as dependencies, but declare them
    # explicitly so a changed prefix / arch always refetches the repo.
    environ = [
        "KOKKOS_ROOT",
        "KOKKOS_FFT_ROOT",
        "OPENROAD_CUDA_PATH",
        "OPENROAD_CUDA_ARCH",
    ],
    attrs = {
        "default_path": attr.string(
            doc = "Install prefix used when the environment variable is unset.",
            mandatory = True,
        ),
        "env_var": attr.string(
            doc = "Environment variable naming the install prefix (read " +
                  "from the shell environment that invokes bazel).",
            mandatory = True,
        ),
        "flavor": attr.string(
            doc = "Which BUILD template to generate.",
            mandatory = True,
            values = ["cuda_local", "kokkos", "kokkos_fft"],
        ),
    },
    doc = "Wraps a system install prefix (headers + libs) as an external " +
          "repo. An unusable prefix yields a stub whose targets fail at " +
          "analysis with the reason, so only --config=gpu builds notice.",
)
