# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2026, The OpenROAD Authors

"""Assemble the CMake dependency prefix from a manifest.

Executed as a bazel action by the cmake_deps_bundle rule in defs.bzl.
Copies files and directories into the output tree, deduplicating large
files that resolve to the same inode by relative symlinks (the hermetic
LLVM distribution multiplexes every tool into one ~190 MB binary reached
through symlinks; copying it once per tool name would multiply the bundle
size), writes the generated wrapper scripts and CMake include files, and
renders toolchain.cmake from its template.
"""

import filecmp
import json
import os
import re
import shutil
import stat
import sys

# Files at least this large are deduplicated via relative symlinks when
# several destinations resolve to the same underlying file.
DEDUP_THRESHOLD_BYTES = 1024 * 1024


class Assembler:
    def __init__(self, out_root):
        self.out_root = out_root
        # (st_dev, st_ino) -> first destination path, for large files.
        self.seen_inodes = {}

    def copy_file(self, src, dest):
        os.makedirs(os.path.dirname(dest), exist_ok=True)
        if os.path.lexists(dest):
            if filecmp.cmp(src, dest, shallow=False):
                return
            raise SystemExit(
                f"error: destination collision with differing contents: "
                f"{dest} (from {src})"
            )
        st = os.stat(src)
        key = (st.st_dev, st.st_ino)
        if st.st_size >= DEDUP_THRESHOLD_BYTES:
            first = self.seen_inodes.get(key)
            if first is not None:
                target = os.path.relpath(first, os.path.dirname(dest))
                os.symlink(target, dest)
                return
            self.seen_inodes[key] = dest
        shutil.copyfile(src, dest)
        os.chmod(dest, st.st_mode & 0o777 | stat.S_IWUSR)

    def copy_tree(self, src, dest):
        for root, _, files in os.walk(src, followlinks=True):
            rel = os.path.relpath(root, src)
            for name in files:
                self.copy_file(
                    os.path.join(root, name),
                    os.path.normpath(os.path.join(dest, rel, name)),
                )

    def copy(self, src, dest):
        if os.path.isdir(src):
            self.copy_tree(src, dest)
        else:
            self.copy_file(src, dest)

    def write(self, dest, content, executable):
        os.makedirs(os.path.dirname(dest), exist_ok=True)
        with open(dest, "w", encoding="utf-8") as f:
            f.write(content)
        os.chmod(dest, 0o755 if executable else 0o644)


def parse_versions(module_bazel_path):
    """Dependency versions from MODULE.bazel, .bcr suffixes stripped.

    Matches each bazel_dep(...) block as a whole, so argument order and
    buildifier's line wrapping do not matter.
    """
    with open(module_bazel_path, encoding="utf-8") as f:
        text = f.read()
    versions = {}
    variables = dict(
        re.findall(r'^\s*(\w+)\s*=\s*["\']([^"\']+)["\']', text, re.MULTILINE)
    )
    for block in re.findall(r"bazel_dep\s*\(([^)]+)\)", text, re.DOTALL):
        name_match = re.search(r'name\s*=\s*["\']([^"\']+)["\']', block)
        version_match = re.search(r'version\s*=\s*(["\'][^"\']+["\']|\w+)', block)
        if not name_match or not version_match:
            continue
        version = version_match.group(1)
        if version[0] in "\"'":
            version = version.strip("\"'")
        else:
            version = variables.get(version, "")
        versions[name_match.group(1)] = version.split(".bcr.")[0]
    for name, version in list(versions.items()):
        if name.startswith("boost."):
            versions.setdefault("boost", version)
    return versions


def versions_cmake(versions):
    lines = ["# Generated by //cmake-deps from MODULE.bazel."]
    for name, version in sorted(versions.items()):
        variable = re.sub(r"[^A-Za-z0-9]", "_", name)
        lines.append(f'set(OPENROAD_DEPS_VERSION_{variable} "{version}")')
    return "\n".join(lines) + "\n"


def main():
    manifest_path, out_root = sys.argv[1], sys.argv[2]
    with open(manifest_path, encoding="utf-8") as f:
        manifest = json.load(f)

    assembler = Assembler(out_root)
    for entry in manifest["copies"]:
        assembler.copy(entry["src"], os.path.join(out_root, entry["dest"]))

    for entry in manifest["writes"]:
        assembler.write(
            os.path.join(out_root, entry["dest"]),
            entry["content"],
            entry["executable"],
        )

    versions = parse_versions(manifest["module_bazel"])
    assembler.write(
        os.path.join(out_root, manifest["versions_dest"]),
        versions_cmake(versions),
        executable=False,
    )

    with open(manifest["template_src"], encoding="utf-8") as f:
        template = f.read()
    for key, value in manifest["substitutions"].items():
        template = template.replace(key, value)
    unresolved = re.findall(r"@[A-Z_]+@", template)
    if unresolved:
        raise SystemExit(f"error: unresolved template keys: {unresolved}")
    assembler.write(
        os.path.join(out_root, manifest["template_dest"]),
        template,
        executable=False,
    )


if __name__ == "__main__":
    main()
