# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2025, The OpenROAD Authors

package(
    default_visibility = ["//:__subpackages__"],
    features = ["layering_check"],
)

filegroup(
    name = "lef-test-data",
    srcs = [
        "sky130_fd_sc_hd.tlef",
        "sky130_fd_sc_hd__tt_025C_1v80.lib",
        "sky130_fd_sc_hd_merged.lef",
        "sky130hd_multi_patterned.tlef",
    ],
)
