global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []  # Keep this as is, or add your Alertmanager targets if you have any.
      scheme: http  # This is already correct
      timeout: 10s    # This is also fine
      api_version: v2  # Changed from v1 to v2
      path_prefix: /   # ADD THIS - Required for v2

scrape_configs:
  - job_name: prometheus
    honor_timestamps: true  # This section is all good as is.
    scrape_interval: 5s
    scrape_timeout: 3s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9090
          - host.docker.internal:8080
