# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.0
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError('Python 2.7 or later required')

# Import the low-level C/C++ module
if __package__ or '.' in __name__:
    from . import _grt_py
else:
    import _grt_py

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if name == "thisown":
        return self.this.own(value)
    if name == "this":
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if not static:
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if name == "thisown":
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class RegionAdjustment(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    region = property(_grt_py.RegionAdjustment_region_get, _grt_py.RegionAdjustment_region_set)
    layer = property(_grt_py.RegionAdjustment_layer_get, _grt_py.RegionAdjustment_layer_set)
    adjustment = property(_grt_py.RegionAdjustment_adjustment_get, _grt_py.RegionAdjustment_adjustment_set)

    def __init__(self, min_x, min_y, max_x, max_y, l, adjst):
        _grt_py.RegionAdjustment_swiginit(self, _grt_py.new_RegionAdjustment(min_x, min_y, max_x, max_y, l, adjst))

    def getRegion(self):
        return _grt_py.RegionAdjustment_getRegion(self)

    def getLayer(self):
        return _grt_py.RegionAdjustment_getLayer(self)

    def getAdjustment(self):
        return _grt_py.RegionAdjustment_getAdjustment(self)
    __swig_destroy__ = _grt_py.delete_RegionAdjustment

# Register RegionAdjustment in _grt_py:
_grt_py.RegionAdjustment_swigregister(RegionAdjustment)

class RoutePointPins(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    pins = property(_grt_py.RoutePointPins_pins_get, _grt_py.RoutePointPins_pins_set)
    connected = property(_grt_py.RoutePointPins_connected_get, _grt_py.RoutePointPins_connected_set)

    def __init__(self):
        _grt_py.RoutePointPins_swiginit(self, _grt_py.new_RoutePointPins())
    __swig_destroy__ = _grt_py.delete_RoutePointPins

# Register RoutePointPins in _grt_py:
_grt_py.RoutePointPins_swigregister(RoutePointPins)

NetType_Clock = _grt_py.NetType_Clock
NetType_Signal = _grt_py.NetType_Signal
NetType_Antenna = _grt_py.NetType_Antenna
NetType_All = _grt_py.NetType_All
class GlobalRouter(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, logger, callback_handler, stt_builder, db, sta, antenna_checker, opendp):
        _grt_py.GlobalRouter_swiginit(self, _grt_py.new_GlobalRouter(logger, callback_handler, stt_builder, db, sta, antenna_checker, opendp))
    __swig_destroy__ = _grt_py.delete_GlobalRouter

    def clear(self):
        return _grt_py.GlobalRouter_clear(self)

    def setAdjustment(self, adjustment):
        return _grt_py.GlobalRouter_setAdjustment(self, adjustment)

    def setMinRoutingLayer(self, min_layer):
        return _grt_py.GlobalRouter_setMinRoutingLayer(self, min_layer)

    def setMaxRoutingLayer(self, max_layer):
        return _grt_py.GlobalRouter_setMaxRoutingLayer(self, max_layer)

    def getMinRoutingLayer(self):
        return _grt_py.GlobalRouter_getMinRoutingLayer(self)

    def getMaxRoutingLayer(self):
        return _grt_py.GlobalRouter_getMaxRoutingLayer(self)

    def setMinLayerForClock(self, min_layer):
        return _grt_py.GlobalRouter_setMinLayerForClock(self, min_layer)

    def setMaxLayerForClock(self, max_layer):
        return _grt_py.GlobalRouter_setMaxLayerForClock(self, max_layer)

    def getMinLayerForClock(self):
        return _grt_py.GlobalRouter_getMinLayerForClock(self)

    def getMaxLayerForClock(self):
        return _grt_py.GlobalRouter_getMaxLayerForClock(self)

    def setCriticalNetsPercentage(self, critical_nets_percentage):
        return _grt_py.GlobalRouter_setCriticalNetsPercentage(self, critical_nets_percentage)

    def addLayerAdjustment(self, layer, reduction_percentage):
        return _grt_py.GlobalRouter_addLayerAdjustment(self, layer, reduction_percentage)

    def addRegionAdjustment(self, min_x, min_y, max_x, max_y, layer, reduction_percentage):
        return _grt_py.GlobalRouter_addRegionAdjustment(self, min_x, min_y, max_x, max_y, layer, reduction_percentage)

    def setVerbose(self, v):
        return _grt_py.GlobalRouter_setVerbose(self, v)

    def setCongestionIterations(self, iterations):
        return _grt_py.GlobalRouter_setCongestionIterations(self, iterations)

    def setCongestionReportIterStep(self, congestion_report_iter_step):
        return _grt_py.GlobalRouter_setCongestionReportIterStep(self, congestion_report_iter_step)

    def setCongestionReportFile(self, file_name):
        return _grt_py.GlobalRouter_setCongestionReportFile(self, file_name)

    def setGridOrigin(self, x, y):
        return _grt_py.GlobalRouter_setGridOrigin(self, x, y)

    def setAllowCongestion(self, allow_congestion):
        return _grt_py.GlobalRouter_setAllowCongestion(self, allow_congestion)

    def setResistanceAware(self, resistance_aware):
        return _grt_py.GlobalRouter_setResistanceAware(self, resistance_aware)

    def setMacroExtension(self, macro_extension):
        return _grt_py.GlobalRouter_setMacroExtension(self, macro_extension)

    def setUseCUGR(self, use_cugr):
        return _grt_py.GlobalRouter_setUseCUGR(self, use_cugr)

    def readGuides(self, file_name):
        return _grt_py.GlobalRouter_readGuides(self, file_name)

    def loadGuidesFromDB(self):
        return _grt_py.GlobalRouter_loadGuidesFromDB(self)

    def ensurePinsPositions(self, db_net):
        return _grt_py.GlobalRouter_ensurePinsPositions(self, db_net)

    def saveGuidesFromFile(self, guides):
        return _grt_py.GlobalRouter_saveGuidesFromFile(self, guides)

    def saveGuides(self, nets):
        return _grt_py.GlobalRouter_saveGuides(self, nets)

    def writeSegments(self, file_name):
        return _grt_py.GlobalRouter_writeSegments(self, file_name)

    def readSegments(self, file_name):
        return _grt_py.GlobalRouter_readSegments(self, file_name)

    def netIsCovered(self, db_net, pins_not_covered):
        return _grt_py.GlobalRouter_netIsCovered(self, db_net, pins_not_covered)

    def segmentIsLine(self, segment):
        return _grt_py.GlobalRouter_segmentIsLine(self, segment)

    def segmentCoversPin(self, segment, pin):
        return _grt_py.GlobalRouter_segmentCoversPin(self, segment, pin)

    def buildNetGraph(self, net):
        return _grt_py.GlobalRouter_buildNetGraph(self, net)

    def isConnected(self, net):
        return _grt_py.GlobalRouter_isConnected(self, net)

    def segmentsConnect(self, segment1, segment2):
        return _grt_py.GlobalRouter_segmentsConnect(self, segment1, segment2)

    def isCoveringPin(self, net, segment):
        return _grt_py.GlobalRouter_isCoveringPin(self, net, segment)

    def initFastRoute(self, min_routing_layer, max_routing_layer):
        return _grt_py.GlobalRouter_initFastRoute(self, min_routing_layer, max_routing_layer)

    def initFastRouteIncr(self, nets):
        return _grt_py.GlobalRouter_initFastRouteIncr(self, nets)

    def routeLayerLengths(self, db_net):
        return _grt_py.GlobalRouter_routeLayerLengths(self, db_net)

    def globalRoute(self, save_guides=False, start_incremental=False, end_incremental=False):
        return _grt_py.GlobalRouter_globalRoute(self, save_guides, start_incremental, end_incremental)

    def saveCongestion(self):
        return _grt_py.GlobalRouter_saveCongestion(self)

    def getRoutes(self):
        return _grt_py.GlobalRouter_getRoutes(self)

    def getNet(self, db_net):
        return _grt_py.GlobalRouter_getNet(self, db_net)

    def getTileSize(self):
        return _grt_py.GlobalRouter_getTileSize(self)

    def isNonLeafClock(self, db_net):
        return _grt_py.GlobalRouter_isNonLeafClock(self, db_net)

    def hasAvailableResources(self, is_horizontal, pos_x, pos_y, layer_level, db_net):
        return _grt_py.GlobalRouter_hasAvailableResources(self, is_horizontal, pos_x, pos_y, layer_level, db_net)

    def getPositionOnGrid(self, real_position):
        return _grt_py.GlobalRouter_getPositionOnGrid(self, real_position)

    def repairAntennas(self, diode_mterm, iterations, ratio_margin, num_threads=1):
        return _grt_py.GlobalRouter_repairAntennas(self, diode_mterm, iterations, ratio_margin, num_threads)

    def updateResources(self, init_x, init_y, final_x, final_y, layer_level, used, db_net):
        return _grt_py.GlobalRouter_updateResources(self, init_x, init_y, final_x, final_y, layer_level, used, db_net)

    def updateFastRouteGridsLayer(self, init_x, init_y, final_x, final_y, layer_level, new_layer_level, db_net):
        return _grt_py.GlobalRouter_updateFastRouteGridsLayer(self, init_x, init_y, final_x, final_y, layer_level, new_layer_level, db_net)

    def addDirtyNet(self, net):
        return _grt_py.GlobalRouter_addDirtyNet(self, net)

    def getDirtyNets(self):
        return _grt_py.GlobalRouter_getDirtyNets(self)

    def haveRoutes(self):
        return _grt_py.GlobalRouter_haveRoutes(self)

    def designIsPlaced(self):
        return _grt_py.GlobalRouter_designIsPlaced(self)

    def haveDetailedRoutes(self, *args):
        return _grt_py.GlobalRouter_haveDetailedRoutes(self, *args)

    def addNetToRoute(self, db_net):
        return _grt_py.GlobalRouter_addNetToRoute(self, db_net)

    def getNetsToRoute(self):
        return _grt_py.GlobalRouter_getNetsToRoute(self)

    def mergeNetsRouting(self, db_net1, db_net2):
        return _grt_py.GlobalRouter_mergeNetsRouting(self, db_net1, db_net2)

    def connectRouting(self, db_net1, db_net2):
        return _grt_py.GlobalRouter_connectRouting(self, db_net1, db_net2)

    def findBufferPinPostions(self, net1, net2, pin_pos1, pin_pos2):
        return _grt_py.GlobalRouter_findBufferPinPostions(self, net1, net2, pin_pos1, pin_pos2)

    def findTopLayerOverPosition(self, pin_pos, route):
        return _grt_py.GlobalRouter_findTopLayerOverPosition(self, pin_pos, route)

    def createConnectionForPositions(self, pin_pos1, pin_pos2, layer1, layer2):
        return _grt_py.GlobalRouter_createConnectionForPositions(self, pin_pos1, pin_pos2, layer1, layer2)

    def insertViasForConnection(self, connection, via_pos, layer, conn_layer):
        return _grt_py.GlobalRouter_insertViasForConnection(self, connection, via_pos, layer, conn_layer)

    def getBlockage(self, layer, x, y, blockage_h, blockage_v):
        return _grt_py.GlobalRouter_getBlockage(self, layer, x, y, blockage_h, blockage_v)

    def setSeed(self, seed):
        return _grt_py.GlobalRouter_setSeed(self, seed)

    def setCapacitiesPerturbationPercentage(self, percentage):
        return _grt_py.GlobalRouter_setCapacitiesPerturbationPercentage(self, percentage)

    def setPerturbationAmount(self, perturbation):
        return _grt_py.GlobalRouter_setPerturbationAmount(self, perturbation)

    def perturbCapacities(self):
        return _grt_py.GlobalRouter_perturbCapacities(self)

    def setDebugNet(self, net):
        return _grt_py.GlobalRouter_setDebugNet(self, net)

    def setDebugSteinerTree(self, steinerTree):
        return _grt_py.GlobalRouter_setDebugSteinerTree(self, steinerTree)

    def setDebugRectilinearSTree(self, rectilinearSTree):
        return _grt_py.GlobalRouter_setDebugRectilinearSTree(self, rectilinearSTree)

    def setDebugTree2D(self, tree2D):
        return _grt_py.GlobalRouter_setDebugTree2D(self, tree2D)

    def setDebugTree3D(self, tree3D):
        return _grt_py.GlobalRouter_setDebugTree3D(self, tree3D)

    def setSttInputFilename(self, file_name):
        return _grt_py.GlobalRouter_setSttInputFilename(self, file_name)

    def saveSttInputFile(self, net):
        return _grt_py.GlobalRouter_saveSttInputFile(self, net)

    def reportNetLayerWirelengths(self, db_net, out):
        return _grt_py.GlobalRouter_reportNetLayerWirelengths(self, db_net, out)

    def reportLayerWireLengths(self, global_route, detailed_route):
        return _grt_py.GlobalRouter_reportLayerWireLengths(self, global_route, detailed_route)

    def globalRoutingToBox(self, route):
        return _grt_py.GlobalRouter_globalRoutingToBox(self, route)

    def boxToGlobalRouting(self, route_bds, layer, via_layer, route):
        return _grt_py.GlobalRouter_boxToGlobalRouting(self, route_bds, layer, via_layer, route)

    def updateVias(self):
        return _grt_py.GlobalRouter_updateVias(self)

    def reportNetWireLength(self, net, global_route, detailed_route, verbose, file_name):
        return _grt_py.GlobalRouter_reportNetWireLength(self, net, global_route, detailed_route, verbose, file_name)

    def reportNetDetailedRouteWL(self, wire, out):
        return _grt_py.GlobalRouter_reportNetDetailedRouteWL(self, wire, out)

    def createWLReportFile(self, file_name, verbose):
        return _grt_py.GlobalRouter_createWLReportFile(self, file_name, verbose)

    def getPinGridPositions(self, db_net):
        return _grt_py.GlobalRouter_getPinGridPositions(self, db_net)

    def findPinAccessPointPositions(self, pin, ap_positions):
        return _grt_py.GlobalRouter_findPinAccessPointPositions(self, pin, ap_positions)

    def getNetLayerRange(self, db_net, min_layer, max_layer):
        return _grt_py.GlobalRouter_getNetLayerRange(self, db_net, min_layer, max_layer)

    def getGridSize(self, x_grids, y_grids):
        return _grt_py.GlobalRouter_getGridSize(self, x_grids, y_grids)

    def getGridTileSize(self):
        return _grt_py.GlobalRouter_getGridTileSize(self)

    def getMinMaxLayer(self, min_layer, max_layer):
        return _grt_py.GlobalRouter_getMinMaxLayer(self, min_layer, max_layer)

    def getCapacityReductionData(self, cap_red_data):
        return _grt_py.GlobalRouter_getCapacityReductionData(self, cap_red_data)

    def isInitialized(self):
        return _grt_py.GlobalRouter_isInitialized(self)

    def isCongested(self):
        return _grt_py.GlobalRouter_isCongested(self)

    def setDbBlock(self, block):
        return _grt_py.GlobalRouter_setDbBlock(self, block)

    def getRenderer(self):
        return _grt_py.GlobalRouter_getRenderer(self)

    def db(self):
        return _grt_py.GlobalRouter_db(self)

    def fastroute(self):
        return _grt_py.GlobalRouter_fastroute(self)

    def getRudy(self):
        return _grt_py.GlobalRouter_getRudy(self)

    def writePinLocations(self, file_name):
        return _grt_py.GlobalRouter_writePinLocations(self, file_name)

# Register GlobalRouter in _grt_py:
_grt_py.GlobalRouter_swigregister(GlobalRouter)


def getITermName(iterm):
    return _grt_py.getITermName(iterm)

def getLayerName(layer_idx, db):
    return _grt_py.getLayerName(layer_idx, db)
class GRouteDbCbk(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, grouter):
        _grt_py.GRouteDbCbk_swiginit(self, _grt_py.new_GRouteDbCbk(grouter))

    def inDbPostMoveInst(self, inst):
        return _grt_py.GRouteDbCbk_inDbPostMoveInst(self, inst)

    def inDbInstSwapMasterAfter(self, inst):
        return _grt_py.GRouteDbCbk_inDbInstSwapMasterAfter(self, inst)

    def inDbNetDestroy(self, net):
        return _grt_py.GRouteDbCbk_inDbNetDestroy(self, net)

    def inDbNetCreate(self, net):
        return _grt_py.GRouteDbCbk_inDbNetCreate(self, net)

    def inDbNetPreMerge(self, preserved_net, removed_net):
        return _grt_py.GRouteDbCbk_inDbNetPreMerge(self, preserved_net, removed_net)

    def inDbITermPreDisconnect(self, iterm):
        return _grt_py.GRouteDbCbk_inDbITermPreDisconnect(self, iterm)

    def inDbITermPostConnect(self, iterm):
        return _grt_py.GRouteDbCbk_inDbITermPostConnect(self, iterm)

    def inDbITermPostSetAccessPoints(self, iterm):
        return _grt_py.GRouteDbCbk_inDbITermPostSetAccessPoints(self, iterm)

    def inDbBTermPostConnect(self, bterm):
        return _grt_py.GRouteDbCbk_inDbBTermPostConnect(self, bterm)

    def inDbBTermPreDisconnect(self, bterm):
        return _grt_py.GRouteDbCbk_inDbBTermPreDisconnect(self, bterm)
    __swig_destroy__ = _grt_py.delete_GRouteDbCbk

# Register GRouteDbCbk in _grt_py:
_grt_py.GRouteDbCbk_swigregister(GRouteDbCbk)

class IncrementalGRoute(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, groute, block):
        _grt_py.IncrementalGRoute_swiginit(self, _grt_py.new_IncrementalGRoute(groute, block))

    def updateRoutes(self, save_guides=False):
        return _grt_py.IncrementalGRoute_updateRoutes(self, save_guides)
    __swig_destroy__ = _grt_py.delete_IncrementalGRoute

# Register IncrementalGRoute in _grt_py:
_grt_py.IncrementalGRoute_swigregister(IncrementalGRoute)



