record_tests {
  make_parasitics1
  make_parasitics2
  rebuffer1
  rebuffer2
  rebuffer4
  rebuffer7
  buffer_ports1
  buffer_ports2
  buffer_ports3
  buffer_ports5
  resize1
  resize2
  resize4
  resize6
  repair_max_cap1
  repair_max_cap2
  repair_max_fanout1
  repair_max_slew1
  repair_max_slew2
  repair_hold1
  repair_hold2
  report_floating_nets1
  repair_tie_fanout1
  repair_tie_fanout2
  repair_tie_fanout3
}
