name: OpenROAD Pull Request 
description: File a pull request for OpenROAD 
  
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! It helps us more quickly track, narrow down, and address bugs.
  - type: dropdown
    id: version
    attributes:
      label: Subject
      description: Choose the category that best fits your bug/problem.
      options:
        - [NEW]: New features, either in the form of Tcl/Python API changes.
        - [DOC]: Documentation only changes.
        - [FIX]: When fixing bugs or issues
        - [ENH]: Feature enhancement
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
    validations:
      required: true
