#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2026, The OpenROAD Authors
#
# Embed the standalone timing report's CSS and JS as C++ string literals.
#
# All four inputs come from esbuild (see //src/web:report_bundle), so this only
# has to quote them.  It used to concatenate the viewer's JS files in a
# hand-kept order and strip their import/export statements to force them into
# one scope; the bundler does that properly now.

import argparse
import os

# Delimiter for the raw string literals.  Content containing it would close the
# literal early, so read_checked() checks rather than assumes.
DELIMITER = "__REPORT_ASSET__"


def read_checked(path):
    with open(path, encoding="utf-8") as f:
        content = f.read()
    # A carriage return inside a raw string literal is translated away by the
    # compiler, so the embedded bytes would not match the file.
    if f'){DELIMITER}"' in content or "\0" in content or "\r" in content:
        raise SystemExit(f"{path} cannot be held verbatim in a raw string literal")
    return content


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", "-o", required=True)
    parser.add_argument("--vendor-css", required=True, help="third-party stylesheets")
    parser.add_argument("--theme-dark", required=True, help="dark theme stylesheet")
    parser.add_argument("--theme-light", required=True, help="light theme stylesheet")
    parser.add_argument("--app-css", required=True, help="the app's own stylesheet")
    parser.add_argument("--js", required=True, help="the bundled script")
    args = parser.parse_args()

    # The saved report carries the same four stylesheets the served page does,
    # in the same order -- see src/vendor.css for why the order matters.
    contents = {
        "kReportVendorCSS": args.vendor_css,
        "kReportThemeDark": args.theme_dark,
        "kReportThemeLight": args.theme_light,
        "kReportAppCSS": args.app_css,
        "kReportJS": args.js,
    }

    # Written aside and renamed: a failure must not leave a truncated .cpp newer
    # than its inputs, which the next build would keep.
    partial = args.output + ".tmp"
    with open(partial, "w", encoding="utf-8") as out:
        out.write("// Auto-generated by embed_report_assets.py — do not edit.\n")
        out.write("#include <string_view>\n\n")
        out.write("namespace web {\n\n")
        for name, path in contents.items():
            out.write(f'extern const std::string_view {name} = R"{DELIMITER}(\n')
            out.write(read_checked(path))
            out.write(f'){DELIMITER}";\n\n')
        out.write("}  // namespace web\n")

    os.replace(partial, args.output)


if __name__ == "__main__":
    main()
