#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2026, The OpenROAD Authors
#
# Embed the standalone timing report's CSS and JS, gzipped, as EmbeddedAssets
# that saveReport() inflates into the file it writes.
#
# All five inputs come from esbuild (see //src/web:report_bundle), so this only
# has to pack them.  It used to concatenate the viewer's JS files in a
# hand-kept order and strip their import/export statements to force them into
# one scope; the bundler does that properly now.

import argparse
import os

from embedded_blob import gzip_bytes, write_char_array


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", "-o", required=True)
    parser.add_argument("--vendor-css", required=True, help="third-party stylesheets")
    parser.add_argument("--theme-dark", required=True, help="dark theme stylesheet")
    parser.add_argument("--theme-light", required=True, help="light theme stylesheet")
    parser.add_argument("--app-css", required=True, help="the app's own stylesheet")
    parser.add_argument("--js", required=True, help="the bundled script")
    args = parser.parse_args()

    # The saved report carries the same four stylesheets the served page does,
    # in the same order -- see src/vendor.css for why the order matters.
    contents = {
        "kReportVendorCSS": (args.vendor_css, "text/css"),
        "kReportThemeDark": (args.theme_dark, "text/css"),
        "kReportThemeLight": (args.theme_light, "text/css"),
        "kReportAppCSS": (args.app_css, "text/css"),
        "kReportJS": (args.js, "application/javascript"),
    }

    # Written aside and renamed: a failure must not leave a truncated .cpp newer
    # than its inputs, which the next build would keep.
    partial = args.output + ".tmp"
    with open(partial, "w", encoding="utf-8") as out:
        out.write("// Auto-generated by embed_report_assets.py — do not edit.\n")
        out.write('#include "web_assets.h"\n\n')
        out.write("namespace web {\n\n")
        for name, (path, mime) in contents.items():
            with open(path, "rb") as f:
                data = f.read()
            packed = gzip_bytes(data)
            write_char_array(out, name, packed)
            out.write(
                f"extern const EmbeddedAsset {name}"
                f' = {{{name}_data, {len(packed)}, "{mime}", true, {len(data)}}};\n\n'
            )
        out.write("}  // namespace web\n")

    os.replace(partial, args.output)


if __name__ == "__main__":
    main()
