#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2026, The OpenROAD Authors
#
# Embed web asset files (HTML, JS, CSS) as C++ raw string literals
# so the web server can serve them without a -dir argument.
#
# Generates a .cpp file with a lookup function: path -> (content, MIME type).

import argparse
import os

MIME_TYPES = {
    ".html": "text/html",
    ".js": "application/javascript",
    ".css": "text/css",
    ".json": "application/json",
}


def c_identifier(filename):
    """Convert a filename to a valid C identifier."""
    return "k_" + filename.replace(".", "_").replace("-", "_")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", "-o", required=True)
    parser.add_argument("files", nargs="+", help="Asset files to embed")
    args = parser.parse_args()

    assets = []
    for path in args.files:
        filename = os.path.basename(path)
        ext = os.path.splitext(filename)[1]
        mime = MIME_TYPES.get(ext, "application/octet-stream")
        with open(path, encoding="utf-8") as f:
            content = f.read()
        assets.append((filename, c_identifier(filename), mime, content))

    # Use a delimiter unlikely to appear in JS/CSS/HTML content.
    delim = "__WEB_ASSET__"

    with open(args.output, "w", encoding="utf-8") as out:
        out.write("// Auto-generated by embed_web_assets.py — do not edit.\n")
        out.write('#include "web_assets.h"\n\n')
        out.write("#include <string_view>\n\n")
        out.write("namespace web {\n\n")

        # Write each asset as a raw string literal.
        for filename, ident, mime, content in assets:
            out.write(f"// {filename}\n")
            out.write(f'static const char {ident}_data[] = R"{delim}(')
            out.write(content)
            out.write(f'){delim}";\n\n')

        # Write the lookup table.
        out.write("static const struct {\n")
        out.write("  const char* path;\n")
        out.write("  EmbeddedAsset asset;\n")
        out.write(f"}} kAssetTable[] = {{\n")
        for filename, ident, mime, _ in assets:
            out.write(
                f'    {{"/{filename}", '
                f'{{{ident}_data, sizeof({ident}_data) - 1, "{mime}"}}}},\n'
            )
        out.write("};\n\n")

        out.write("const EmbeddedAsset* findEmbeddedAsset(std::string_view path)\n")
        out.write("{\n")
        out.write("  for (const auto& entry : kAssetTable) {\n")
        out.write("    if (path == entry.path) {\n")
        out.write("      return &entry.asset;\n")
        out.write("    }\n")
        out.write("  }\n")
        out.write("  return nullptr;\n")
        out.write("}\n\n")

        out.write("}  // namespace web\n")


if __name__ == "__main__":
    main()
