#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2026, The OpenROAD Authors
#
# Embed the saved timing report's script (//src/web:report_bundle), gzipped, as
# the EmbeddedAsset saveReport() inflates; its styles come from /index.html.

import argparse
import os

from embedded_blob import gzip_bytes, write_char_array


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", "-o", required=True)
    parser.add_argument("--js", required=True, help="the bundled script")
    args = parser.parse_args()

    with open(args.js, "rb") as f:
        data = f.read()
    packed = gzip_bytes(data)

    # Written aside and renamed: a failure must not leave a truncated .cpp newer
    # than its inputs, which the next build would keep.
    partial = args.output + ".tmp"
    with open(partial, "w", encoding="utf-8") as out:
        out.write("// Auto-generated by embed_report_assets.py — do not edit.\n")
        out.write('#include "web_assets.h"\n\n')
        out.write("namespace web {\n\n")
        write_char_array(out, "kReportJS", packed)
        out.write(
            "extern const EmbeddedAsset kReportJS = {kReportJS_data, "
            f'{len(packed)}, "application/javascript", true, {len(data)}}};\n\n'
        )
        out.write("}  // namespace web\n")

    os.replace(partial, args.output)


if __name__ == "__main__":
    main()
