// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2026, The OpenROAD Authors

#include "src/web/include/web/MakeWeb.h"

#include "src/utl/include/utl/decode.h"
#include "tcl.h"

// Generated by swig from the web.i
extern "C" {
extern int Web_Init(Tcl_Interp* interp);
}

namespace web {

// example.tcl encoded as strings.
extern const char* web_tcl_inits[];

void initWeb(Tcl_Interp* tcl_interp)
{
  // Define swig TCL commands.
  Web_Init(tcl_interp);
  // Eval encoded TCL sources.
  utl::evalTclInit(tcl_interp, web_tcl_inits);
}

}  // namespace web
