/* Generated by Yosys 0.44 (git sha1 80ba43d26, clang++ 11.1.0 -fPIC -O3) */

(* implements_operator = "LCU_16" *)
(* src = "/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_impls.v:36.1-77.10" *)
module LCU_16_BRENT_KUNG(P, G, CO);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  (* src = "/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_impls.v:43.21-43.23" *)
  output [15:0] CO;
  wire [15:0] CO;
  (* src = "/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_impls.v:40.23-40.24" *)
  input [15:0] G;
  wire [15:0] G;
  (* src = "/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_impls.v:40.20-40.21" *)
  input [15:0] P;
  wire [15:0] P;
  (* src = "/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_impls.v:47.21-47.22" *)
  wire \g[10] ;
  (* src = "/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_impls.v:47.21-47.22" *)
  wire \g[11] ;
  (* src = "/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_impls.v:47.21-47.22" *)
  wire \g[12] ;
  (* src = "/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_impls.v:47.21-47.22" *)
  wire \g[13] ;
  (* src = "/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_impls.v:47.21-47.22" *)
  wire \g[14] ;
  (* src = "/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_impls.v:47.21-47.22" *)
  wire \g[15] ;
  (* src = "/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_impls.v:47.21-47.22" *)
  wire \g[1] ;
  (* src = "/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_impls.v:47.21-47.22" *)
  wire \g[2] ;
  (* src = "/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_impls.v:47.21-47.22" *)
  wire \g[3] ;
  (* src = "/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_impls.v:47.21-47.22" *)
  wire \g[4] ;
  (* src = "/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_impls.v:47.21-47.22" *)
  wire \g[5] ;
  (* src = "/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_impls.v:47.21-47.22" *)
  wire \g[6] ;
  (* src = "/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_impls.v:47.21-47.22" *)
  wire \g[7] ;
  (* src = "/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_impls.v:47.21-47.22" *)
  wire \g[8] ;
  (* src = "/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_impls.v:47.21-47.22" *)
  wire \g[9] ;
  sky130_fd_sc_hd__inv_1 _31_ (
    .A(P[14]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__a21oi_1 _32_ (
    .A1(P[1]),
    .A2(G[0]),
    .B1(G[1]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__inv_1 _33_ (
    .A(_01_),
    .Y(\g[1] )
  );
  sky130_fd_sc_hd__a21oi_1 _34_ (
    .A1(P[3]),
    .A2(G[2]),
    .B1(G[3]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__nand2_1 _35_ (
    .A(P[3]),
    .B(P[2]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__o21ai_0 _36_ (
    .A1(_03_),
    .A2(_01_),
    .B1(_02_),
    .Y(\g[3] )
  );
  sky130_fd_sc_hd__a21oi_1 _37_ (
    .A1(P[7]),
    .A2(G[6]),
    .B1(G[7]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__nand2_1 _38_ (
    .A(P[7]),
    .B(P[6]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__a21oi_1 _39_ (
    .A1(P[5]),
    .A2(G[4]),
    .B1(G[5]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__o21ai_0 _40_ (
    .A1(_05_),
    .A2(_06_),
    .B1(_04_),
    .Y(_07_)
  );
  sky130_fd_sc_hd__nand2_1 _41_ (
    .A(P[5]),
    .B(P[4]),
    .Y(_08_)
  );
  sky130_fd_sc_hd__nor2_1 _42_ (
    .A(_05_),
    .B(_08_),
    .Y(_09_)
  );
  sky130_fd_sc_hd__a21oi_1 _43_ (
    .A1(\g[3] ),
    .A2(_09_),
    .B1(_07_),
    .Y(_10_)
  );
  sky130_fd_sc_hd__inv_1 _44_ (
    .A(_10_),
    .Y(\g[7] )
  );
  sky130_fd_sc_hd__a21oi_1 _45_ (
    .A1(P[11]),
    .A2(G[10]),
    .B1(G[11]),
    .Y(_11_)
  );
  sky130_fd_sc_hd__nand2_1 _46_ (
    .A(P[11]),
    .B(P[10]),
    .Y(_12_)
  );
  sky130_fd_sc_hd__a21oi_1 _47_ (
    .A1(P[9]),
    .A2(G[8]),
    .B1(G[9]),
    .Y(_13_)
  );
  sky130_fd_sc_hd__o21ai_0 _48_ (
    .A1(_12_),
    .A2(_13_),
    .B1(_11_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__nand2_1 _49_ (
    .A(P[9]),
    .B(P[8]),
    .Y(_15_)
  );
  sky130_fd_sc_hd__nand4_1 _50_ (
    .A(P[9]),
    .B(P[11]),
    .C(P[8]),
    .D(P[10]),
    .Y(_16_)
  );
  sky130_fd_sc_hd__o21bai_1 _51_ (
    .A1(_16_),
    .A2(_10_),
    .B1_N(_14_),
    .Y(\g[11] )
  );
  sky130_fd_sc_hd__nand3_1 _52_ (
    .A(\g[3] ),
    .B(P[4]),
    .C(P[5]),
    .Y(_17_)
  );
  sky130_fd_sc_hd__nand2_1 _53_ (
    .A(_17_),
    .B(_06_),
    .Y(\g[5] )
  );
  sky130_fd_sc_hd__o21ai_0 _54_ (
    .A1(_15_),
    .A2(_10_),
    .B1(_13_),
    .Y(\g[9] )
  );
  sky130_fd_sc_hd__a21oi_1 _55_ (
    .A1(P[13]),
    .A2(G[12]),
    .B1(G[13]),
    .Y(_18_)
  );
  sky130_fd_sc_hd__nand2_1 _56_ (
    .A(P[13]),
    .B(P[12]),
    .Y(_19_)
  );
  sky130_fd_sc_hd__inv_1 _57_ (
    .A(_19_),
    .Y(_20_)
  );
  sky130_fd_sc_hd__a21boi_0 _58_ (
    .A1(\g[11] ),
    .A2(_20_),
    .B1_N(_18_),
    .Y(_21_)
  );
  sky130_fd_sc_hd__inv_1 _59_ (
    .A(_21_),
    .Y(\g[13] )
  );
  sky130_fd_sc_hd__a21oi_1 _60_ (
    .A1(P[15]),
    .A2(G[14]),
    .B1(G[15]),
    .Y(_22_)
  );
  sky130_fd_sc_hd__nand2_1 _61_ (
    .A(P[15]),
    .B(P[14]),
    .Y(_23_)
  );
  sky130_fd_sc_hd__o21ai_0 _62_ (
    .A1(_23_),
    .A2(_18_),
    .B1(_22_),
    .Y(_24_)
  );
  sky130_fd_sc_hd__nor2_1 _63_ (
    .A(_19_),
    .B(_23_),
    .Y(_25_)
  );
  sky130_fd_sc_hd__a21oi_1 _64_ (
    .A1(_14_),
    .A2(_25_),
    .B1(_24_),
    .Y(_26_)
  );
  sky130_fd_sc_hd__o41ai_1 _65_ (
    .A1(_16_),
    .A2(_19_),
    .A3(_23_),
    .A4(_10_),
    .B1(_26_),
    .Y(\g[15] )
  );
  sky130_fd_sc_hd__a21oi_1 _66_ (
    .A1(\g[1] ),
    .A2(P[2]),
    .B1(G[2]),
    .Y(_27_)
  );
  sky130_fd_sc_hd__inv_1 _67_ (
    .A(_27_),
    .Y(\g[2] )
  );
  sky130_fd_sc_hd__a21oi_1 _68_ (
    .A1(\g[3] ),
    .A2(P[4]),
    .B1(G[4]),
    .Y(_28_)
  );
  sky130_fd_sc_hd__inv_1 _69_ (
    .A(_28_),
    .Y(\g[4] )
  );
  sky130_fd_sc_hd__a21oi_1 _70_ (
    .A1(\g[5] ),
    .A2(P[6]),
    .B1(G[6]),
    .Y(_29_)
  );
  sky130_fd_sc_hd__inv_1 _71_ (
    .A(_29_),
    .Y(\g[6] )
  );
  sky130_fd_sc_hd__a21o_2 _72_ (
    .A1(\g[7] ),
    .A2(P[8]),
    .B1(G[8]),
    .X(\g[8] )
  );
  sky130_fd_sc_hd__a21o_2 _73_ (
    .A1(\g[9] ),
    .A2(P[10]),
    .B1(G[10]),
    .X(\g[10] )
  );
  sky130_fd_sc_hd__a21oi_1 _74_ (
    .A1(\g[11] ),
    .A2(P[12]),
    .B1(G[12]),
    .Y(_30_)
  );
  sky130_fd_sc_hd__inv_1 _75_ (
    .A(_30_),
    .Y(\g[12] )
  );
  sky130_fd_sc_hd__o21bai_1 _76_ (
    .A1(_00_),
    .A2(_21_),
    .B1_N(G[14]),
    .Y(\g[14] )
  );
  sky130_fd_sc_hd__buf_4 _77_ (
    .A(G[0]),
    .X(CO[0])
  );
  sky130_fd_sc_hd__buf_4 _78_ (
    .A(\g[1] ),
    .X(CO[1])
  );
  sky130_fd_sc_hd__buf_4 _79_ (
    .A(\g[2] ),
    .X(CO[2])
  );
  sky130_fd_sc_hd__buf_4 _80_ (
    .A(\g[3] ),
    .X(CO[3])
  );
  sky130_fd_sc_hd__buf_4 _81_ (
    .A(\g[4] ),
    .X(CO[4])
  );
  sky130_fd_sc_hd__buf_4 _82_ (
    .A(\g[5] ),
    .X(CO[5])
  );
  sky130_fd_sc_hd__buf_4 _83_ (
    .A(\g[6] ),
    .X(CO[6])
  );
  sky130_fd_sc_hd__buf_4 _84_ (
    .A(\g[7] ),
    .X(CO[7])
  );
  sky130_fd_sc_hd__buf_4 _85_ (
    .A(\g[8] ),
    .X(CO[8])
  );
  sky130_fd_sc_hd__buf_4 _86_ (
    .A(\g[9] ),
    .X(CO[9])
  );
  sky130_fd_sc_hd__buf_4 _87_ (
    .A(\g[10] ),
    .X(CO[10])
  );
  sky130_fd_sc_hd__buf_4 _88_ (
    .A(\g[11] ),
    .X(CO[11])
  );
  sky130_fd_sc_hd__buf_4 _89_ (
    .A(\g[12] ),
    .X(CO[12])
  );
  sky130_fd_sc_hd__buf_4 _90_ (
    .A(\g[13] ),
    .X(CO[13])
  );
  sky130_fd_sc_hd__buf_4 _91_ (
    .A(\g[14] ),
    .X(CO[14])
  );
  sky130_fd_sc_hd__buf_4 _92_ (
    .A(\g[15] ),
    .X(CO[15])
  );
endmodule

(* implements_operator = "LCU_16" *)
(* src = "/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_impls.v:3.1-32.10" *)
module LCU_16_KOGGE_STONE(P, G, CO);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  (* src = "/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_impls.v:10.21-10.23" *)
  output [15:0] CO;
  wire [15:0] CO;
  (* src = "/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_impls.v:7.23-7.24" *)
  input [15:0] G;
  wire [15:0] G;
  (* src = "/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_impls.v:7.20-7.21" *)
  input [15:0] P;
  wire [15:0] P;
  (* src = "/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_impls.v:14.21-14.22" *)
  wire \g[10] ;
  (* src = "/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_impls.v:14.21-14.22" *)
  wire \g[11] ;
  (* src = "/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_impls.v:14.21-14.22" *)
  wire \g[12] ;
  (* src = "/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_impls.v:14.21-14.22" *)
  wire \g[13] ;
  (* src = "/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_impls.v:14.21-14.22" *)
  wire \g[14] ;
  (* src = "/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_impls.v:14.21-14.22" *)
  wire \g[15] ;
  (* src = "/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_impls.v:14.21-14.22" *)
  wire \g[1] ;
  (* src = "/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_impls.v:14.21-14.22" *)
  wire \g[2] ;
  (* src = "/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_impls.v:14.21-14.22" *)
  wire \g[3] ;
  (* src = "/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_impls.v:14.21-14.22" *)
  wire \g[4] ;
  (* src = "/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_impls.v:14.21-14.22" *)
  wire \g[5] ;
  (* src = "/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_impls.v:14.21-14.22" *)
  wire \g[6] ;
  (* src = "/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_impls.v:14.21-14.22" *)
  wire \g[7] ;
  (* src = "/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_impls.v:14.21-14.22" *)
  wire \g[8] ;
  (* src = "/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_impls.v:14.21-14.22" *)
  wire \g[9] ;
  sky130_fd_sc_hd__inv_1 _072_ (
    .A(G[0]),
    .Y(_027_)
  );
  sky130_fd_sc_hd__a21oi_1 _073_ (
    .A1(P[1]),
    .A2(G[0]),
    .B1(G[1]),
    .Y(_028_)
  );
  sky130_fd_sc_hd__inv_1 _074_ (
    .A(_028_),
    .Y(\g[1] )
  );
  sky130_fd_sc_hd__a21oi_1 _075_ (
    .A1(P[3]),
    .A2(G[2]),
    .B1(G[3]),
    .Y(_029_)
  );
  sky130_fd_sc_hd__nand2_1 _076_ (
    .A(P[3]),
    .B(P[2]),
    .Y(_030_)
  );
  sky130_fd_sc_hd__o21ai_0 _077_ (
    .A1(_030_),
    .A2(_028_),
    .B1(_029_),
    .Y(\g[3] )
  );
  sky130_fd_sc_hd__a21oi_1 _078_ (
    .A1(P[2]),
    .A2(G[1]),
    .B1(G[2]),
    .Y(_031_)
  );
  sky130_fd_sc_hd__nand3_1 _079_ (
    .A(P[2]),
    .B(P[1]),
    .C(G[0]),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nand2_1 _080_ (
    .A(_031_),
    .B(_032_),
    .Y(\g[2] )
  );
  sky130_fd_sc_hd__a21oi_1 _081_ (
    .A1(P[7]),
    .A2(G[6]),
    .B1(G[7]),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nand2_1 _082_ (
    .A(P[7]),
    .B(P[6]),
    .Y(_034_)
  );
  sky130_fd_sc_hd__a21oi_1 _083_ (
    .A1(P[5]),
    .A2(G[4]),
    .B1(G[5]),
    .Y(_035_)
  );
  sky130_fd_sc_hd__o21ai_0 _084_ (
    .A1(_034_),
    .A2(_035_),
    .B1(_033_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__nand2_1 _085_ (
    .A(P[5]),
    .B(P[4]),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nor2_1 _086_ (
    .A(_034_),
    .B(_037_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__a21oi_1 _087_ (
    .A1(\g[3] ),
    .A2(_038_),
    .B1(_036_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__inv_1 _088_ (
    .A(_039_),
    .Y(\g[7] )
  );
  sky130_fd_sc_hd__a21oi_1 _089_ (
    .A1(P[6]),
    .A2(G[5]),
    .B1(G[6]),
    .Y(_040_)
  );
  sky130_fd_sc_hd__nand2_1 _090_ (
    .A(P[6]),
    .B(P[5]),
    .Y(_041_)
  );
  sky130_fd_sc_hd__a21oi_1 _091_ (
    .A1(P[4]),
    .A2(G[3]),
    .B1(G[4]),
    .Y(_042_)
  );
  sky130_fd_sc_hd__o21ai_0 _092_ (
    .A1(_041_),
    .A2(_042_),
    .B1(_040_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nand2_1 _093_ (
    .A(P[4]),
    .B(P[3]),
    .Y(_044_)
  );
  sky130_fd_sc_hd__nor2_1 _094_ (
    .A(_041_),
    .B(_044_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__a21oi_1 _095_ (
    .A1(\g[2] ),
    .A2(_045_),
    .B1(_043_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__inv_1 _096_ (
    .A(_046_),
    .Y(\g[6] )
  );
  sky130_fd_sc_hd__o21ai_0 _097_ (
    .A1(_037_),
    .A2(_029_),
    .B1(_035_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__nand4_1 _098_ (
    .A(P[5]),
    .B(P[4]),
    .C(P[3]),
    .D(P[2]),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nor2_1 _099_ (
    .A(_048_),
    .B(_028_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nor2_1 _100_ (
    .A(_049_),
    .B(_047_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__inv_1 _101_ (
    .A(_050_),
    .Y(\g[5] )
  );
  sky130_fd_sc_hd__o21ai_0 _102_ (
    .A1(_044_),
    .A2(_031_),
    .B1(_042_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__nand4_1 _103_ (
    .A(P[4]),
    .B(P[3]),
    .C(P[2]),
    .D(P[1]),
    .Y(_052_)
  );
  sky130_fd_sc_hd__o221ai_1 _104_ (
    .A1(_027_),
    .A2(_052_),
    .B1(_044_),
    .B2(_031_),
    .C1(_042_),
    .Y(\g[4] )
  );
  sky130_fd_sc_hd__a21oi_1 _105_ (
    .A1(P[15]),
    .A2(G[14]),
    .B1(G[15]),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nand2_1 _106_ (
    .A(P[15]),
    .B(P[14]),
    .Y(_054_)
  );
  sky130_fd_sc_hd__a21oi_1 _107_ (
    .A1(P[13]),
    .A2(G[12]),
    .B1(G[13]),
    .Y(_055_)
  );
  sky130_fd_sc_hd__o21ai_0 _108_ (
    .A1(_054_),
    .A2(_055_),
    .B1(_053_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nand2_1 _109_ (
    .A(P[13]),
    .B(P[12]),
    .Y(_057_)
  );
  sky130_fd_sc_hd__nor2_1 _110_ (
    .A(_054_),
    .B(_057_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__a21oi_1 _111_ (
    .A1(P[11]),
    .A2(G[10]),
    .B1(G[11]),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nand2_1 _112_ (
    .A(P[11]),
    .B(P[10]),
    .Y(_060_)
  );
  sky130_fd_sc_hd__a21oi_1 _113_ (
    .A1(P[9]),
    .A2(G[8]),
    .B1(G[9]),
    .Y(_061_)
  );
  sky130_fd_sc_hd__o21ai_0 _114_ (
    .A1(_060_),
    .A2(_061_),
    .B1(_059_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__a21oi_1 _115_ (
    .A1(_062_),
    .A2(_058_),
    .B1(_056_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__nand2_1 _116_ (
    .A(P[9]),
    .B(P[8]),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nor2_1 _117_ (
    .A(_060_),
    .B(_064_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__nand2_1 _118_ (
    .A(_058_),
    .B(_065_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__o21ai_0 _119_ (
    .A1(_066_),
    .A2(_039_),
    .B1(_063_),
    .Y(\g[15] )
  );
  sky130_fd_sc_hd__a21oi_1 _120_ (
    .A1(P[14]),
    .A2(G[13]),
    .B1(G[14]),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nand2_1 _121_ (
    .A(P[14]),
    .B(P[13]),
    .Y(_068_)
  );
  sky130_fd_sc_hd__a21oi_1 _122_ (
    .A1(P[12]),
    .A2(G[11]),
    .B1(G[12]),
    .Y(_069_)
  );
  sky130_fd_sc_hd__o21ai_0 _123_ (
    .A1(_068_),
    .A2(_069_),
    .B1(_067_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nand2_1 _124_ (
    .A(P[12]),
    .B(P[11]),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nor2_1 _125_ (
    .A(_068_),
    .B(_071_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__a21oi_1 _126_ (
    .A1(P[10]),
    .A2(G[9]),
    .B1(G[10]),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nand2_1 _127_ (
    .A(P[10]),
    .B(P[9]),
    .Y(_002_)
  );
  sky130_fd_sc_hd__a21oi_1 _128_ (
    .A1(P[8]),
    .A2(G[7]),
    .B1(G[8]),
    .Y(_003_)
  );
  sky130_fd_sc_hd__o21ai_0 _129_ (
    .A1(_002_),
    .A2(_003_),
    .B1(_001_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__a21oi_1 _130_ (
    .A1(_004_),
    .A2(_000_),
    .B1(_070_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__nand2_1 _131_ (
    .A(P[8]),
    .B(P[7]),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nor2_1 _132_ (
    .A(_002_),
    .B(_006_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nand2_1 _133_ (
    .A(_000_),
    .B(_007_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__o21ai_0 _134_ (
    .A1(_008_),
    .A2(_046_),
    .B1(_005_),
    .Y(\g[14] )
  );
  sky130_fd_sc_hd__o21ai_0 _135_ (
    .A1(_057_),
    .A2(_059_),
    .B1(_055_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nor2_1 _136_ (
    .A(_057_),
    .B(_060_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__o21ai_0 _137_ (
    .A1(_064_),
    .A2(_033_),
    .B1(_061_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__a21oi_1 _138_ (
    .A1(_011_),
    .A2(_010_),
    .B1(_009_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__nor2_1 _139_ (
    .A(_034_),
    .B(_064_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__nand2_1 _140_ (
    .A(_010_),
    .B(_013_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__o21ai_0 _141_ (
    .A1(_014_),
    .A2(_050_),
    .B1(_012_),
    .Y(\g[13] )
  );
  sky130_fd_sc_hd__o21ai_0 _142_ (
    .A1(_071_),
    .A2(_001_),
    .B1(_069_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__nor2_1 _143_ (
    .A(_071_),
    .B(_002_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__o21ai_0 _144_ (
    .A1(_006_),
    .A2(_040_),
    .B1(_003_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__a21oi_1 _145_ (
    .A1(_017_),
    .A2(_016_),
    .B1(_015_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__nor2_1 _146_ (
    .A(_041_),
    .B(_006_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nand3_1 _147_ (
    .A(\g[4] ),
    .B(_016_),
    .C(_019_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nand2_1 _148_ (
    .A(_020_),
    .B(_018_),
    .Y(\g[12] )
  );
  sky130_fd_sc_hd__a21oi_1 _149_ (
    .A1(_036_),
    .A2(_065_),
    .B1(_062_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nand3_1 _150_ (
    .A(\g[3] ),
    .B(_038_),
    .C(_065_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nand2_1 _151_ (
    .A(_021_),
    .B(_022_),
    .Y(\g[11] )
  );
  sky130_fd_sc_hd__a21oi_1 _152_ (
    .A1(_043_),
    .A2(_007_),
    .B1(_004_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nand3_1 _153_ (
    .A(\g[2] ),
    .B(_045_),
    .C(_007_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nand2_1 _154_ (
    .A(_023_),
    .B(_024_),
    .Y(\g[10] )
  );
  sky130_fd_sc_hd__a21oi_1 _155_ (
    .A1(_047_),
    .A2(_013_),
    .B1(_011_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__o41ai_1 _156_ (
    .A1(_034_),
    .A2(_048_),
    .A3(_064_),
    .A4(_028_),
    .B1(_025_),
    .Y(\g[9] )
  );
  sky130_fd_sc_hd__a21oi_1 _157_ (
    .A1(_051_),
    .A2(_019_),
    .B1(_017_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__o41ai_1 _158_ (
    .A1(_027_),
    .A2(_041_),
    .A3(_052_),
    .A4(_006_),
    .B1(_026_),
    .Y(\g[8] )
  );
  sky130_fd_sc_hd__buf_4 _159_ (
    .A(G[0]),
    .X(CO[0])
  );
  sky130_fd_sc_hd__buf_4 _160_ (
    .A(\g[1] ),
    .X(CO[1])
  );
  sky130_fd_sc_hd__buf_4 _161_ (
    .A(\g[2] ),
    .X(CO[2])
  );
  sky130_fd_sc_hd__buf_4 _162_ (
    .A(\g[3] ),
    .X(CO[3])
  );
  sky130_fd_sc_hd__buf_4 _163_ (
    .A(\g[4] ),
    .X(CO[4])
  );
  sky130_fd_sc_hd__buf_4 _164_ (
    .A(\g[5] ),
    .X(CO[5])
  );
  sky130_fd_sc_hd__buf_4 _165_ (
    .A(\g[6] ),
    .X(CO[6])
  );
  sky130_fd_sc_hd__buf_4 _166_ (
    .A(\g[7] ),
    .X(CO[7])
  );
  sky130_fd_sc_hd__buf_4 _167_ (
    .A(\g[8] ),
    .X(CO[8])
  );
  sky130_fd_sc_hd__buf_4 _168_ (
    .A(\g[9] ),
    .X(CO[9])
  );
  sky130_fd_sc_hd__buf_4 _169_ (
    .A(\g[10] ),
    .X(CO[10])
  );
  sky130_fd_sc_hd__buf_4 _170_ (
    .A(\g[11] ),
    .X(CO[11])
  );
  sky130_fd_sc_hd__buf_4 _171_ (
    .A(\g[12] ),
    .X(CO[12])
  );
  sky130_fd_sc_hd__buf_4 _172_ (
    .A(\g[13] ),
    .X(CO[13])
  );
  sky130_fd_sc_hd__buf_4 _173_ (
    .A(\g[14] ),
    .X(CO[14])
  );
  sky130_fd_sc_hd__buf_4 _174_ (
    .A(\g[15] ),
    .X(CO[15])
  );
endmodule

(* top =  1  *)
(* src = "./designs/src/gcd/gcd.v:11.1-102.10" *)
module gcd(clk, req_msg, req_rdy, req_val, reset, resp_msg, resp_rdy, resp_val, carry_out);
  wire _000_;
  wire _001_;
  wire _002_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:286.27-286.69|/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_nomap.v:14.66-14.84" *)
  wire _003_;
  (* src = "./designs/src/gcd/gcd.v:752.12-752.19|/Users/pk/repos/yosys/share/techmap.v:286.27-286.69|/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_nomap.v:14.66-14.84" *)
  wire _004_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:274.23-274.25" *)
  wire _005_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:270.23-270.24" *)
  wire _006_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:270.23-270.24" *)
  wire _007_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:270.23-270.24" *)
  wire _008_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:270.23-270.24" *)
  wire _009_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:270.23-270.24" *)
  wire _010_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:270.23-270.24" *)
  wire _011_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:270.23-270.24" *)
  wire _012_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:270.23-270.24" *)
  wire _013_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:270.23-270.24" *)
  wire _014_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:270.23-270.24" *)
  wire _015_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:270.23-270.24" *)
  wire _016_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:270.23-270.24" *)
  wire _017_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:270.23-270.24" *)
  wire _018_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:270.23-270.24" *)
  wire _019_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:270.23-270.24" *)
  wire _020_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:270.23-270.24" *)
  wire _021_;
  (* src = "./designs/src/gcd/gcd.v:752.12-752.19|/Users/pk/repos/yosys/share/techmap.v:274.23-274.25" *)
  wire _022_;
  (* src = "./designs/src/gcd/gcd.v:752.12-752.19|/Users/pk/repos/yosys/share/techmap.v:274.23-274.25" *)
  wire _023_;
  (* src = "./designs/src/gcd/gcd.v:752.12-752.19|/Users/pk/repos/yosys/share/techmap.v:274.23-274.25" *)
  wire _024_;
  (* src = "./designs/src/gcd/gcd.v:752.12-752.19|/Users/pk/repos/yosys/share/techmap.v:274.23-274.25" *)
  wire _025_;
  (* src = "./designs/src/gcd/gcd.v:752.12-752.19|/Users/pk/repos/yosys/share/techmap.v:274.23-274.25" *)
  wire _026_;
  (* src = "./designs/src/gcd/gcd.v:752.12-752.19|/Users/pk/repos/yosys/share/techmap.v:274.23-274.25" *)
  wire _027_;
  (* src = "./designs/src/gcd/gcd.v:752.12-752.19|/Users/pk/repos/yosys/share/techmap.v:274.23-274.25" *)
  wire _028_;
  (* src = "./designs/src/gcd/gcd.v:752.12-752.19|/Users/pk/repos/yosys/share/techmap.v:274.23-274.25" *)
  wire _029_;
  (* src = "./designs/src/gcd/gcd.v:752.12-752.19|/Users/pk/repos/yosys/share/techmap.v:274.23-274.25" *)
  wire _030_;
  (* src = "./designs/src/gcd/gcd.v:752.12-752.19|/Users/pk/repos/yosys/share/techmap.v:274.23-274.25" *)
  wire _031_;
  (* src = "./designs/src/gcd/gcd.v:752.12-752.19|/Users/pk/repos/yosys/share/techmap.v:274.23-274.25" *)
  wire _032_;
  (* src = "./designs/src/gcd/gcd.v:752.12-752.19|/Users/pk/repos/yosys/share/techmap.v:274.23-274.25" *)
  wire _033_;
  (* src = "./designs/src/gcd/gcd.v:752.12-752.19|/Users/pk/repos/yosys/share/techmap.v:274.23-274.25" *)
  wire _034_;
  (* src = "./designs/src/gcd/gcd.v:752.12-752.19|/Users/pk/repos/yosys/share/techmap.v:274.23-274.25" *)
  wire _035_;
  (* src = "./designs/src/gcd/gcd.v:752.12-752.19|/Users/pk/repos/yosys/share/techmap.v:274.23-274.25" *)
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:286.27-286.69|/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_nomap.v:8.25-8.26" *)
  wire _237_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:286.27-286.69|/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_nomap.v:8.25-8.26" *)
  wire _238_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:286.27-286.69|/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_nomap.v:8.25-8.26" *)
  wire _239_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:286.27-286.69|/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_nomap.v:8.25-8.26" *)
  wire _240_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:286.27-286.69|/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_nomap.v:8.25-8.26" *)
  wire _241_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:286.27-286.69|/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_nomap.v:8.25-8.26" *)
  wire _242_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:286.27-286.69|/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_nomap.v:8.25-8.26" *)
  wire _243_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:286.27-286.69|/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_nomap.v:8.25-8.26" *)
  wire _244_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:286.27-286.69|/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_nomap.v:8.25-8.26" *)
  wire _245_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:286.27-286.69|/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_nomap.v:8.25-8.26" *)
  wire _246_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:286.27-286.69|/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_nomap.v:8.25-8.26" *)
  wire _247_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:286.27-286.69|/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_nomap.v:8.25-8.26" *)
  wire _248_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:286.27-286.69|/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_nomap.v:8.25-8.26" *)
  wire _249_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:286.27-286.69|/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_nomap.v:8.25-8.26" *)
  wire _250_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:286.27-286.69|/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_nomap.v:8.25-8.26" *)
  wire _251_;
  (* src = "./designs/src/gcd/gcd.v:752.12-752.19|/Users/pk/repos/yosys/share/techmap.v:286.27-286.69|/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_nomap.v:8.25-8.26" *)
  wire _252_;
  (* src = "./designs/src/gcd/gcd.v:752.12-752.19|/Users/pk/repos/yosys/share/techmap.v:286.27-286.69|/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_nomap.v:8.25-8.26" *)
  wire _253_;
  (* src = "./designs/src/gcd/gcd.v:752.12-752.19|/Users/pk/repos/yosys/share/techmap.v:286.27-286.69|/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_nomap.v:8.25-8.26" *)
  wire _254_;
  (* src = "./designs/src/gcd/gcd.v:752.12-752.19|/Users/pk/repos/yosys/share/techmap.v:286.27-286.69|/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_nomap.v:8.25-8.26" *)
  wire _255_;
  (* src = "./designs/src/gcd/gcd.v:752.12-752.19|/Users/pk/repos/yosys/share/techmap.v:286.27-286.69|/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_nomap.v:8.25-8.26" *)
  wire _256_;
  (* src = "./designs/src/gcd/gcd.v:752.12-752.19|/Users/pk/repos/yosys/share/techmap.v:286.27-286.69|/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_nomap.v:8.25-8.26" *)
  wire _257_;
  (* src = "./designs/src/gcd/gcd.v:752.12-752.19|/Users/pk/repos/yosys/share/techmap.v:286.27-286.69|/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_nomap.v:8.25-8.26" *)
  wire _258_;
  (* src = "./designs/src/gcd/gcd.v:752.12-752.19|/Users/pk/repos/yosys/share/techmap.v:286.27-286.69|/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_nomap.v:8.25-8.26" *)
  wire _259_;
  (* src = "./designs/src/gcd/gcd.v:752.12-752.19|/Users/pk/repos/yosys/share/techmap.v:286.27-286.69|/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_nomap.v:8.25-8.26" *)
  wire _260_;
  (* src = "./designs/src/gcd/gcd.v:752.12-752.19|/Users/pk/repos/yosys/share/techmap.v:286.27-286.69|/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_nomap.v:8.25-8.26" *)
  wire _261_;
  (* src = "./designs/src/gcd/gcd.v:752.12-752.19|/Users/pk/repos/yosys/share/techmap.v:286.27-286.69|/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_nomap.v:8.25-8.26" *)
  wire _262_;
  (* src = "./designs/src/gcd/gcd.v:752.12-752.19|/Users/pk/repos/yosys/share/techmap.v:286.27-286.69|/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_nomap.v:8.25-8.26" *)
  wire _263_;
  (* src = "./designs/src/gcd/gcd.v:752.12-752.19|/Users/pk/repos/yosys/share/techmap.v:286.27-286.69|/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_nomap.v:8.25-8.26" *)
  wire _264_;
  (* src = "./designs/src/gcd/gcd.v:752.12-752.19|/Users/pk/repos/yosys/share/techmap.v:286.27-286.69|/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_nomap.v:8.25-8.26" *)
  wire _265_;
  (* src = "./designs/src/gcd/gcd.v:752.12-752.19|/Users/pk/repos/yosys/share/techmap.v:286.27-286.69|/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_nomap.v:8.25-8.26" *)
  wire _266_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:274.23-274.25" *)
  wire _267_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:274.23-274.25" *)
  wire _268_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:274.23-274.25" *)
  wire _269_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:274.23-274.25" *)
  wire _270_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:274.23-274.25" *)
  wire _271_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:274.23-274.25" *)
  wire _272_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:274.23-274.25" *)
  wire _273_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:274.23-274.25" *)
  wire _274_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:274.23-274.25" *)
  wire _275_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:274.23-274.25" *)
  wire _276_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:274.23-274.25" *)
  wire _277_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:274.23-274.25" *)
  wire _278_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:274.23-274.25" *)
  wire _279_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:274.23-274.25" *)
  wire _280_;
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:274.23-274.25" *)
  wire _281_;
  (* src = "./designs/src/gcd/gcd.v:752.12-752.19|/Users/pk/repos/yosys/share/techmap.v:274.23-274.25" *)
  wire _282_;
  (* src = "./designs/src/gcd/gcd.v:13.15-13.18" *)
  input clk;
  wire clk;
  wire \ctrl.state.out[1] ;
  wire \ctrl.state.out[2] ;
  (* hdlname = "dpath a_lt_b$in0" *)
  (* src = "./designs/src/gcd/gcd.v:408.19-408.29" *)
  wire \dpath.a_lt_b$in0[0] ;
  (* hdlname = "dpath a_lt_b$in0" *)
  (* src = "./designs/src/gcd/gcd.v:408.19-408.29" *)
  wire \dpath.a_lt_b$in0[10] ;
  (* hdlname = "dpath a_lt_b$in0" *)
  (* src = "./designs/src/gcd/gcd.v:408.19-408.29" *)
  wire \dpath.a_lt_b$in0[11] ;
  (* hdlname = "dpath a_lt_b$in0" *)
  (* src = "./designs/src/gcd/gcd.v:408.19-408.29" *)
  wire \dpath.a_lt_b$in0[12] ;
  (* hdlname = "dpath a_lt_b$in0" *)
  (* src = "./designs/src/gcd/gcd.v:408.19-408.29" *)
  wire \dpath.a_lt_b$in0[13] ;
  (* hdlname = "dpath a_lt_b$in0" *)
  (* src = "./designs/src/gcd/gcd.v:408.19-408.29" *)
  wire \dpath.a_lt_b$in0[14] ;
  (* hdlname = "dpath a_lt_b$in0" *)
  (* src = "./designs/src/gcd/gcd.v:408.19-408.29" *)
  wire \dpath.a_lt_b$in0[15] ;
  (* hdlname = "dpath a_lt_b$in0" *)
  (* src = "./designs/src/gcd/gcd.v:408.19-408.29" *)
  wire \dpath.a_lt_b$in0[1] ;
  (* hdlname = "dpath a_lt_b$in0" *)
  (* src = "./designs/src/gcd/gcd.v:408.19-408.29" *)
  wire \dpath.a_lt_b$in0[2] ;
  (* hdlname = "dpath a_lt_b$in0" *)
  (* src = "./designs/src/gcd/gcd.v:408.19-408.29" *)
  wire \dpath.a_lt_b$in0[3] ;
  (* hdlname = "dpath a_lt_b$in0" *)
  (* src = "./designs/src/gcd/gcd.v:408.19-408.29" *)
  wire \dpath.a_lt_b$in0[4] ;
  (* hdlname = "dpath a_lt_b$in0" *)
  (* src = "./designs/src/gcd/gcd.v:408.19-408.29" *)
  wire \dpath.a_lt_b$in0[5] ;
  (* hdlname = "dpath a_lt_b$in0" *)
  (* src = "./designs/src/gcd/gcd.v:408.19-408.29" *)
  wire \dpath.a_lt_b$in0[6] ;
  (* hdlname = "dpath a_lt_b$in0" *)
  (* src = "./designs/src/gcd/gcd.v:408.19-408.29" *)
  wire \dpath.a_lt_b$in0[7] ;
  (* hdlname = "dpath a_lt_b$in0" *)
  (* src = "./designs/src/gcd/gcd.v:408.19-408.29" *)
  wire \dpath.a_lt_b$in0[8] ;
  (* hdlname = "dpath a_lt_b$in0" *)
  (* src = "./designs/src/gcd/gcd.v:408.19-408.29" *)
  wire \dpath.a_lt_b$in0[9] ;
  (* hdlname = "dpath a_lt_b$in1" *)
  (* src = "./designs/src/gcd/gcd.v:409.19-409.29" *)
  wire \dpath.a_lt_b$in1[0] ;
  (* hdlname = "dpath a_lt_b$in1" *)
  (* src = "./designs/src/gcd/gcd.v:409.19-409.29" *)
  wire \dpath.a_lt_b$in1[10] ;
  (* hdlname = "dpath a_lt_b$in1" *)
  (* src = "./designs/src/gcd/gcd.v:409.19-409.29" *)
  wire \dpath.a_lt_b$in1[11] ;
  (* hdlname = "dpath a_lt_b$in1" *)
  (* src = "./designs/src/gcd/gcd.v:409.19-409.29" *)
  wire \dpath.a_lt_b$in1[12] ;
  (* hdlname = "dpath a_lt_b$in1" *)
  (* src = "./designs/src/gcd/gcd.v:409.19-409.29" *)
  wire \dpath.a_lt_b$in1[13] ;
  (* hdlname = "dpath a_lt_b$in1" *)
  (* src = "./designs/src/gcd/gcd.v:409.19-409.29" *)
  wire \dpath.a_lt_b$in1[14] ;
  (* hdlname = "dpath a_lt_b$in1" *)
  (* src = "./designs/src/gcd/gcd.v:409.19-409.29" *)
  wire \dpath.a_lt_b$in1[15] ;
  (* hdlname = "dpath a_lt_b$in1" *)
  (* src = "./designs/src/gcd/gcd.v:409.19-409.29" *)
  wire \dpath.a_lt_b$in1[1] ;
  (* hdlname = "dpath a_lt_b$in1" *)
  (* src = "./designs/src/gcd/gcd.v:409.19-409.29" *)
  wire \dpath.a_lt_b$in1[2] ;
  (* hdlname = "dpath a_lt_b$in1" *)
  (* src = "./designs/src/gcd/gcd.v:409.19-409.29" *)
  wire \dpath.a_lt_b$in1[3] ;
  (* hdlname = "dpath a_lt_b$in1" *)
  (* src = "./designs/src/gcd/gcd.v:409.19-409.29" *)
  wire \dpath.a_lt_b$in1[4] ;
  (* hdlname = "dpath a_lt_b$in1" *)
  (* src = "./designs/src/gcd/gcd.v:409.19-409.29" *)
  wire \dpath.a_lt_b$in1[5] ;
  (* hdlname = "dpath a_lt_b$in1" *)
  (* src = "./designs/src/gcd/gcd.v:409.19-409.29" *)
  wire \dpath.a_lt_b$in1[6] ;
  (* hdlname = "dpath a_lt_b$in1" *)
  (* src = "./designs/src/gcd/gcd.v:409.19-409.29" *)
  wire \dpath.a_lt_b$in1[7] ;
  (* hdlname = "dpath a_lt_b$in1" *)
  (* src = "./designs/src/gcd/gcd.v:409.19-409.29" *)
  wire \dpath.a_lt_b$in1[8] ;
  (* hdlname = "dpath a_lt_b$in1" *)
  (* src = "./designs/src/gcd/gcd.v:409.19-409.29" *)
  wire \dpath.a_lt_b$in1[9] ;
  (* src = "./designs/src/gcd/gcd.v:14.24-14.31" *)
  input [31:0] req_msg;
  wire [31:0] req_msg;
  (* src = "./designs/src/gcd/gcd.v:15.15-15.22" *)
  output req_rdy;
  wire req_rdy;
  (* src = "./designs/src/gcd/gcd.v:16.15-16.22" *)
  input req_val;
  wire req_val;
  (* src = "./designs/src/gcd/gcd.v:17.15-17.20" *)
  input reset;
  wire reset;
  (* src = "./designs/src/gcd/gcd.v:18.24-18.32" *)
  output [15:0] resp_msg;
  wire [15:0] resp_msg;
  (* src = "./designs/src/gcd/gcd.v:19.15-19.23" *)
  input resp_rdy;
  wire resp_rdy;
  (* src = "./designs/src/gcd/gcd.v:20.15-20.23" *)
  output resp_val;
  wire resp_val;
  output carry_out; // dummy out that ANDs two LCU CO[15] CO[14] bits
  wire  carry_out;
  sky130_fd_sc_hd__and4_1 _carry_out_and_ (
    .A(_005_),
    .B(_282_),
    .C(_272_),
    .D(_027_),                                          
    .X(carry_out)
  );

  sky130_fd_sc_hd__inv_1 _283_ (
    .A(\dpath.a_lt_b$in1[1] ),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nor2_1 _284_ (
    .A(_069_),
    .B(\dpath.a_lt_b$in0[1] ),
    .Y(_243_)
  );
  sky130_fd_sc_hd__nor2b_1 _285_ (
    .A(\dpath.a_lt_b$in0[2] ),
    .B_N(\dpath.a_lt_b$in1[2] ),
    .Y(_244_)
  );
  sky130_fd_sc_hd__inv_1 _286_ (
    .A(\dpath.a_lt_b$in1[3] ),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nor2_1 _287_ (
    .A(_070_),
    .B(\dpath.a_lt_b$in0[3] ),
    .Y(_245_)
  );
  sky130_fd_sc_hd__inv_1 _288_ (
    .A(\dpath.a_lt_b$in1[4] ),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nor2_1 _289_ (
    .A(_071_),
    .B(\dpath.a_lt_b$in0[4] ),
    .Y(_246_)
  );
  sky130_fd_sc_hd__nor2b_1 _290_ (
    .A(\dpath.a_lt_b$in0[5] ),
    .B_N(\dpath.a_lt_b$in1[5] ),
    .Y(_247_)
  );
  sky130_fd_sc_hd__inv_1 _291_ (
    .A(\dpath.a_lt_b$in1[6] ),
    .Y(_072_)
  );
  sky130_fd_sc_hd__nor2_1 _292_ (
    .A(_072_),
    .B(\dpath.a_lt_b$in0[6] ),
    .Y(_248_)
  );
  sky130_fd_sc_hd__inv_1 _293_ (
    .A(\dpath.a_lt_b$in1[7] ),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nor2_1 _294_ (
    .A(_073_),
    .B(\dpath.a_lt_b$in0[7] ),
    .Y(_249_)
  );
  sky130_fd_sc_hd__inv_1 _295_ (
    .A(\dpath.a_lt_b$in1[8] ),
    .Y(_074_)
  );
  sky130_fd_sc_hd__nor2_1 _296_ (
    .A(_074_),
    .B(\dpath.a_lt_b$in0[8] ),
    .Y(_250_)
  );
  sky130_fd_sc_hd__inv_1 _297_ (
    .A(\dpath.a_lt_b$in1[9] ),
    .Y(_075_)
  );
  sky130_fd_sc_hd__nor2_1 _298_ (
    .A(_075_),
    .B(\dpath.a_lt_b$in0[9] ),
    .Y(_251_)
  );
  sky130_fd_sc_hd__inv_1 _299_ (
    .A(\dpath.a_lt_b$in1[10] ),
    .Y(_076_)
  );
  sky130_fd_sc_hd__nor2_1 _300_ (
    .A(_076_),
    .B(\dpath.a_lt_b$in0[10] ),
    .Y(_237_)
  );
  sky130_fd_sc_hd__nor2b_1 _301_ (
    .A(\dpath.a_lt_b$in0[11] ),
    .B_N(\dpath.a_lt_b$in1[11] ),
    .Y(_238_)
  );
  sky130_fd_sc_hd__inv_1 _302_ (
    .A(\dpath.a_lt_b$in1[12] ),
    .Y(_077_)
  );
  sky130_fd_sc_hd__nor2_1 _303_ (
    .A(_077_),
    .B(\dpath.a_lt_b$in0[12] ),
    .Y(_239_)
  );
  sky130_fd_sc_hd__nor2b_1 _304_ (
    .A(\dpath.a_lt_b$in0[13] ),
    .B_N(\dpath.a_lt_b$in1[13] ),
    .Y(_240_)
  );
  sky130_fd_sc_hd__nor2b_1 _305_ (
    .A(\dpath.a_lt_b$in0[14] ),
    .B_N(\dpath.a_lt_b$in1[14] ),
    .Y(_241_)
  );
  sky130_fd_sc_hd__inv_1 _306_ (
    .A(\dpath.a_lt_b$in1[15] ),
    .Y(_078_)
  );
  sky130_fd_sc_hd__nor2_1 _307_ (
    .A(_078_),
    .B(\dpath.a_lt_b$in0[15] ),
    .Y(_242_)
  );
  sky130_fd_sc_hd__nor2b_1 _308_ (
    .A(\dpath.a_lt_b$in1[1] ),
    .B_N(\dpath.a_lt_b$in0[1] ),
    .Y(_258_)
  );
  sky130_fd_sc_hd__nor2b_1 _309_ (
    .A(\dpath.a_lt_b$in1[2] ),
    .B_N(\dpath.a_lt_b$in0[2] ),
    .Y(_259_)
  );
  sky130_fd_sc_hd__nor2b_1 _310_ (
    .A(\dpath.a_lt_b$in1[3] ),
    .B_N(\dpath.a_lt_b$in0[3] ),
    .Y(_260_)
  );
  sky130_fd_sc_hd__nor2b_1 _311_ (
    .A(\dpath.a_lt_b$in1[4] ),
    .B_N(\dpath.a_lt_b$in0[4] ),
    .Y(_261_)
  );
  sky130_fd_sc_hd__nor2b_1 _312_ (
    .A(\dpath.a_lt_b$in1[5] ),
    .B_N(\dpath.a_lt_b$in0[5] ),
    .Y(_262_)
  );
  sky130_fd_sc_hd__nor2b_1 _313_ (
    .A(\dpath.a_lt_b$in1[6] ),
    .B_N(\dpath.a_lt_b$in0[6] ),
    .Y(_263_)
  );
  sky130_fd_sc_hd__nor2b_1 _314_ (
    .A(\dpath.a_lt_b$in1[7] ),
    .B_N(\dpath.a_lt_b$in0[7] ),
    .Y(_264_)
  );
  sky130_fd_sc_hd__nor2b_1 _315_ (
    .A(\dpath.a_lt_b$in1[8] ),
    .B_N(\dpath.a_lt_b$in0[8] ),
    .Y(_265_)
  );
  sky130_fd_sc_hd__nor2b_1 _316_ (
    .A(\dpath.a_lt_b$in1[9] ),
    .B_N(\dpath.a_lt_b$in0[9] ),
    .Y(_266_)
  );
  sky130_fd_sc_hd__nor2b_1 _317_ (
    .A(\dpath.a_lt_b$in1[10] ),
    .B_N(\dpath.a_lt_b$in0[10] ),
    .Y(_252_)
  );
  sky130_fd_sc_hd__nor2b_1 _318_ (
    .A(\dpath.a_lt_b$in1[11] ),
    .B_N(\dpath.a_lt_b$in0[11] ),
    .Y(_253_)
  );
  sky130_fd_sc_hd__nor2b_1 _319_ (
    .A(\dpath.a_lt_b$in1[12] ),
    .B_N(\dpath.a_lt_b$in0[12] ),
    .Y(_254_)
  );
  sky130_fd_sc_hd__nor2b_1 _320_ (
    .A(\dpath.a_lt_b$in1[13] ),
    .B_N(\dpath.a_lt_b$in0[13] ),
    .Y(_255_)
  );
  sky130_fd_sc_hd__nor2b_1 _321_ (
    .A(\dpath.a_lt_b$in1[14] ),
    .B_N(\dpath.a_lt_b$in0[14] ),
    .Y(_256_)
  );
  sky130_fd_sc_hd__nor2b_1 _322_ (
    .A(\dpath.a_lt_b$in1[15] ),
    .B_N(\dpath.a_lt_b$in0[15] ),
    .Y(_257_)
  );
  sky130_fd_sc_hd__buf_2 _323_ (
    .A(\dpath.a_lt_b$in1[0] ),
    .X(_079_)
  );
  sky130_fd_sc_hd__nand2b_1 _324_ (
    .A_N(_079_),
    .B(\dpath.a_lt_b$in0[0] ),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nand2b_1 _325_ (
    .A_N(\dpath.a_lt_b$in0[0] ),
    .B(_079_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__xnor2_2 _326_ (
    .A(_079_),
    .B(\dpath.a_lt_b$in0[0] ),
    .Y(_006_)
  );
  sky130_fd_sc_hd__xnor2_2 _327_ (
    .A(\dpath.a_lt_b$in1[1] ),
    .B(\dpath.a_lt_b$in0[1] ),
    .Y(_013_)
  );
  sky130_fd_sc_hd__xnor2_2 _328_ (
    .A(\dpath.a_lt_b$in1[2] ),
    .B(\dpath.a_lt_b$in0[2] ),
    .Y(_014_)
  );
  sky130_fd_sc_hd__xnor2_1 _329_ (
    .A(\dpath.a_lt_b$in1[3] ),
    .B(\dpath.a_lt_b$in0[3] ),
    .Y(_015_)
  );
  sky130_fd_sc_hd__xnor2_1 _330_ (
    .A(\dpath.a_lt_b$in1[4] ),
    .B(\dpath.a_lt_b$in0[4] ),
    .Y(_016_)
  );
  sky130_fd_sc_hd__xnor2_1 _331_ (
    .A(\dpath.a_lt_b$in1[5] ),
    .B(\dpath.a_lt_b$in0[5] ),
    .Y(_017_)
  );
  sky130_fd_sc_hd__xnor2_1 _332_ (
    .A(\dpath.a_lt_b$in1[6] ),
    .B(\dpath.a_lt_b$in0[6] ),
    .Y(_018_)
  );
  sky130_fd_sc_hd__xnor2_2 _333_ (
    .A(\dpath.a_lt_b$in1[7] ),
    .B(\dpath.a_lt_b$in0[7] ),
    .Y(_019_)
  );
  sky130_fd_sc_hd__xnor2_2 _334_ (
    .A(\dpath.a_lt_b$in1[8] ),
    .B(\dpath.a_lt_b$in0[8] ),
    .Y(_020_)
  );
  sky130_fd_sc_hd__xnor2_2 _335_ (
    .A(\dpath.a_lt_b$in1[9] ),
    .B(\dpath.a_lt_b$in0[9] ),
    .Y(_021_)
  );
  sky130_fd_sc_hd__xnor2_2 _336_ (
    .A(\dpath.a_lt_b$in1[10] ),
    .B(\dpath.a_lt_b$in0[10] ),
    .Y(_007_)
  );
  sky130_fd_sc_hd__xnor2_2 _337_ (
    .A(\dpath.a_lt_b$in1[11] ),
    .B(\dpath.a_lt_b$in0[11] ),
    .Y(_008_)
  );
  sky130_fd_sc_hd__xnor2_2 _338_ (
    .A(\dpath.a_lt_b$in1[12] ),
    .B(\dpath.a_lt_b$in0[12] ),
    .Y(_009_)
  );
  sky130_fd_sc_hd__xnor2_2 _339_ (
    .A(\dpath.a_lt_b$in1[13] ),
    .B(\dpath.a_lt_b$in0[13] ),
    .Y(_010_)
  );
  sky130_fd_sc_hd__xnor2_2 _340_ (
    .A(\dpath.a_lt_b$in1[14] ),
    .B(\dpath.a_lt_b$in0[14] ),
    .Y(_011_)
  );
  sky130_fd_sc_hd__xnor2_2 _341_ (
    .A(\dpath.a_lt_b$in1[15] ),
    .B(\dpath.a_lt_b$in0[15] ),
    .Y(_012_)
  );
  sky130_fd_sc_hd__clkbuf_1 _342_ (
    .A(req_rdy),
    .X(_080_)
  );
  sky130_fd_sc_hd__clkbuf_1 _343_ (
    .A(_080_),
    .X(_081_)
  );
  sky130_fd_sc_hd__nand2_1 _344_ (
    .A(_081_),
    .B(req_val),
    .Y(_082_)
  );
  sky130_fd_sc_hd__nand4_1 _345_ (
    .A(_020_),
    .B(_021_),
    .C(_007_),
    .D(_012_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nand4_1 _346_ (
    .A(_008_),
    .B(_009_),
    .C(_010_),
    .D(_011_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__nand4_1 _347_ (
    .A(_006_),
    .B(_013_),
    .C(_014_),
    .D(_019_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__nand4_1 _348_ (
    .A(_015_),
    .B(_016_),
    .C(_017_),
    .D(_018_),
    .Y(_086_)
  );
  sky130_fd_sc_hd__o41a_1 _349_ (
    .A1(_083_),
    .A2(_084_),
    .A3(_085_),
    .A4(_086_),
    .B1(_005_),
    .X(_087_)
  );
  sky130_fd_sc_hd__nor4_1 _350_ (
    .A(\dpath.a_lt_b$in1[14] ),
    .B(\dpath.a_lt_b$in1[15] ),
    .C(\dpath.a_lt_b$in1[1] ),
    .D(_079_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__nor4_1 _351_ (
    .A(\dpath.a_lt_b$in1[2] ),
    .B(\dpath.a_lt_b$in1[3] ),
    .C(\dpath.a_lt_b$in1[4] ),
    .D(\dpath.a_lt_b$in1[5] ),
    .Y(_089_)
  );
  sky130_fd_sc_hd__nand2_1 _352_ (
    .A(_088_),
    .B(_089_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__nor4_1 _353_ (
    .A(\dpath.a_lt_b$in1[6] ),
    .B(\dpath.a_lt_b$in1[7] ),
    .C(\dpath.a_lt_b$in1[8] ),
    .D(\dpath.a_lt_b$in1[13] ),
    .Y(_091_)
  );
  sky130_fd_sc_hd__nor4_1 _354_ (
    .A(\dpath.a_lt_b$in1[9] ),
    .B(\dpath.a_lt_b$in1[10] ),
    .C(\dpath.a_lt_b$in1[11] ),
    .D(\dpath.a_lt_b$in1[12] ),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nand2_1 _355_ (
    .A(_091_),
    .B(_092_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__buf_1 _356_ (
    .A(\ctrl.state.out[2] ),
    .X(_094_)
  );
  sky130_fd_sc_hd__clkbuf_1 _357_ (
    .A(_094_),
    .X(_095_)
  );
  sky130_fd_sc_hd__o31ai_1 _358_ (
    .A1(_087_),
    .A2(_090_),
    .A3(_093_),
    .B1(_095_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__a21oi_1 _359_ (
    .A1(_082_),
    .A2(_096_),
    .B1(reset),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nor2_1 _360_ (
    .A(_080_),
    .B(_094_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__and2_1 _361_ (
    .A(\ctrl.state.out[1] ),
    .B(_097_),
    .X(resp_val)
  );
  sky130_fd_sc_hd__nor2b_1 _362_ (
    .A(req_val),
    .B_N(_080_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__a311o_1 _363_ (
    .A1(\ctrl.state.out[1] ),
    .A2(resp_rdy),
    .A3(_097_),
    .B1(_098_),
    .C1(reset),
    .X(_000_)
  );
  sky130_fd_sc_hd__o41ai_4 _364_ (
    .A1(_083_),
    .A2(_084_),
    .A3(_085_),
    .A4(_086_),
    .B1(_005_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__buf_2 _365_ (
    .A(_099_),
    .X(_100_)
  );
  sky130_fd_sc_hd__nor2_1 _366_ (
    .A(_090_),
    .B(_093_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__nand3_1 _367_ (
    .A(_095_),
    .B(_100_),
    .C(_101_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__nand2_1 _368_ (
    .A(resp_rdy),
    .B(_097_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__nand2_1 _369_ (
    .A(\ctrl.state.out[1] ),
    .B(_103_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__a21oi_1 _370_ (
    .A1(_102_),
    .A2(_104_),
    .B1(reset),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nor2b_1 _371_ (
    .A(req_rdy),
    .B_N(\ctrl.state.out[2] ),
    .Y(_105_)
  );
  sky130_fd_sc_hd__clkbuf_1 _372_ (
    .A(_105_),
    .X(_106_)
  );
  sky130_fd_sc_hd__nand2_1 _373_ (
    .A(_079_),
    .B(\dpath.a_lt_b$in0[0] ),
    .Y(_107_)
  );
  sky130_fd_sc_hd__mux2i_1 _374_ (
    .A0(_079_),
    .A1(_107_),
    .S(_099_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__clkbuf_1 _375_ (
    .A(_080_),
    .X(_109_)
  );
  sky130_fd_sc_hd__a21oi_1 _376_ (
    .A1(_079_),
    .A2(_094_),
    .B1(\dpath.a_lt_b$in0[0] ),
    .Y(_110_)
  );
  sky130_fd_sc_hd__nor2_1 _377_ (
    .A(_109_),
    .B(_110_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__a21oi_1 _378_ (
    .A1(_081_),
    .A2(req_msg[16]),
    .B1(_111_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__a21oi_1 _379_ (
    .A1(_106_),
    .A2(_108_),
    .B1(_112_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__clkbuf_1 _380_ (
    .A(req_rdy),
    .X(_113_)
  );
  sky130_fd_sc_hd__xor2_1 _381_ (
    .A(_036_),
    .B(_007_),
    .X(resp_msg[10])
  );
  sky130_fd_sc_hd__mux2i_1 _382_ (
    .A0(\dpath.a_lt_b$in0[10] ),
    .A1(resp_msg[10]),
    .S(\ctrl.state.out[2] ),
    .Y(_114_)
  );
  sky130_fd_sc_hd__clkbuf_1 _383_ (
    .A(req_rdy),
    .X(_115_)
  );
  sky130_fd_sc_hd__nand2_1 _384_ (
    .A(_115_),
    .B(req_msg[26]),
    .Y(_116_)
  );
  sky130_fd_sc_hd__o21a_1 _385_ (
    .A1(_113_),
    .A2(_114_),
    .B1(_116_),
    .X(_117_)
  );
  sky130_fd_sc_hd__nand2b_1 _386_ (
    .A_N(req_rdy),
    .B(\ctrl.state.out[2] ),
    .Y(_118_)
  );
  sky130_fd_sc_hd__nor2_1 _387_ (
    .A(_099_),
    .B(_118_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__clkbuf_1 _388_ (
    .A(_080_),
    .X(_120_)
  );
  sky130_fd_sc_hd__clkbuf_1 _389_ (
    .A(_087_),
    .X(_121_)
  );
  sky130_fd_sc_hd__nand4b_1 _390_ (
    .A_N(_120_),
    .B(_095_),
    .C(_121_),
    .D(\dpath.a_lt_b$in1[10] ),
    .Y(_122_)
  );
  sky130_fd_sc_hd__o21ai_0 _391_ (
    .A1(_117_),
    .A2(_119_),
    .B1(_122_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__clkbuf_1 _392_ (
    .A(_087_),
    .X(_123_)
  );
  sky130_fd_sc_hd__clkbuf_1 _393_ (
    .A(_105_),
    .X(_124_)
  );
  sky130_fd_sc_hd__or2_2 _394_ (
    .A(req_rdy),
    .B(\ctrl.state.out[2] ),
    .X(_125_)
  );
  sky130_fd_sc_hd__clkbuf_1 _395_ (
    .A(_125_),
    .X(_126_)
  );
  sky130_fd_sc_hd__nand2_1 _396_ (
    .A(_115_),
    .B(req_msg[27]),
    .Y(_127_)
  );
  sky130_fd_sc_hd__nand2_1 _397_ (
    .A(_126_),
    .B(_127_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__a31oi_1 _398_ (
    .A1(\dpath.a_lt_b$in1[11] ),
    .A2(_123_),
    .A3(_124_),
    .B1(_128_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__xor2_1 _399_ (
    .A(_023_),
    .B(_008_),
    .X(resp_msg[11])
  );
  sky130_fd_sc_hd__nand3_1 _400_ (
    .A(_100_),
    .B(_106_),
    .C(resp_msg[11]),
    .Y(_130_)
  );
  sky130_fd_sc_hd__clkbuf_1 _401_ (
    .A(_125_),
    .X(_131_)
  );
  sky130_fd_sc_hd__nor2_1 _402_ (
    .A(\dpath.a_lt_b$in0[11] ),
    .B(_131_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__a21oi_1 _403_ (
    .A1(_129_),
    .A2(_130_),
    .B1(_132_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nand2_1 _404_ (
    .A(_115_),
    .B(req_msg[28]),
    .Y(_133_)
  );
  sky130_fd_sc_hd__nand2_1 _405_ (
    .A(_126_),
    .B(_133_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__a31oi_1 _406_ (
    .A1(\dpath.a_lt_b$in1[12] ),
    .A2(_123_),
    .A3(_124_),
    .B1(_134_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__xor2_1 _407_ (
    .A(_024_),
    .B(_009_),
    .X(resp_msg[12])
  );
  sky130_fd_sc_hd__nand3_1 _408_ (
    .A(_100_),
    .B(_106_),
    .C(resp_msg[12]),
    .Y(_136_)
  );
  sky130_fd_sc_hd__nor2_1 _409_ (
    .A(\dpath.a_lt_b$in0[12] ),
    .B(_131_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__a21oi_1 _410_ (
    .A1(_135_),
    .A2(_136_),
    .B1(_137_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__clkbuf_1 _411_ (
    .A(_087_),
    .X(_138_)
  );
  sky130_fd_sc_hd__nand2_1 _412_ (
    .A(_115_),
    .B(req_msg[29]),
    .Y(_139_)
  );
  sky130_fd_sc_hd__nand2_1 _413_ (
    .A(_126_),
    .B(_139_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__a31oi_1 _414_ (
    .A1(\dpath.a_lt_b$in1[13] ),
    .A2(_138_),
    .A3(_124_),
    .B1(_140_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__xor2_1 _415_ (
    .A(_025_),
    .B(_010_),
    .X(resp_msg[13])
  );
  sky130_fd_sc_hd__nand3_1 _416_ (
    .A(_100_),
    .B(_106_),
    .C(resp_msg[13]),
    .Y(_142_)
  );
  sky130_fd_sc_hd__nor2_1 _417_ (
    .A(\dpath.a_lt_b$in0[13] ),
    .B(_131_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__a21oi_1 _418_ (
    .A1(_141_),
    .A2(_142_),
    .B1(_143_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__nand2_1 _419_ (
    .A(_113_),
    .B(req_msg[30]),
    .Y(_144_)
  );
  sky130_fd_sc_hd__nand2_1 _420_ (
    .A(_126_),
    .B(_144_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__a31oi_1 _421_ (
    .A1(\dpath.a_lt_b$in1[14] ),
    .A2(_123_),
    .A3(_124_),
    .B1(_145_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__xor2_1 _422_ (
    .A(_026_),
    .B(_011_),
    .X(resp_msg[14])
  );
  sky130_fd_sc_hd__nand3_1 _423_ (
    .A(_100_),
    .B(_106_),
    .C(resp_msg[14]),
    .Y(_147_)
  );
  sky130_fd_sc_hd__nor2_1 _424_ (
    .A(\dpath.a_lt_b$in0[14] ),
    .B(_131_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__a21oi_1 _425_ (
    .A1(_146_),
    .A2(_147_),
    .B1(_148_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__xor2_1 _426_ (
    .A(_027_),
    .B(_012_),
    .X(resp_msg[15])
  );
  sky130_fd_sc_hd__mux2i_1 _427_ (
    .A0(\dpath.a_lt_b$in0[15] ),
    .A1(resp_msg[15]),
    .S(_094_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__nand2_1 _428_ (
    .A(_113_),
    .B(req_msg[31]),
    .Y(_150_)
  );
  sky130_fd_sc_hd__o21a_1 _429_ (
    .A1(_113_),
    .A2(_149_),
    .B1(_150_),
    .X(_151_)
  );
  sky130_fd_sc_hd__nand4b_1 _430_ (
    .A_N(_109_),
    .B(_095_),
    .C(_121_),
    .D(\dpath.a_lt_b$in1[15] ),
    .Y(_152_)
  );
  sky130_fd_sc_hd__o21ai_0 _431_ (
    .A1(_119_),
    .A2(_151_),
    .B1(_152_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nand2_1 _432_ (
    .A(_115_),
    .B(req_msg[17]),
    .Y(_153_)
  );
  sky130_fd_sc_hd__nand2_1 _433_ (
    .A(_126_),
    .B(_153_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__a31oi_1 _434_ (
    .A1(\dpath.a_lt_b$in1[1] ),
    .A2(_123_),
    .A3(_105_),
    .B1(_154_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__buf_1 _435_ (
    .A(_105_),
    .X(_156_)
  );
  sky130_fd_sc_hd__xor2_1 _436_ (
    .A(_022_),
    .B(_013_),
    .X(resp_msg[1])
  );
  sky130_fd_sc_hd__nand3_1 _437_ (
    .A(_099_),
    .B(_156_),
    .C(resp_msg[1]),
    .Y(_157_)
  );
  sky130_fd_sc_hd__nor2_1 _438_ (
    .A(\dpath.a_lt_b$in0[1] ),
    .B(_131_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__a21oi_1 _439_ (
    .A1(_155_),
    .A2(_157_),
    .B1(_158_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__nand2_1 _440_ (
    .A(_115_),
    .B(req_msg[18]),
    .Y(_159_)
  );
  sky130_fd_sc_hd__nand2_1 _441_ (
    .A(_126_),
    .B(_159_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__a31oi_1 _442_ (
    .A1(\dpath.a_lt_b$in1[2] ),
    .A2(_123_),
    .A3(_124_),
    .B1(_160_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__xor2_1 _443_ (
    .A(_028_),
    .B(_014_),
    .X(resp_msg[2])
  );
  sky130_fd_sc_hd__nand3_1 _444_ (
    .A(_100_),
    .B(_106_),
    .C(resp_msg[2]),
    .Y(_162_)
  );
  sky130_fd_sc_hd__nor2_1 _445_ (
    .A(\dpath.a_lt_b$in0[2] ),
    .B(_131_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__a21oi_1 _446_ (
    .A1(_161_),
    .A2(_162_),
    .B1(_163_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nand2_1 _447_ (
    .A(_115_),
    .B(req_msg[19]),
    .Y(_164_)
  );
  sky130_fd_sc_hd__nand2_1 _448_ (
    .A(_126_),
    .B(_164_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__a31oi_1 _449_ (
    .A1(\dpath.a_lt_b$in1[3] ),
    .A2(_123_),
    .A3(_124_),
    .B1(_165_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__xor2_1 _450_ (
    .A(_029_),
    .B(_015_),
    .X(resp_msg[3])
  );
  sky130_fd_sc_hd__nand3_1 _451_ (
    .A(_100_),
    .B(_106_),
    .C(resp_msg[3]),
    .Y(_167_)
  );
  sky130_fd_sc_hd__nor2_1 _452_ (
    .A(\dpath.a_lt_b$in0[3] ),
    .B(_131_),
    .Y(_168_)
  );
  sky130_fd_sc_hd__a21oi_1 _453_ (
    .A1(_166_),
    .A2(_167_),
    .B1(_168_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nand2_1 _454_ (
    .A(_115_),
    .B(req_msg[20]),
    .Y(_169_)
  );
  sky130_fd_sc_hd__nand2_1 _455_ (
    .A(_126_),
    .B(_169_),
    .Y(_170_)
  );
  sky130_fd_sc_hd__a31oi_1 _456_ (
    .A1(\dpath.a_lt_b$in1[4] ),
    .A2(_123_),
    .A3(_124_),
    .B1(_170_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__xor2_1 _457_ (
    .A(_030_),
    .B(_016_),
    .X(resp_msg[4])
  );
  sky130_fd_sc_hd__nand3_1 _458_ (
    .A(_100_),
    .B(_106_),
    .C(resp_msg[4]),
    .Y(_172_)
  );
  sky130_fd_sc_hd__nor2_1 _459_ (
    .A(\dpath.a_lt_b$in0[4] ),
    .B(_131_),
    .Y(_173_)
  );
  sky130_fd_sc_hd__a21oi_1 _460_ (
    .A1(_171_),
    .A2(_172_),
    .B1(_173_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__nand2_1 _461_ (
    .A(_115_),
    .B(req_msg[21]),
    .Y(_174_)
  );
  sky130_fd_sc_hd__nand2_1 _462_ (
    .A(_126_),
    .B(_174_),
    .Y(_175_)
  );
  sky130_fd_sc_hd__a31oi_1 _463_ (
    .A1(\dpath.a_lt_b$in1[5] ),
    .A2(_123_),
    .A3(_124_),
    .B1(_175_),
    .Y(_176_)
  );
  sky130_fd_sc_hd__xor2_1 _464_ (
    .A(_031_),
    .B(_017_),
    .X(resp_msg[5])
  );
  sky130_fd_sc_hd__nand3_1 _465_ (
    .A(_100_),
    .B(_106_),
    .C(resp_msg[5]),
    .Y(_177_)
  );
  sky130_fd_sc_hd__nor2_1 _466_ (
    .A(\dpath.a_lt_b$in0[5] ),
    .B(_131_),
    .Y(_178_)
  );
  sky130_fd_sc_hd__a21oi_1 _467_ (
    .A1(_176_),
    .A2(_177_),
    .B1(_178_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nand2_1 _468_ (
    .A(_115_),
    .B(req_msg[22]),
    .Y(_179_)
  );
  sky130_fd_sc_hd__nand2_1 _469_ (
    .A(_126_),
    .B(_179_),
    .Y(_180_)
  );
  sky130_fd_sc_hd__a31oi_1 _470_ (
    .A1(\dpath.a_lt_b$in1[6] ),
    .A2(_123_),
    .A3(_124_),
    .B1(_180_),
    .Y(_181_)
  );
  sky130_fd_sc_hd__xor2_1 _471_ (
    .A(_032_),
    .B(_018_),
    .X(resp_msg[6])
  );
  sky130_fd_sc_hd__nand3_1 _472_ (
    .A(_100_),
    .B(_106_),
    .C(resp_msg[6]),
    .Y(_182_)
  );
  sky130_fd_sc_hd__nor2_1 _473_ (
    .A(\dpath.a_lt_b$in0[6] ),
    .B(_131_),
    .Y(_183_)
  );
  sky130_fd_sc_hd__a21oi_1 _474_ (
    .A1(_181_),
    .A2(_182_),
    .B1(_183_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__clkbuf_1 _475_ (
    .A(_080_),
    .X(_184_)
  );
  sky130_fd_sc_hd__xor2_1 _476_ (
    .A(_033_),
    .B(_019_),
    .X(resp_msg[7])
  );
  sky130_fd_sc_hd__mux2i_1 _477_ (
    .A0(\dpath.a_lt_b$in0[7] ),
    .A1(resp_msg[7]),
    .S(_094_),
    .Y(_185_)
  );
  sky130_fd_sc_hd__nand2_1 _478_ (
    .A(_113_),
    .B(req_msg[23]),
    .Y(_186_)
  );
  sky130_fd_sc_hd__o21a_1 _479_ (
    .A1(_184_),
    .A2(_185_),
    .B1(_186_),
    .X(_187_)
  );
  sky130_fd_sc_hd__nand4b_1 _480_ (
    .A_N(_109_),
    .B(_095_),
    .C(_121_),
    .D(\dpath.a_lt_b$in1[7] ),
    .Y(_188_)
  );
  sky130_fd_sc_hd__o21ai_0 _481_ (
    .A1(_119_),
    .A2(_187_),
    .B1(_188_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__xor2_1 _482_ (
    .A(_034_),
    .B(_020_),
    .X(resp_msg[8])
  );
  sky130_fd_sc_hd__mux2i_1 _483_ (
    .A0(\dpath.a_lt_b$in0[8] ),
    .A1(resp_msg[8]),
    .S(_094_),
    .Y(_189_)
  );
  sky130_fd_sc_hd__nand2_1 _484_ (
    .A(_113_),
    .B(req_msg[24]),
    .Y(_190_)
  );
  sky130_fd_sc_hd__o21a_1 _485_ (
    .A1(_184_),
    .A2(_189_),
    .B1(_190_),
    .X(_191_)
  );
  sky130_fd_sc_hd__nand4b_1 _486_ (
    .A_N(_109_),
    .B(_095_),
    .C(_121_),
    .D(\dpath.a_lt_b$in1[8] ),
    .Y(_192_)
  );
  sky130_fd_sc_hd__o21ai_0 _487_ (
    .A1(_119_),
    .A2(_191_),
    .B1(_192_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__xor2_1 _488_ (
    .A(_035_),
    .B(_021_),
    .X(resp_msg[9])
  );
  sky130_fd_sc_hd__mux2i_1 _489_ (
    .A0(\dpath.a_lt_b$in0[9] ),
    .A1(resp_msg[9]),
    .S(_094_),
    .Y(_193_)
  );
  sky130_fd_sc_hd__nand2_1 _490_ (
    .A(_113_),
    .B(req_msg[25]),
    .Y(_194_)
  );
  sky130_fd_sc_hd__o21a_1 _491_ (
    .A1(_113_),
    .A2(_193_),
    .B1(_194_),
    .X(_195_)
  );
  sky130_fd_sc_hd__nand4b_1 _492_ (
    .A_N(_120_),
    .B(_095_),
    .C(_121_),
    .D(\dpath.a_lt_b$in1[9] ),
    .Y(_196_)
  );
  sky130_fd_sc_hd__o21ai_0 _493_ (
    .A1(_119_),
    .A2(_195_),
    .B1(_196_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__and2_4 _494_ (
    .A(\ctrl.state.out[2] ),
    .B(_087_),
    .X(_197_)
  );
  sky130_fd_sc_hd__buf_6 _495_ (
    .A(_197_),
    .X(_198_)
  );
  sky130_fd_sc_hd__nand2b_1 _496_ (
    .A_N(_080_),
    .B(_079_),
    .Y(_199_)
  );
  sky130_fd_sc_hd__nand4b_1 _497_ (
    .A_N(_109_),
    .B(_095_),
    .C(_121_),
    .D(\dpath.a_lt_b$in0[0] ),
    .Y(_200_)
  );
  sky130_fd_sc_hd__nand2_1 _498_ (
    .A(_081_),
    .B(req_msg[0]),
    .Y(_201_)
  );
  sky130_fd_sc_hd__o211ai_1 _499_ (
    .A1(_198_),
    .A2(_199_),
    .B1(_200_),
    .C1(_201_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nand2_1 _500_ (
    .A(_120_),
    .B(req_msg[10]),
    .Y(_202_)
  );
  sky130_fd_sc_hd__nand3_1 _501_ (
    .A(\dpath.a_lt_b$in0[10] ),
    .B(_138_),
    .C(_156_),
    .Y(_203_)
  );
  sky130_fd_sc_hd__o311ai_2 _502_ (
    .A1(_076_),
    .A2(_184_),
    .A3(_198_),
    .B1(_202_),
    .C1(_203_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__nor2b_1 _503_ (
    .A(req_msg[11]),
    .B_N(_113_),
    .Y(_204_)
  );
  sky130_fd_sc_hd__nor3_1 _504_ (
    .A(\dpath.a_lt_b$in0[11] ),
    .B(_099_),
    .C(_118_),
    .Y(_205_)
  );
  sky130_fd_sc_hd__a211oi_1 _505_ (
    .A1(_094_),
    .A2(_087_),
    .B1(\dpath.a_lt_b$in1[11] ),
    .C1(_120_),
    .Y(_206_)
  );
  sky130_fd_sc_hd__nor3_1 _506_ (
    .A(_204_),
    .B(_205_),
    .C(_206_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nand2_1 _507_ (
    .A(_081_),
    .B(req_msg[12]),
    .Y(_207_)
  );
  sky130_fd_sc_hd__nand3_1 _508_ (
    .A(\dpath.a_lt_b$in0[12] ),
    .B(_138_),
    .C(_156_),
    .Y(_208_)
  );
  sky130_fd_sc_hd__o311ai_2 _509_ (
    .A1(_077_),
    .A2(_184_),
    .A3(_198_),
    .B1(_207_),
    .C1(_208_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nand2b_1 _510_ (
    .A_N(_080_),
    .B(\dpath.a_lt_b$in1[13] ),
    .Y(_209_)
  );
  sky130_fd_sc_hd__nand4b_1 _511_ (
    .A_N(_109_),
    .B(_094_),
    .C(_121_),
    .D(\dpath.a_lt_b$in0[13] ),
    .Y(_210_)
  );
  sky130_fd_sc_hd__nand2_1 _512_ (
    .A(_081_),
    .B(req_msg[13]),
    .Y(_211_)
  );
  sky130_fd_sc_hd__o211ai_1 _513_ (
    .A1(_198_),
    .A2(_209_),
    .B1(_210_),
    .C1(_211_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__nand2b_1 _514_ (
    .A_N(_080_),
    .B(\dpath.a_lt_b$in1[14] ),
    .Y(_212_)
  );
  sky130_fd_sc_hd__nand4b_1 _515_ (
    .A_N(_109_),
    .B(_095_),
    .C(_121_),
    .D(\dpath.a_lt_b$in0[14] ),
    .Y(_213_)
  );
  sky130_fd_sc_hd__nand2_1 _516_ (
    .A(_081_),
    .B(req_msg[14]),
    .Y(_214_)
  );
  sky130_fd_sc_hd__o211ai_1 _517_ (
    .A1(_198_),
    .A2(_212_),
    .B1(_213_),
    .C1(_214_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nand2_1 _518_ (
    .A(_120_),
    .B(req_msg[15]),
    .Y(_215_)
  );
  sky130_fd_sc_hd__nand3_1 _519_ (
    .A(\dpath.a_lt_b$in0[15] ),
    .B(_121_),
    .C(_156_),
    .Y(_216_)
  );
  sky130_fd_sc_hd__o311ai_2 _520_ (
    .A1(_078_),
    .A2(_184_),
    .A3(_198_),
    .B1(_215_),
    .C1(_216_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nand2_1 _521_ (
    .A(_120_),
    .B(req_msg[1]),
    .Y(_217_)
  );
  sky130_fd_sc_hd__nand3_1 _522_ (
    .A(\dpath.a_lt_b$in0[1] ),
    .B(_138_),
    .C(_156_),
    .Y(_218_)
  );
  sky130_fd_sc_hd__o311ai_2 _523_ (
    .A1(_069_),
    .A2(_184_),
    .A3(_198_),
    .B1(_217_),
    .C1(_218_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nand2b_1 _524_ (
    .A_N(_080_),
    .B(\dpath.a_lt_b$in1[2] ),
    .Y(_219_)
  );
  sky130_fd_sc_hd__nand4b_1 _525_ (
    .A_N(_109_),
    .B(_095_),
    .C(_121_),
    .D(\dpath.a_lt_b$in0[2] ),
    .Y(_220_)
  );
  sky130_fd_sc_hd__nand2_1 _526_ (
    .A(_081_),
    .B(req_msg[2]),
    .Y(_221_)
  );
  sky130_fd_sc_hd__o211ai_1 _527_ (
    .A1(_198_),
    .A2(_219_),
    .B1(_220_),
    .C1(_221_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nand2_1 _528_ (
    .A(_120_),
    .B(req_msg[3]),
    .Y(_222_)
  );
  sky130_fd_sc_hd__nand3_1 _529_ (
    .A(\dpath.a_lt_b$in0[3] ),
    .B(_138_),
    .C(_156_),
    .Y(_223_)
  );
  sky130_fd_sc_hd__o311ai_2 _530_ (
    .A1(_070_),
    .A2(_184_),
    .A3(_198_),
    .B1(_222_),
    .C1(_223_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__nand2_1 _531_ (
    .A(_081_),
    .B(req_msg[4]),
    .Y(_224_)
  );
  sky130_fd_sc_hd__nand3_1 _532_ (
    .A(\dpath.a_lt_b$in0[4] ),
    .B(_138_),
    .C(_156_),
    .Y(_225_)
  );
  sky130_fd_sc_hd__o311ai_1 _533_ (
    .A1(_071_),
    .A2(_184_),
    .A3(_197_),
    .B1(_224_),
    .C1(_225_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__nor2b_1 _534_ (
    .A(req_msg[5]),
    .B_N(_113_),
    .Y(_226_)
  );
  sky130_fd_sc_hd__nor3_1 _535_ (
    .A(\dpath.a_lt_b$in0[5] ),
    .B(_099_),
    .C(_118_),
    .Y(_227_)
  );
  sky130_fd_sc_hd__a211oi_1 _536_ (
    .A1(_094_),
    .A2(_123_),
    .B1(\dpath.a_lt_b$in1[5] ),
    .C1(_120_),
    .Y(_228_)
  );
  sky130_fd_sc_hd__nor3_1 _537_ (
    .A(_226_),
    .B(_227_),
    .C(_228_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nand2_1 _538_ (
    .A(_120_),
    .B(req_msg[6]),
    .Y(_229_)
  );
  sky130_fd_sc_hd__nand3_1 _539_ (
    .A(\dpath.a_lt_b$in0[6] ),
    .B(_138_),
    .C(_156_),
    .Y(_230_)
  );
  sky130_fd_sc_hd__o311ai_1 _540_ (
    .A1(_072_),
    .A2(_184_),
    .A3(_197_),
    .B1(_229_),
    .C1(_230_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__nand2_1 _541_ (
    .A(_081_),
    .B(req_msg[7]),
    .Y(_231_)
  );
  sky130_fd_sc_hd__nand3_1 _542_ (
    .A(\dpath.a_lt_b$in0[7] ),
    .B(_138_),
    .C(_156_),
    .Y(_232_)
  );
  sky130_fd_sc_hd__o311ai_1 _543_ (
    .A1(_073_),
    .A2(_109_),
    .A3(_197_),
    .B1(_231_),
    .C1(_232_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nand2_1 _544_ (
    .A(_120_),
    .B(req_msg[8]),
    .Y(_233_)
  );
  sky130_fd_sc_hd__nand3_1 _545_ (
    .A(\dpath.a_lt_b$in0[8] ),
    .B(_138_),
    .C(_156_),
    .Y(_234_)
  );
  sky130_fd_sc_hd__o311ai_1 _546_ (
    .A1(_074_),
    .A2(_109_),
    .A3(_197_),
    .B1(_233_),
    .C1(_234_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nand2_1 _547_ (
    .A(_081_),
    .B(req_msg[9]),
    .Y(_235_)
  );
  sky130_fd_sc_hd__nand3_1 _548_ (
    .A(\dpath.a_lt_b$in0[9] ),
    .B(_138_),
    .C(_124_),
    .Y(_236_)
  );
  sky130_fd_sc_hd__o311ai_2 _549_ (
    .A1(_075_),
    .A2(_184_),
    .A3(_198_),
    .B1(_235_),
    .C1(_236_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__inv_1 _550_ (
    .A(_006_),
    .Y(resp_msg[0])
  );
  (* implements_operator = "LCU_16" *)
  (* src = "./designs/src/gcd/gcd.v:607.12-607.21|/Users/pk/repos/yosys/share/techmap.v:286.27-286.69|/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_nomap.v:14.23-14.96|/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_export_rename.v:15.24-15.64" *)
  (* unmapped_operator = 32'b00000000000000000000000000000001 *)
  LCU_16_BRENT_KUNG _551_ (
    .CO({ _005_, _272_, _271_, _270_, _269_, _268_, _281_, _280_, _279_, _278_, _277_, _276_, _275_, _274_, _273_, _267_ }),
    .G({ _242_, _241_, _240_, _239_, _238_, _237_, _251_, _250_, _249_, _248_, _247_, _246_, _245_, _244_, _243_, _003_ }),
    .P({ _012_, _011_, _010_, _009_, _008_, _007_, _021_, _020_, _019_, _018_, _017_, _016_, _015_, _014_, _013_, _006_ })
  );
  (* implements_operator = "LCU_16" *)
  (* src = "./designs/src/gcd/gcd.v:752.12-752.19|/Users/pk/repos/yosys/share/techmap.v:286.27-286.69|/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_nomap.v:14.23-14.96|/Users/pk/repos/OpenROAD-flow-scripts/flow/scripts/lcu_export_rename.v:15.24-15.64" *)
  (* unmapped_operator = 32'b00000000000000000000000000000001 *)
  LCU_16_KOGGE_STONE _552_ (
    .CO({ _282_, _027_, _026_, _025_, _024_, _023_, _036_, _035_, _034_, _033_, _032_, _031_, _030_, _029_, _028_, _022_ }),
    .G({ _257_, _256_, _255_, _254_, _253_, _252_, _266_, _265_, _264_, _263_, _262_, _261_, _260_, _259_, _258_, _004_ }),
    .P({ _012_, _011_, _010_, _009_, _008_, _007_, _021_, _020_, _019_, _018_, _017_, _016_, _015_, _014_, _013_, _006_ })
  );
  sky130_fd_sc_hd__dfxtp_1 \ctrl.state.out[0]$_DFF_P_  (
    .CLK(clk),
    .D(_000_),
    .Q(req_rdy)
  );
  sky130_fd_sc_hd__dfxtp_1 \ctrl.state.out[1]$_DFF_P_  (
    .CLK(clk),
    .D(_001_),
    .Q(\ctrl.state.out[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 \ctrl.state.out[2]$_DFF_P_  (
    .CLK(clk),
    .D(_002_),
    .Q(\ctrl.state.out[2] )
  );
  (* src = "./designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__dfxtp_1 \dpath.a_reg.out[0]$_DFFE_PP_  (
    .CLK(clk),
    .D(_037_),
    .Q(\dpath.a_lt_b$in0[0] )
  );
  (* src = "./designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__dfxtp_1 \dpath.a_reg.out[10]$_DFFE_PP_  (
    .CLK(clk),
    .D(_038_),
    .Q(\dpath.a_lt_b$in0[10] )
  );
  (* src = "./designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__dfxtp_1 \dpath.a_reg.out[11]$_DFFE_PP_  (
    .CLK(clk),
    .D(_039_),
    .Q(\dpath.a_lt_b$in0[11] )
  );
  (* src = "./designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__dfxtp_1 \dpath.a_reg.out[12]$_DFFE_PP_  (
    .CLK(clk),
    .D(_040_),
    .Q(\dpath.a_lt_b$in0[12] )
  );
  (* src = "./designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__dfxtp_1 \dpath.a_reg.out[13]$_DFFE_PP_  (
    .CLK(clk),
    .D(_041_),
    .Q(\dpath.a_lt_b$in0[13] )
  );
  (* src = "./designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__dfxtp_1 \dpath.a_reg.out[14]$_DFFE_PP_  (
    .CLK(clk),
    .D(_042_),
    .Q(\dpath.a_lt_b$in0[14] )
  );
  (* src = "./designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__dfxtp_1 \dpath.a_reg.out[15]$_DFFE_PP_  (
    .CLK(clk),
    .D(_043_),
    .Q(\dpath.a_lt_b$in0[15] )
  );
  (* src = "./designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__dfxtp_1 \dpath.a_reg.out[1]$_DFFE_PP_  (
    .CLK(clk),
    .D(_044_),
    .Q(\dpath.a_lt_b$in0[1] )
  );
  (* src = "./designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__dfxtp_1 \dpath.a_reg.out[2]$_DFFE_PP_  (
    .CLK(clk),
    .D(_045_),
    .Q(\dpath.a_lt_b$in0[2] )
  );
  (* src = "./designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__dfxtp_1 \dpath.a_reg.out[3]$_DFFE_PP_  (
    .CLK(clk),
    .D(_046_),
    .Q(\dpath.a_lt_b$in0[3] )
  );
  (* src = "./designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__dfxtp_1 \dpath.a_reg.out[4]$_DFFE_PP_  (
    .CLK(clk),
    .D(_047_),
    .Q(\dpath.a_lt_b$in0[4] )
  );
  (* src = "./designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__dfxtp_1 \dpath.a_reg.out[5]$_DFFE_PP_  (
    .CLK(clk),
    .D(_048_),
    .Q(\dpath.a_lt_b$in0[5] )
  );
  (* src = "./designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__dfxtp_1 \dpath.a_reg.out[6]$_DFFE_PP_  (
    .CLK(clk),
    .D(_049_),
    .Q(\dpath.a_lt_b$in0[6] )
  );
  (* src = "./designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__dfxtp_1 \dpath.a_reg.out[7]$_DFFE_PP_  (
    .CLK(clk),
    .D(_050_),
    .Q(\dpath.a_lt_b$in0[7] )
  );
  (* src = "./designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__dfxtp_1 \dpath.a_reg.out[8]$_DFFE_PP_  (
    .CLK(clk),
    .D(_051_),
    .Q(\dpath.a_lt_b$in0[8] )
  );
  (* src = "./designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__dfxtp_1 \dpath.a_reg.out[9]$_DFFE_PP_  (
    .CLK(clk),
    .D(_052_),
    .Q(\dpath.a_lt_b$in0[9] )
  );
  (* src = "./designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__dfxtp_1 \dpath.b_reg.out[0]$_DFFE_PP_  (
    .CLK(clk),
    .D(_053_),
    .Q(\dpath.a_lt_b$in1[0] )
  );
  (* src = "./designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__dfxtp_1 \dpath.b_reg.out[10]$_DFFE_PP_  (
    .CLK(clk),
    .D(_054_),
    .Q(\dpath.a_lt_b$in1[10] )
  );
  (* src = "./designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__dfxtp_1 \dpath.b_reg.out[11]$_DFFE_PP_  (
    .CLK(clk),
    .D(_055_),
    .Q(\dpath.a_lt_b$in1[11] )
  );
  (* src = "./designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__dfxtp_1 \dpath.b_reg.out[12]$_DFFE_PP_  (
    .CLK(clk),
    .D(_056_),
    .Q(\dpath.a_lt_b$in1[12] )
  );
  (* src = "./designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__dfxtp_1 \dpath.b_reg.out[13]$_DFFE_PP_  (
    .CLK(clk),
    .D(_057_),
    .Q(\dpath.a_lt_b$in1[13] )
  );
  (* src = "./designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__dfxtp_1 \dpath.b_reg.out[14]$_DFFE_PP_  (
    .CLK(clk),
    .D(_058_),
    .Q(\dpath.a_lt_b$in1[14] )
  );
  (* src = "./designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__dfxtp_1 \dpath.b_reg.out[15]$_DFFE_PP_  (
    .CLK(clk),
    .D(_059_),
    .Q(\dpath.a_lt_b$in1[15] )
  );
  (* src = "./designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__dfxtp_1 \dpath.b_reg.out[1]$_DFFE_PP_  (
    .CLK(clk),
    .D(_060_),
    .Q(\dpath.a_lt_b$in1[1] )
  );
  (* src = "./designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__dfxtp_1 \dpath.b_reg.out[2]$_DFFE_PP_  (
    .CLK(clk),
    .D(_061_),
    .Q(\dpath.a_lt_b$in1[2] )
  );
  (* src = "./designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__dfxtp_1 \dpath.b_reg.out[3]$_DFFE_PP_  (
    .CLK(clk),
    .D(_062_),
    .Q(\dpath.a_lt_b$in1[3] )
  );
  (* src = "./designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__dfxtp_1 \dpath.b_reg.out[4]$_DFFE_PP_  (
    .CLK(clk),
    .D(_063_),
    .Q(\dpath.a_lt_b$in1[4] )
  );
  (* src = "./designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__dfxtp_1 \dpath.b_reg.out[5]$_DFFE_PP_  (
    .CLK(clk),
    .D(_064_),
    .Q(\dpath.a_lt_b$in1[5] )
  );
  (* src = "./designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__dfxtp_1 \dpath.b_reg.out[6]$_DFFE_PP_  (
    .CLK(clk),
    .D(_065_),
    .Q(\dpath.a_lt_b$in1[6] )
  );
  (* src = "./designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__dfxtp_1 \dpath.b_reg.out[7]$_DFFE_PP_  (
    .CLK(clk),
    .D(_066_),
    .Q(\dpath.a_lt_b$in1[7] )
  );
  (* src = "./designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__dfxtp_1 \dpath.b_reg.out[8]$_DFFE_PP_  (
    .CLK(clk),
    .D(_067_),
    .Q(\dpath.a_lt_b$in1[8] )
  );
  (* src = "./designs/src/gcd/gcd.v:571.3-577.6" *)
  sky130_fd_sc_hd__dfxtp_1 \dpath.b_reg.out[9]$_DFFE_PP_  (
    .CLK(clk),
    .D(_068_),
    .Q(\dpath.a_lt_b$in1[9] )
  );
endmodule
