pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        sh './jenkins/coverage/build.sh'
      }
    }
    stage('Coverage') {
      steps {
        sh './jenkins/coverage/coverage.sh'
        publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: 'coverage-output', reportFiles: 'index.html', reportName: 'Code Coverage', reportTitles: ''])
      }
    }
  }
}
