# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.0
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError('Python 2.7 or later required')

# Import the low-level C/C++ module
if __package__ or '.' in __name__:
    from . import _pdn_py
else:
    import _pdn_py

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if name == "thisown":
        return self.this.own(value)
    if name == "this":
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if not static:
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if name == "thisown":
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _pdn_py.delete_SwigPyIterator

    def value(self):
        return _pdn_py.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _pdn_py.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _pdn_py.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _pdn_py.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _pdn_py.SwigPyIterator_equal(self, x)

    def copy(self):
        return _pdn_py.SwigPyIterator_copy(self)

    def next(self):
        return _pdn_py.SwigPyIterator_next(self)

    def __next__(self):
        return _pdn_py.SwigPyIterator___next__(self)

    def previous(self):
        return _pdn_py.SwigPyIterator_previous(self)

    def advance(self, n):
        return _pdn_py.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _pdn_py.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _pdn_py.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _pdn_py.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _pdn_py.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _pdn_py.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _pdn_py.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _pdn_py:
_pdn_py.SwigPyIterator_swigregister(SwigPyIterator)

class split_cuts_stuff(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def iterator(self):
        return _pdn_py.split_cuts_stuff_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pdn_py.split_cuts_stuff___nonzero__(self)

    def __bool__(self):
        return _pdn_py.split_cuts_stuff___bool__(self)

    def __len__(self):
        return _pdn_py.split_cuts_stuff___len__(self)

    def __getslice__(self, i, j):
        return _pdn_py.split_cuts_stuff___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pdn_py.split_cuts_stuff___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pdn_py.split_cuts_stuff___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pdn_py.split_cuts_stuff___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pdn_py.split_cuts_stuff___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pdn_py.split_cuts_stuff___setitem__(self, *args)

    def pop(self):
        return _pdn_py.split_cuts_stuff_pop(self)

    def append(self, x):
        return _pdn_py.split_cuts_stuff_append(self, x)

    def empty(self):
        return _pdn_py.split_cuts_stuff_empty(self)

    def size(self):
        return _pdn_py.split_cuts_stuff_size(self)

    def swap(self, v):
        return _pdn_py.split_cuts_stuff_swap(self, v)

    def begin(self):
        return _pdn_py.split_cuts_stuff_begin(self)

    def end(self):
        return _pdn_py.split_cuts_stuff_end(self)

    def rbegin(self):
        return _pdn_py.split_cuts_stuff_rbegin(self)

    def rend(self):
        return _pdn_py.split_cuts_stuff_rend(self)

    def clear(self):
        return _pdn_py.split_cuts_stuff_clear(self)

    def get_allocator(self):
        return _pdn_py.split_cuts_stuff_get_allocator(self)

    def pop_back(self):
        return _pdn_py.split_cuts_stuff_pop_back(self)

    def erase(self, *args):
        return _pdn_py.split_cuts_stuff_erase(self, *args)

    def __init__(self, *args):
        _pdn_py.split_cuts_stuff_swiginit(self, _pdn_py.new_split_cuts_stuff(*args))

    def push_back(self, x):
        return _pdn_py.split_cuts_stuff_push_back(self, x)

    def front(self):
        return _pdn_py.split_cuts_stuff_front(self)

    def back(self):
        return _pdn_py.split_cuts_stuff_back(self)

    def assign(self, n, x):
        return _pdn_py.split_cuts_stuff_assign(self, n, x)

    def resize(self, *args):
        return _pdn_py.split_cuts_stuff_resize(self, *args)

    def insert(self, *args):
        return _pdn_py.split_cuts_stuff_insert(self, *args)

    def reserve(self, n):
        return _pdn_py.split_cuts_stuff_reserve(self, n)

    def capacity(self):
        return _pdn_py.split_cuts_stuff_capacity(self)
    __swig_destroy__ = _pdn_py.delete_split_cuts_stuff

# Register split_cuts_stuff in _pdn_py:
_pdn_py.split_cuts_stuff_swigregister(split_cuts_stuff)

class stuff(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def iterator(self):
        return _pdn_py.stuff_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pdn_py.stuff___nonzero__(self)

    def __bool__(self):
        return _pdn_py.stuff___bool__(self)

    def __len__(self):
        return _pdn_py.stuff___len__(self)

    def __getslice__(self, i, j):
        return _pdn_py.stuff___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pdn_py.stuff___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pdn_py.stuff___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pdn_py.stuff___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pdn_py.stuff___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pdn_py.stuff___setitem__(self, *args)

    def __init__(self, *args):
        _pdn_py.stuff_swiginit(self, _pdn_py.new_stuff(*args))

    def empty(self):
        return _pdn_py.stuff_empty(self)

    def size(self):
        return _pdn_py.stuff_size(self)

    def swap(self, v):
        return _pdn_py.stuff_swap(self, v)

    def begin(self):
        return _pdn_py.stuff_begin(self)

    def end(self):
        return _pdn_py.stuff_end(self)

    def rbegin(self):
        return _pdn_py.stuff_rbegin(self)

    def rend(self):
        return _pdn_py.stuff_rend(self)

    def front(self):
        return _pdn_py.stuff_front(self)

    def back(self):
        return _pdn_py.stuff_back(self)

    def fill(self, u):
        return _pdn_py.stuff_fill(self, u)
    __swig_destroy__ = _pdn_py.delete_stuff

# Register stuff in _pdn_py:
_pdn_py.stuff_swigregister(stuff)

class split_map(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def iterator(self):
        return _pdn_py.split_map_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pdn_py.split_map___nonzero__(self)

    def __bool__(self):
        return _pdn_py.split_map___bool__(self)

    def __len__(self):
        return _pdn_py.split_map___len__(self)
    def __iter__(self):
        return self.key_iterator()
    def iterkeys(self):
        return self.key_iterator()
    def itervalues(self):
        return self.value_iterator()
    def iteritems(self):
        return self.iterator()

    def __getitem__(self, key):
        return _pdn_py.split_map___getitem__(self, key)

    def __delitem__(self, key):
        return _pdn_py.split_map___delitem__(self, key)

    def has_key(self, key):
        return _pdn_py.split_map_has_key(self, key)

    def keys(self):
        return _pdn_py.split_map_keys(self)

    def values(self):
        return _pdn_py.split_map_values(self)

    def items(self):
        return _pdn_py.split_map_items(self)

    def __contains__(self, key):
        return _pdn_py.split_map___contains__(self, key)

    def key_iterator(self):
        return _pdn_py.split_map_key_iterator(self)

    def value_iterator(self):
        return _pdn_py.split_map_value_iterator(self)

    def __setitem__(self, *args):
        return _pdn_py.split_map___setitem__(self, *args)

    def asdict(self):
        return _pdn_py.split_map_asdict(self)

    def __init__(self, *args):
        _pdn_py.split_map_swiginit(self, _pdn_py.new_split_map(*args))

    def empty(self):
        return _pdn_py.split_map_empty(self)

    def size(self):
        return _pdn_py.split_map_size(self)

    def swap(self, v):
        return _pdn_py.split_map_swap(self, v)

    def begin(self):
        return _pdn_py.split_map_begin(self)

    def end(self):
        return _pdn_py.split_map_end(self)

    def rbegin(self):
        return _pdn_py.split_map_rbegin(self)

    def rend(self):
        return _pdn_py.split_map_rend(self)

    def clear(self):
        return _pdn_py.split_map_clear(self)

    def get_allocator(self):
        return _pdn_py.split_map_get_allocator(self)

    def count(self, x):
        return _pdn_py.split_map_count(self, x)

    def erase(self, *args):
        return _pdn_py.split_map_erase(self, *args)

    def find(self, x):
        return _pdn_py.split_map_find(self, x)

    def lower_bound(self, x):
        return _pdn_py.split_map_lower_bound(self, x)

    def upper_bound(self, x):
        return _pdn_py.split_map_upper_bound(self, x)
    __swig_destroy__ = _pdn_py.delete_split_map

# Register split_map in _pdn_py:
_pdn_py.split_map_swigregister(split_map)

class grid_list(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def iterator(self):
        return _pdn_py.grid_list_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pdn_py.grid_list___nonzero__(self)

    def __bool__(self):
        return _pdn_py.grid_list___bool__(self)

    def __len__(self):
        return _pdn_py.grid_list___len__(self)

    def __getslice__(self, i, j):
        return _pdn_py.grid_list___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pdn_py.grid_list___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pdn_py.grid_list___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pdn_py.grid_list___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pdn_py.grid_list___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pdn_py.grid_list___setitem__(self, *args)

    def pop(self):
        return _pdn_py.grid_list_pop(self)

    def append(self, x):
        return _pdn_py.grid_list_append(self, x)

    def empty(self):
        return _pdn_py.grid_list_empty(self)

    def size(self):
        return _pdn_py.grid_list_size(self)

    def swap(self, v):
        return _pdn_py.grid_list_swap(self, v)

    def begin(self):
        return _pdn_py.grid_list_begin(self)

    def end(self):
        return _pdn_py.grid_list_end(self)

    def rbegin(self):
        return _pdn_py.grid_list_rbegin(self)

    def rend(self):
        return _pdn_py.grid_list_rend(self)

    def clear(self):
        return _pdn_py.grid_list_clear(self)

    def get_allocator(self):
        return _pdn_py.grid_list_get_allocator(self)

    def pop_back(self):
        return _pdn_py.grid_list_pop_back(self)

    def erase(self, *args):
        return _pdn_py.grid_list_erase(self, *args)

    def __init__(self, *args):
        _pdn_py.grid_list_swiginit(self, _pdn_py.new_grid_list(*args))

    def push_back(self, x):
        return _pdn_py.grid_list_push_back(self, x)

    def front(self):
        return _pdn_py.grid_list_front(self)

    def back(self):
        return _pdn_py.grid_list_back(self)

    def assign(self, n, x):
        return _pdn_py.grid_list_assign(self, n, x)

    def resize(self, *args):
        return _pdn_py.grid_list_resize(self, *args)

    def insert(self, *args):
        return _pdn_py.grid_list_insert(self, *args)

    def reserve(self, n):
        return _pdn_py.grid_list_reserve(self, n)

    def capacity(self):
        return _pdn_py.grid_list_capacity(self)
    __swig_destroy__ = _pdn_py.delete_grid_list

# Register grid_list in _pdn_py:
_pdn_py.grid_list_swigregister(grid_list)

class domain_list(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def iterator(self):
        return _pdn_py.domain_list_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pdn_py.domain_list___nonzero__(self)

    def __bool__(self):
        return _pdn_py.domain_list___bool__(self)

    def __len__(self):
        return _pdn_py.domain_list___len__(self)

    def __getslice__(self, i, j):
        return _pdn_py.domain_list___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pdn_py.domain_list___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pdn_py.domain_list___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pdn_py.domain_list___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pdn_py.domain_list___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pdn_py.domain_list___setitem__(self, *args)

    def pop(self):
        return _pdn_py.domain_list_pop(self)

    def append(self, x):
        return _pdn_py.domain_list_append(self, x)

    def empty(self):
        return _pdn_py.domain_list_empty(self)

    def size(self):
        return _pdn_py.domain_list_size(self)

    def swap(self, v):
        return _pdn_py.domain_list_swap(self, v)

    def begin(self):
        return _pdn_py.domain_list_begin(self)

    def end(self):
        return _pdn_py.domain_list_end(self)

    def rbegin(self):
        return _pdn_py.domain_list_rbegin(self)

    def rend(self):
        return _pdn_py.domain_list_rend(self)

    def clear(self):
        return _pdn_py.domain_list_clear(self)

    def get_allocator(self):
        return _pdn_py.domain_list_get_allocator(self)

    def pop_back(self):
        return _pdn_py.domain_list_pop_back(self)

    def erase(self, *args):
        return _pdn_py.domain_list_erase(self, *args)

    def __init__(self, *args):
        _pdn_py.domain_list_swiginit(self, _pdn_py.new_domain_list(*args))

    def push_back(self, x):
        return _pdn_py.domain_list_push_back(self, x)

    def front(self):
        return _pdn_py.domain_list_front(self)

    def back(self):
        return _pdn_py.domain_list_back(self)

    def assign(self, n, x):
        return _pdn_py.domain_list_assign(self, n, x)

    def resize(self, *args):
        return _pdn_py.domain_list_resize(self, *args)

    def insert(self, *args):
        return _pdn_py.domain_list_insert(self, *args)

    def reserve(self, n):
        return _pdn_py.domain_list_reserve(self, n)

    def capacity(self):
        return _pdn_py.domain_list_capacity(self)
    __swig_destroy__ = _pdn_py.delete_domain_list

# Register domain_list in _pdn_py:
_pdn_py.domain_list_swigregister(domain_list)

class net_list(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def iterator(self):
        return _pdn_py.net_list_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pdn_py.net_list___nonzero__(self)

    def __bool__(self):
        return _pdn_py.net_list___bool__(self)

    def __len__(self):
        return _pdn_py.net_list___len__(self)

    def __getslice__(self, i, j):
        return _pdn_py.net_list___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pdn_py.net_list___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pdn_py.net_list___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pdn_py.net_list___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pdn_py.net_list___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pdn_py.net_list___setitem__(self, *args)

    def pop(self):
        return _pdn_py.net_list_pop(self)

    def append(self, x):
        return _pdn_py.net_list_append(self, x)

    def empty(self):
        return _pdn_py.net_list_empty(self)

    def size(self):
        return _pdn_py.net_list_size(self)

    def swap(self, v):
        return _pdn_py.net_list_swap(self, v)

    def begin(self):
        return _pdn_py.net_list_begin(self)

    def end(self):
        return _pdn_py.net_list_end(self)

    def rbegin(self):
        return _pdn_py.net_list_rbegin(self)

    def rend(self):
        return _pdn_py.net_list_rend(self)

    def clear(self):
        return _pdn_py.net_list_clear(self)

    def get_allocator(self):
        return _pdn_py.net_list_get_allocator(self)

    def pop_back(self):
        return _pdn_py.net_list_pop_back(self)

    def erase(self, *args):
        return _pdn_py.net_list_erase(self, *args)

    def __init__(self, *args):
        _pdn_py.net_list_swiginit(self, _pdn_py.new_net_list(*args))

    def push_back(self, x):
        return _pdn_py.net_list_push_back(self, x)

    def front(self):
        return _pdn_py.net_list_front(self)

    def back(self):
        return _pdn_py.net_list_back(self)

    def assign(self, n, x):
        return _pdn_py.net_list_assign(self, n, x)

    def resize(self, *args):
        return _pdn_py.net_list_resize(self, *args)

    def insert(self, *args):
        return _pdn_py.net_list_insert(self, *args)

    def reserve(self, n):
        return _pdn_py.net_list_reserve(self, n)

    def capacity(self):
        return _pdn_py.net_list_capacity(self)
    __swig_destroy__ = _pdn_py.delete_net_list

# Register net_list in _pdn_py:
_pdn_py.net_list_swigregister(net_list)

class viagen_list(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def iterator(self):
        return _pdn_py.viagen_list_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pdn_py.viagen_list___nonzero__(self)

    def __bool__(self):
        return _pdn_py.viagen_list___bool__(self)

    def __len__(self):
        return _pdn_py.viagen_list___len__(self)

    def __getslice__(self, i, j):
        return _pdn_py.viagen_list___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pdn_py.viagen_list___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pdn_py.viagen_list___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pdn_py.viagen_list___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pdn_py.viagen_list___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pdn_py.viagen_list___setitem__(self, *args)

    def pop(self):
        return _pdn_py.viagen_list_pop(self)

    def append(self, x):
        return _pdn_py.viagen_list_append(self, x)

    def empty(self):
        return _pdn_py.viagen_list_empty(self)

    def size(self):
        return _pdn_py.viagen_list_size(self)

    def swap(self, v):
        return _pdn_py.viagen_list_swap(self, v)

    def begin(self):
        return _pdn_py.viagen_list_begin(self)

    def end(self):
        return _pdn_py.viagen_list_end(self)

    def rbegin(self):
        return _pdn_py.viagen_list_rbegin(self)

    def rend(self):
        return _pdn_py.viagen_list_rend(self)

    def clear(self):
        return _pdn_py.viagen_list_clear(self)

    def get_allocator(self):
        return _pdn_py.viagen_list_get_allocator(self)

    def pop_back(self):
        return _pdn_py.viagen_list_pop_back(self)

    def erase(self, *args):
        return _pdn_py.viagen_list_erase(self, *args)

    def __init__(self, *args):
        _pdn_py.viagen_list_swiginit(self, _pdn_py.new_viagen_list(*args))

    def push_back(self, x):
        return _pdn_py.viagen_list_push_back(self, x)

    def front(self):
        return _pdn_py.viagen_list_front(self)

    def back(self):
        return _pdn_py.viagen_list_back(self)

    def assign(self, n, x):
        return _pdn_py.viagen_list_assign(self, n, x)

    def resize(self, *args):
        return _pdn_py.viagen_list_resize(self, *args)

    def insert(self, *args):
        return _pdn_py.viagen_list_insert(self, *args)

    def reserve(self, n):
        return _pdn_py.viagen_list_reserve(self, n)

    def capacity(self):
        return _pdn_py.viagen_list_capacity(self)
    __swig_destroy__ = _pdn_py.delete_viagen_list

# Register viagen_list in _pdn_py:
_pdn_py.viagen_list_swigregister(viagen_list)

class techvia_list(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def iterator(self):
        return _pdn_py.techvia_list_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pdn_py.techvia_list___nonzero__(self)

    def __bool__(self):
        return _pdn_py.techvia_list___bool__(self)

    def __len__(self):
        return _pdn_py.techvia_list___len__(self)

    def __getslice__(self, i, j):
        return _pdn_py.techvia_list___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pdn_py.techvia_list___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pdn_py.techvia_list___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pdn_py.techvia_list___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pdn_py.techvia_list___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pdn_py.techvia_list___setitem__(self, *args)

    def pop(self):
        return _pdn_py.techvia_list_pop(self)

    def append(self, x):
        return _pdn_py.techvia_list_append(self, x)

    def empty(self):
        return _pdn_py.techvia_list_empty(self)

    def size(self):
        return _pdn_py.techvia_list_size(self)

    def swap(self, v):
        return _pdn_py.techvia_list_swap(self, v)

    def begin(self):
        return _pdn_py.techvia_list_begin(self)

    def end(self):
        return _pdn_py.techvia_list_end(self)

    def rbegin(self):
        return _pdn_py.techvia_list_rbegin(self)

    def rend(self):
        return _pdn_py.techvia_list_rend(self)

    def clear(self):
        return _pdn_py.techvia_list_clear(self)

    def get_allocator(self):
        return _pdn_py.techvia_list_get_allocator(self)

    def pop_back(self):
        return _pdn_py.techvia_list_pop_back(self)

    def erase(self, *args):
        return _pdn_py.techvia_list_erase(self, *args)

    def __init__(self, *args):
        _pdn_py.techvia_list_swiginit(self, _pdn_py.new_techvia_list(*args))

    def push_back(self, x):
        return _pdn_py.techvia_list_push_back(self, x)

    def front(self):
        return _pdn_py.techvia_list_front(self)

    def back(self):
        return _pdn_py.techvia_list_back(self)

    def assign(self, n, x):
        return _pdn_py.techvia_list_assign(self, n, x)

    def resize(self, *args):
        return _pdn_py.techvia_list_resize(self, *args)

    def insert(self, *args):
        return _pdn_py.techvia_list_insert(self, *args)

    def reserve(self, n):
        return _pdn_py.techvia_list_reserve(self, n)

    def capacity(self):
        return _pdn_py.techvia_list_capacity(self)
    __swig_destroy__ = _pdn_py.delete_techvia_list

# Register techvia_list in _pdn_py:
_pdn_py.techvia_list_swigregister(techvia_list)

class layer_list(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def iterator(self):
        return _pdn_py.layer_list_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pdn_py.layer_list___nonzero__(self)

    def __bool__(self):
        return _pdn_py.layer_list___bool__(self)

    def __len__(self):
        return _pdn_py.layer_list___len__(self)

    def __getslice__(self, i, j):
        return _pdn_py.layer_list___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pdn_py.layer_list___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pdn_py.layer_list___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pdn_py.layer_list___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pdn_py.layer_list___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pdn_py.layer_list___setitem__(self, *args)

    def pop(self):
        return _pdn_py.layer_list_pop(self)

    def append(self, x):
        return _pdn_py.layer_list_append(self, x)

    def empty(self):
        return _pdn_py.layer_list_empty(self)

    def size(self):
        return _pdn_py.layer_list_size(self)

    def swap(self, v):
        return _pdn_py.layer_list_swap(self, v)

    def begin(self):
        return _pdn_py.layer_list_begin(self)

    def end(self):
        return _pdn_py.layer_list_end(self)

    def rbegin(self):
        return _pdn_py.layer_list_rbegin(self)

    def rend(self):
        return _pdn_py.layer_list_rend(self)

    def clear(self):
        return _pdn_py.layer_list_clear(self)

    def get_allocator(self):
        return _pdn_py.layer_list_get_allocator(self)

    def pop_back(self):
        return _pdn_py.layer_list_pop_back(self)

    def erase(self, *args):
        return _pdn_py.layer_list_erase(self, *args)

    def __init__(self, *args):
        _pdn_py.layer_list_swiginit(self, _pdn_py.new_layer_list(*args))

    def push_back(self, x):
        return _pdn_py.layer_list_push_back(self, x)

    def front(self):
        return _pdn_py.layer_list_front(self)

    def back(self):
        return _pdn_py.layer_list_back(self)

    def assign(self, n, x):
        return _pdn_py.layer_list_assign(self, n, x)

    def resize(self, *args):
        return _pdn_py.layer_list_resize(self, *args)

    def insert(self, *args):
        return _pdn_py.layer_list_insert(self, *args)

    def reserve(self, n):
        return _pdn_py.layer_list_reserve(self, n)

    def capacity(self):
        return _pdn_py.layer_list_capacity(self)
    __swig_destroy__ = _pdn_py.delete_layer_list

# Register layer_list in _pdn_py:
_pdn_py.layer_list_swigregister(layer_list)

class net_set(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def iterator(self):
        return _pdn_py.net_set_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pdn_py.net_set___nonzero__(self)

    def __bool__(self):
        return _pdn_py.net_set___bool__(self)

    def __len__(self):
        return _pdn_py.net_set___len__(self)

    def append(self, x):
        return _pdn_py.net_set_append(self, x)

    def __contains__(self, x):
        return _pdn_py.net_set___contains__(self, x)

    def __getitem__(self, i):
        return _pdn_py.net_set___getitem__(self, i)

    def add(self, x):
        return _pdn_py.net_set_add(self, x)

    def discard(self, x):
        return _pdn_py.net_set_discard(self, x)

    def __init__(self, *args):
        _pdn_py.net_set_swiginit(self, _pdn_py.new_net_set(*args))

    def empty(self):
        return _pdn_py.net_set_empty(self)

    def size(self):
        return _pdn_py.net_set_size(self)

    def clear(self):
        return _pdn_py.net_set_clear(self)

    def swap(self, v):
        return _pdn_py.net_set_swap(self, v)

    def count(self, x):
        return _pdn_py.net_set_count(self, x)

    def begin(self):
        return _pdn_py.net_set_begin(self)

    def end(self):
        return _pdn_py.net_set_end(self)

    def rbegin(self):
        return _pdn_py.net_set_rbegin(self)

    def rend(self):
        return _pdn_py.net_set_rend(self)

    def erase(self, *args):
        return _pdn_py.net_set_erase(self, *args)

    def find(self, x):
        return _pdn_py.net_set_find(self, x)

    def lower_bound(self, x):
        return _pdn_py.net_set_lower_bound(self, x)

    def upper_bound(self, x):
        return _pdn_py.net_set_upper_bound(self, x)

    def equal_range(self, x):
        return _pdn_py.net_set_equal_range(self, x)

    def insert(self, __x):
        return _pdn_py.net_set_insert(self, __x)
    __swig_destroy__ = _pdn_py.delete_net_set

# Register net_set in _pdn_py:
_pdn_py.net_set_swigregister(net_set)

CORE = _pdn_py.CORE
RINGS = _pdn_py.RINGS
BOUNDARY = _pdn_py.BOUNDARY
FIXED = _pdn_py.FIXED
GRID = _pdn_py.GRID
POWER = _pdn_py.POWER
GROUND = _pdn_py.GROUND
STAR = _pdn_py.STAR
DAISY = _pdn_py.DAISY
class PdnGen(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, db, logger):
        _pdn_py.PdnGen_swiginit(self, _pdn_py.new_PdnGen(db, logger))
    __swig_destroy__ = _pdn_py.delete_PdnGen

    def reset(self):
        return _pdn_py.PdnGen_reset(self)

    def resetShapes(self):
        return _pdn_py.PdnGen_resetShapes(self)

    def report(self):
        return _pdn_py.PdnGen_report(self)

    def findSwitchedPowerCell(self, name):
        return _pdn_py.PdnGen_findSwitchedPowerCell(self, name)

    def makeSwitchedPowerCell(self, master, control, acknowledge, switched_power, alwayson_power, ground):
        return _pdn_py.PdnGen_makeSwitchedPowerCell(self, master, control, acknowledge, switched_power, alwayson_power, ground)

    def getSwitchedPowerCells(self):
        return _pdn_py.PdnGen_getSwitchedPowerCells(self)

    def getDomains(self):
        return _pdn_py.PdnGen_getDomains(self)

    def findDomain(self, name):
        return _pdn_py.PdnGen_findDomain(self, name)

    def setCoreDomain(self, power, switched_power, ground, secondary):
        return _pdn_py.PdnGen_setCoreDomain(self, power, switched_power, ground, secondary)

    def makeRegionVoltageDomain(self, name, power, switched_power, ground, secondary_nets, region):
        return _pdn_py.PdnGen_makeRegionVoltageDomain(self, name, power, switched_power, ground, secondary_nets, region)

    def buildGrids(self, trim):
        return _pdn_py.PdnGen_buildGrids(self, trim)

    def findGrid(self, name):
        return _pdn_py.PdnGen_findGrid(self, name)

    def makeCoreGrid(self, domain, name, starts_with, pin_layers, generate_obstructions, powercell, powercontrol, powercontrolnetwork):
        return _pdn_py.PdnGen_makeCoreGrid(self, domain, name, starts_with, pin_layers, generate_obstructions, powercell, powercontrol, powercontrolnetwork)

    def makeInstanceGrid(self, domain, name, starts_with, inst, halo, pg_pins_to_boundary, default_grid, generate_obstructions, is_bump):
        return _pdn_py.PdnGen_makeInstanceGrid(self, domain, name, starts_with, inst, halo, pg_pins_to_boundary, default_grid, generate_obstructions, is_bump)

    def makeExistingGrid(self, name, generate_obstructions):
        return _pdn_py.PdnGen_makeExistingGrid(self, name, generate_obstructions)

    def makeRing(self, grid, layer0, width0, spacing0, layer1, width1, spacing1, starts_with, offset, pad_offset, extend, pad_pin_layers, nets, allow_out_of_die):
        return _pdn_py.PdnGen_makeRing(self, grid, layer0, width0, spacing0, layer1, width1, spacing1, starts_with, offset, pad_offset, extend, pad_pin_layers, nets, allow_out_of_die)

    def makeFollowpin(self, grid, layer, width, extend):
        return _pdn_py.PdnGen_makeFollowpin(self, grid, layer, width, extend)

    def makeStrap(self, grid, layer, width, spacing, pitch, offset, number_of_straps, snap, starts_with, extend, nets):
        return _pdn_py.PdnGen_makeStrap(self, grid, layer, width, spacing, pitch, offset, number_of_straps, snap, starts_with, extend, nets)

    def makeConnect(self, grid, layer0, layer1, cut_pitch_x, cut_pitch_y, vias, techvias, max_rows, max_columns, ongrid, split_cuts, dont_use_vias):
        return _pdn_py.PdnGen_makeConnect(self, grid, layer0, layer1, cut_pitch_x, cut_pitch_y, vias, techvias, max_rows, max_columns, ongrid, split_cuts, dont_use_vias)

    def writeToDb(self, *args):
        return _pdn_py.PdnGen_writeToDb(self, *args)

    def ripUp(self, net):
        return _pdn_py.PdnGen_ripUp(self, net)

    def setDebugRenderer(self, on):
        return _pdn_py.PdnGen_setDebugRenderer(self, on)

    def rendererRedraw(self):
        return _pdn_py.PdnGen_rendererRedraw(self)

    def setAllowRepairChannels(self, allow):
        return _pdn_py.PdnGen_setAllowRepairChannels(self, allow)

    def filterVias(self, filter):
        return _pdn_py.PdnGen_filterVias(self, filter)

    def checkSetup(self):
        return _pdn_py.PdnGen_checkSetup(self)

    def repairVias(self, nets):
        return _pdn_py.PdnGen_repairVias(self, nets)

    def createSrouteWires(self, net, outerNet, layer0, layer1, cut_pitch_x, cut_pitch_y, vias, techvias, max_rows, max_columns, ongrid, metalWidths, metalspaces, insts):
        return _pdn_py.PdnGen_createSrouteWires(self, net, outerNet, layer0, layer1, cut_pitch_x, cut_pitch_y, vias, techvias, max_rows, max_columns, ongrid, metalWidths, metalspaces, insts)

    def getDebugRenderer(self):
        return _pdn_py.PdnGen_getDebugRenderer(self)

# Register PdnGen in _pdn_py:
_pdn_py.PdnGen_swigregister(PdnGen)



