# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2025, The OpenROAD Authors

# Python scripts and utilities for documentation tests
filegroup(
    name = "doc_test_utils",
    srcs = [
        "extract_utils.py",
        "man_tcl_check.py",
        "md_roff_compat.py",
        "readme_msgs_check.py",
    ],
    visibility = ["//visibility:public"],
)
