# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2026, The OpenROAD Authors

load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "extract_utils",
    srcs = ["extract_utils.py"],
    visibility = ["//visibility:public"],
)
