if(EXISTS "/home/memzfs_projects/MLBuf_extension/OR_latest/build/src/rmp/test/cpp/RmpGTests[1]_tests.cmake")
  include("/home/memzfs_projects/MLBuf_extension/OR_latest/build/src/rmp/test/cpp/RmpGTests[1]_tests.cmake")
else()
  add_test(RmpGTests_NOT_BUILT RmpGTests_NOT_BUILT)
endif()
