if(EXISTS "/home/memzfs_projects/MLBuf_extension/OR_latest/build/src/rsz/test/cpp/TestBufRem1[1]_tests.cmake")
  include("/home/memzfs_projects/MLBuf_extension/OR_latest/build/src/rsz/test/cpp/TestBufRem1[1]_tests.cmake")
else()
  add_test(TestBufRem1_NOT_BUILT TestBufRem1_NOT_BUILT)
endif()
