record_tests {
  clock_route
  est_rc1
  est_rc2
  gcd
  gcd_random1
  gcd_random2
  invalid_routing_layer
  invalid_pin_placement
  multiple_calls
  ndr_1w_3s
  ndr_2w_3s
  no_tracks
  region_adjustment
  repair_antennas1
  repair_antennas2
  repair_antennas3
  repair_antennas_error1
  repair_antennas_error2
}
