record_tests {
  clock_route
  clock_route_error1
  clock_route_error2
  est_rc1
  est_rc2
  gcd
  invalid_routing_layer
  invalid_pin_placement
  multiple_calls
  ndr_1w_3s
  ndr_2w_3s
  no_tracks
  pd1
  pd2
  region_adjustment
  repair_antennas1
  repair_antennas2
  repair_antennas3
  repair_antennas_error1
  repair_antennas_error2
}
