record_tests {
  bus_route
  clock_route
  clock_route_alpha
  clock_route_error1
  clock_route_error2
  congestion1
  congestion2
  congestion3
  congestion4
  congestion5
  congestion6
  critical_nets_percentage
  est_rc1
  est_rc2
  est_rc3
  est_rc4
  gcd
  gcd_flute
  inst_pin_out_of_die
  invalid_routing_layer
  invalid_pin_placement
  macro_obs_not_aligned
  multiple_calls
  ndr_1w_3s
  ndr_2w_3s
  no_tracks
  obs_out_of_die
  overlapping_edges
  pd1
  pd2
  pd3
  pd4
  pin_access1
  pin_access2
  pin_track_not_aligned
  pre_routed1
  region_adjustment
  repair_antennas1
  repair_antennas2
  repair_antennas3
  repair_antennas4
  repair_antennas_error1
  repair_antennas_error2
  report_wire_length1
  report_wire_length2
  report_wire_length3
  report_wire_length4
  report_wire_length5
  report_wire_length6
  silence
  top_level_term
  tracks1
  tracks2
  tracks3
  upper_layer_net
}
