#!/usr/bin/env bash

# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2024-2025, The OpenROAD Authors

set -e

script_dir="$(dirname "$(readlink -f "$0")")/../../../test/shared"
bazel_pending=()

for test_name in "${@:1}"
do
    if [ -f "results/${test_name}-tcl.guide" ]; then
        cp "results/${test_name}-tcl.guide" "${test_name}.guideok"
        echo "${test_name}"
    elif [ -f "results/${test_name}-py.guide" ]; then
        cp "results/${test_name}-py.guide" "${test_name}.guideok"
        echo "${test_name}"
    else
        bazel_pending+=("${test_name}")
    fi
done

if [ ${#bazel_pending[@]} -gt 0 ]; then
    "${script_dir}/bazel_save.sh" guideok guide "${bazel_pending[@]}"
fi
