name: Lint Bazel (Buildifier)

on:
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ${{ vars.USE_SELF_HOSTED == 'true' && 'self-hosted' || 'ubuntu-latest' }}
    env:
      BUILDIFIER_VERSION: v8.2.1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Download buildifier
        run: |
          wget https://github.com/bazelbuild/buildtools/releases/download/${BUILDIFIER_VERSION}/buildifier-linux-amd64 -O buildifier
          chmod +x buildifier

      - name: Run buildifier (format check)
        run: ./buildifier -r -mode=check -lint=off .

      - name: Run buildifier (lint)
        if: always()
        run: ./buildifier -r -lint=warn .
