name: Lint Python

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  Black:
    runs-on: ${{ vars.USE_SELF_HOSTED == 'true' && 'self-hosted' || 'ubuntu-latest' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: Run black
        uses: psf/black@87928e6d6761a4a6d22250e1fee5601b3998086e  # 26.5.1
