name: Test DependencyInstaller script
on:
  schedule:
  - cron: "0 8 * * SUN"
  push:
    paths:
      - 'etc/DependencyInstaller.sh'
      - 'docker/*'
      - '.github/workflows/github-actions-test-installer.yml'
  pull_request:
    paths:
      - 'etc/DependencyInstaller.sh'
      - 'docker/*'
      - '.github/workflows/github-actions-test-installer.yml'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  testInstaller:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu20.04", "ubuntu22.04", "centos7", "rhel", "debian10", "debian11", "opensuse"]
        args: ["", "-local", "-no_eqy", "-no_eqy -local"]
        compilers: ["gcc", "clang"]
        exclude:
          - os: "opensuse"
            compilers: "clang"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: recursive
      - name: Network Setup
        run: |
          sudo apt-get update
          sudo apt-get install -y bridge-utils
          sudo pkill docker
          sudo iptables -t nat -F
          sudo ifconfig docker0 down
          sudo brctl delbr docker0
          sudo service docker restart
      - name: Run installer
        run: |
          ./etc/DockerHelper.sh create -target=dev -os=${{ matrix.os }} ${{ matrix.args }}
      - name: Build project
        run: |
          ./etc/DockerHelper.sh create -target=builder -os=${{ matrix.os }} -compiler=${{ matrix.compilers }} ${{ matrix.args }}
      - name: Test build
        run: |
          if [[ ${{ matrix.os }} == "centos7" ]]; then
            docker run openroad/${{ matrix.os }}-builder-${{ matrix.compilers }} /bin/bash -c "source /opt/rh/llvm-toolset-7.0/enable; source /opt/rh/devtoolset-8/enable; build/src/openroad -help;"
          else
            docker run openroad/${{ matrix.os }}-builder-${{ matrix.compilers }} build/src/openroad -help
          fi
