name: bazel-build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Create Cache Timestamp
        id: cache_timestamp
        uses: nanzm/get-time-action@v2.0
        with:
          format: 'YYYY-MM-DD-HH-mm-ss'

      - name: Mount bazel cache
        uses: actions/cache@v4
        with:
          path: "~/.cache/bazel"
          key: bazelcache_${{ steps.cache_timestamp.outputs.time }}
          restore-keys: bazelcache_

      - name: Build
        run: |
          # There are no cc_test()s yet, so just build for now.
          # For now, just run, but don't fail the whole CI, as bazel build is
          # experimental at this stage.
          bazel build --keep_going --show_timestamps --curses=no ... || /bin/true

      - name: Smoke test
        run: |
          bazel-bin/openroad -help

      - name: Trim Bazel Cache
        run: |
          echo "Trim download cache"
          du -sh $(bazel info repository_cache)
          rm -r $(bazel info repository_cache)

          echo "Other remaining things that are big"
          du -h -t 200M ~/.cache/bazel/*/ | sort -hr
