name: bazel-build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Create Cache Timestamp
        id: cache_timestamp
        uses: nanzm/get-time-action@v2.0
        with:
          format: 'YYYY-MM-DD-HH-mm-ss'

      - name: Mount bazel cache
        uses: actions/cache@v4
        with:
          path: "~/.cache/bazel"
          key: bazelcache_${{ steps.cache_timestamp.outputs.time }}
          restore-keys: bazelcache_

      - name: Build
        run: |
          # FIXME When we're fully switched to MODULE.bazel, we can
          # select tests with a simple top level "...", but for
          # now we don't want to build any tests that "..." picks
          # up from WORKSPACE. Also, we don't want to build any
          # tests that are marked as tags=["manual"], because
          # it is used as a feature-toggle for unfinished tests
          # that are in master for collaboration prior to deployment.
          bazel test \
           -c opt \
           --keep_going \
           --show_timestamps \
           --test_output=errors \
           --curses=no \
           --force_pic \
           --build_tag_filters=-manual \
           test/... src/...

      - name: Smoke test
        run: |
          bazel-bin/openroad -help

      - name: Trim Bazel Cache
        run: |
          echo "Trim download cache"
          du -sh $(bazel info repository_cache)
          rm -r $(bazel info repository_cache)

          echo "Other remaining things that are big"
          du -h -t 200M ~/.cache/bazel/*/ | sort -hr
