name: Ubuntu Stable Build

on:
  push:
    branches:
      - ubuntu-build

jobs:
  build:
    name: Compile OpenROAD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Update System
        run: |
          sudo apt update
          sudo apt upgrade -y

      - name: Install Dependencies
        run: |
          sudo ./etc/DependencyInstaller.sh -base
          ./etc/DependencyInstaller.sh -common -local

      - name: Build OpenROAD
        run: |
          ./etc/Build.sh

      - name: Verify Binary
        run: |
          ls build/bin
          ./build/bin/openroad -version

      - name: Create Debian Package
        run: |
          mkdir -p package/usr/bin
          cp build/bin/openroad package/usr/bin/

          mkdir -p package/DEBIAN
          cat <<EOF > package/DEBIAN/control
          Package: openroad
          Version: 1.0
          Section: electronics
          Priority: optional
          Architecture: amd64
          Maintainer: Hemant Kumar
          Description: OpenROAD physical design automation tool
          EOF

          dpkg-deb --build package openroad_amd64.deb

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: openroad-deb
          path: openroad_amd64.deb

      - name: Create Pre Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ubuntu-build-${{ github.run_number }}
          name: OpenROAD Pre-release
          prerelease: true
          files: openroad_amd64.deb
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}