if(EXISTS "/home/memzfs_projects/MLBuf_extension/OR_latest/build/src/utl/test/cpp/TestSuppressStdout[1]_tests.cmake")
  include("/home/memzfs_projects/MLBuf_extension/OR_latest/build/src/utl/test/cpp/TestSuppressStdout[1]_tests.cmake")
else()
  add_test(TestSuppressStdout_NOT_BUILT TestSuppressStdout_NOT_BUILT)
endif()
